
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Apr  8 2026 16:33:22 PDT (Apr  8 2026 23:33:22 UTC)

// Verification Directory fv/prbs_gen_top 

module CLKGATE_RC_CG_MOD_mapped(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP7T RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module prbs_core_LFSR_W7_DEFAULT_SEED1_mapped(clk, rst_n, load_req,
     seed_value, step_en, prbs_out, state_out);
  input clk, rst_n, load_req, step_en;
  input [6:0] seed_value;
  output prbs_out;
  output [6:0] state_out;
  wire clk, rst_n, load_req, step_en;
  wire [6:0] seed_value;
  wire prbs_out;
  wire [6:0] state_out;
  wire [6:0] lfsr_q;
  wire CLKGATE_rc_gclk, UNCONNECTED, logic_0_1_net, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_10;
  CLKGATE_RC_CG_MOD_mapped CLKGATE_RC_CG_HIER_INST0(.enable (n_10),
       .ck_in (clk), .ck_out (CLKGATE_rc_gclk), .test (logic_0_1_net));
  DFKCNQD1BWP7T \lfsr_q_reg[4] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_8), .Q (lfsr_q[4]));
  CKMUX2D1BWP7T g161__2398(.I0 (lfsr_q[3]), .I1 (seed_value[4]), .S
       (load_req), .Z (n_8));
  DFKCNQD1BWP7T \lfsr_q_reg[3] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_7), .Q (lfsr_q[3]));
  CKMUX2D1BWP7T g163__5107(.I0 (lfsr_q[2]), .I1 (seed_value[3]), .S
       (load_req), .Z (n_7));
  DFKCNQD1BWP7T \lfsr_q_reg[2] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_6), .Q (lfsr_q[2]));
  CKMUX2D1BWP7T g165__6260(.I0 (lfsr_q[1]), .I1 (seed_value[2]), .S
       (load_req), .Z (n_6));
  DFKCNQD1BWP7T \lfsr_q_reg[1] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_5), .Q (lfsr_q[1]));
  IND3D0BWP7T g167__4319(.A1 (step_en), .B1 (rst_n), .B2 (n_4), .ZN
       (n_10));
  CKMUX2D1BWP7T g168__8428(.I0 (lfsr_q[0]), .I1 (seed_value[1]), .S
       (load_req), .Z (n_5));
  INVD0BWP7T g169(.I (load_req), .ZN (n_4));
  DFKSND1BWP7T \lfsr_q_reg[0] (.CP (CLKGATE_rc_gclk), .D (n_3), .SN
       (rst_n), .Q (lfsr_q[0]), .QN (UNCONNECTED));
  CKMUX2D1BWP7T g135__5526(.I0 (n_2), .I1 (seed_value[0]), .S
       (load_req), .Z (n_3));
  CKXOR2D1BWP7T g136__6783(.A1 (prbs_out), .A2 (lfsr_q[5]), .Z (n_2));
  DFKCNQD1BWP7T \lfsr_q_reg[5] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_1), .Q (lfsr_q[5]));
  DFKCNQD1BWP7T \lfsr_q_reg[6] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_0), .Q (prbs_out));
  CKMUX2D1BWP7T g138__3680(.I0 (lfsr_q[4]), .I1 (seed_value[5]), .S
       (load_req), .Z (n_1));
  CKMUX2D1BWP7T g139__1617(.I0 (lfsr_q[5]), .I1 (seed_value[6]), .S
       (load_req), .Z (n_0));
  TIELBWP7T tie_0_cell(.ZN (logic_0_1_net));
  TIELBWP7T tie_0_cell1(.ZN (state_out[0]));
  TIELBWP7T tie_0_cell2(.ZN (state_out[1]));
  TIELBWP7T tie_0_cell3(.ZN (state_out[2]));
  TIELBWP7T tie_0_cell4(.ZN (state_out[3]));
  TIELBWP7T tie_0_cell5(.ZN (state_out[4]));
  TIELBWP7T tie_0_cell6(.ZN (state_out[5]));
  TIELBWP7T tie_0_cell7(.ZN (state_out[6]));
endmodule

module prbs_ctrl_LFSR_W7_DEFAULT_SEED1_mapped(seed_load, seed_in, en,
     load_req, seed_value, step_en);
  input seed_load, en;
  input [6:0] seed_in;
  output load_req, step_en;
  output [6:0] seed_value;
  wire seed_load, en;
  wire [6:0] seed_in;
  wire load_req, step_en;
  wire [6:0] seed_value;
  wire n_1, n_2;
  AO21D0BWP7T g69__2802(.A1 (n_2), .A2 (n_1), .B (seed_in[0]), .Z
       (seed_value[0]));
  NR4D0BWP7T g70__1705(.A1 (seed_in[6]), .A2 (seed_in[5]), .A3
       (seed_in[4]), .A4 (seed_in[3]), .ZN (n_2));
  NR2D0BWP7T g71__5122(.A1 (seed_in[2]), .A2 (seed_in[1]), .ZN (n_1));
  TIELBWP7T tie_0_cell(.ZN (load_req));
  TIELBWP7T tie_0_cell1(.ZN (seed_value[1]));
  TIELBWP7T tie_0_cell2(.ZN (seed_value[2]));
  TIELBWP7T tie_0_cell3(.ZN (seed_value[3]));
  TIELBWP7T tie_0_cell4(.ZN (seed_value[4]));
  TIELBWP7T tie_0_cell5(.ZN (seed_value[5]));
  TIELBWP7T tie_0_cell6(.ZN (seed_value[6]));
  TIELBWP7T tie_0_cell7(.ZN (step_en));
endmodule

module prbs_top_mapped(clk, rst_n, en, seed_load, seed_in, prbs_out);
  input clk, rst_n, en, seed_load;
  input [6:0] seed_in;
  output prbs_out;
  wire clk, rst_n, en, seed_load;
  wire [6:0] seed_in;
  wire prbs_out;
  wire [6:0] seed_value;
  wire [6:0] prbs_state;
  wire UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, UNCONNECTED3,
       UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7;
  wire logic_0_1_net, logic_0_2_net;
  prbs_core_LFSR_W7_DEFAULT_SEED1_mapped u_prbs_core(.clk (clk), .rst_n
       (rst_n), .load_req (seed_load), .seed_value ({seed_in[6:1],
       seed_value[0]}), .step_en (en), .prbs_out (prbs_out), .state_out
       (prbs_state));
  prbs_ctrl_LFSR_W7_DEFAULT_SEED1_mapped u_prbs_ctrl(.seed_load
       (logic_0_2_net), .seed_in (seed_in), .en (logic_0_1_net),
       .load_req (UNCONNECTED0), .seed_value ({UNCONNECTED6,
       UNCONNECTED5, UNCONNECTED4, UNCONNECTED3, UNCONNECTED2,
       UNCONNECTED1, seed_value[0]}), .step_en (UNCONNECTED7));
  TIELBWP7T tie_0_cell(.ZN (logic_0_1_net));
  TIELBWP7T tie_0_cell1(.ZN (logic_0_2_net));
endmodule

module CLKGATE_RC_CG_MOD_1_mapped(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP7T RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module prbs15_core_LFSR_W15_DEFAULT_SEED1_mapped(clk, rst_n, load_req,
     seed_value, step_en, prbs_out, state_out);
  input clk, rst_n, load_req, step_en;
  input [14:0] seed_value;
  output prbs_out;
  output [14:0] state_out;
  wire clk, rst_n, load_req, step_en;
  wire [14:0] seed_value;
  wire prbs_out;
  wire [14:0] state_out;
  wire [14:0] lfsr_q;
  wire CLKGATE_rc_gclk, UNCONNECTED8, logic_0_1_net, n_0, n_1, n_2,
       n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_18;
  CLKGATE_RC_CG_MOD_1_mapped CLKGATE_RC_CG_HIER_INST1(.enable (n_18),
       .ck_in (clk), .ck_out (CLKGATE_rc_gclk), .test (logic_0_1_net));
  DFKCNQD1BWP7T \lfsr_q_reg[12] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_16), .Q (lfsr_q[12]));
  CKMUX2D1BWP7T g308__8246(.I0 (lfsr_q[11]), .I1 (seed_value[12]), .S
       (load_req), .Z (n_16));
  DFKCNQD1BWP7T \lfsr_q_reg[11] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_15), .Q (lfsr_q[11]));
  CKMUX2D1BWP7T g310__7098(.I0 (lfsr_q[10]), .I1 (seed_value[11]), .S
       (load_req), .Z (n_15));
  DFKCNQD1BWP7T \lfsr_q_reg[10] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_14), .Q (lfsr_q[10]));
  CKMUX2D1BWP7T g312__6131(.I0 (lfsr_q[9]), .I1 (seed_value[10]), .S
       (load_req), .Z (n_14));
  DFKCNQD1BWP7T \lfsr_q_reg[9] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_13), .Q (lfsr_q[9]));
  CKMUX2D1BWP7T g314__1881(.I0 (lfsr_q[8]), .I1 (seed_value[9]), .S
       (load_req), .Z (n_13));
  DFKCNQD1BWP7T \lfsr_q_reg[8] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_12), .Q (lfsr_q[8]));
  CKMUX2D1BWP7T g316__5115(.I0 (lfsr_q[7]), .I1 (seed_value[8]), .S
       (load_req), .Z (n_12));
  DFKCNQD1BWP7T \lfsr_q_reg[7] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_11), .Q (lfsr_q[7]));
  CKMUX2D1BWP7T g318__7482(.I0 (lfsr_q[6]), .I1 (seed_value[7]), .S
       (load_req), .Z (n_11));
  DFKCNQD1BWP7T \lfsr_q_reg[6] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_10), .Q (lfsr_q[6]));
  CKMUX2D1BWP7T g320__4733(.I0 (lfsr_q[5]), .I1 (seed_value[6]), .S
       (load_req), .Z (n_10));
  DFKCNQD1BWP7T \lfsr_q_reg[5] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_9), .Q (lfsr_q[5]));
  CKMUX2D1BWP7T g322__6161(.I0 (lfsr_q[4]), .I1 (seed_value[5]), .S
       (load_req), .Z (n_9));
  DFKCNQD1BWP7T \lfsr_q_reg[4] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_8), .Q (lfsr_q[4]));
  CKMUX2D1BWP7T g324__9315(.I0 (lfsr_q[3]), .I1 (seed_value[4]), .S
       (load_req), .Z (n_8));
  DFKCNQD1BWP7T \lfsr_q_reg[3] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_7), .Q (lfsr_q[3]));
  CKMUX2D1BWP7T g326__9945(.I0 (lfsr_q[2]), .I1 (seed_value[3]), .S
       (load_req), .Z (n_7));
  DFKCNQD1BWP7T \lfsr_q_reg[2] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_6), .Q (lfsr_q[2]));
  CKMUX2D1BWP7T g328__2883(.I0 (lfsr_q[1]), .I1 (seed_value[2]), .S
       (load_req), .Z (n_6));
  DFKCNQD1BWP7T \lfsr_q_reg[1] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_5), .Q (lfsr_q[1]));
  IND3D0BWP7T g330__2346(.A1 (step_en), .B1 (rst_n), .B2 (n_4), .ZN
       (n_18));
  CKMUX2D1BWP7T g331__1666(.I0 (lfsr_q[0]), .I1 (seed_value[1]), .S
       (load_req), .Z (n_5));
  INVD2BWP7T g332(.I (load_req), .ZN (n_4));
  DFKSND1BWP7T \lfsr_q_reg[0] (.CP (CLKGATE_rc_gclk), .D (n_3), .SN
       (rst_n), .Q (lfsr_q[0]), .QN (UNCONNECTED8));
  CKMUX2D1BWP7T g215__7410(.I0 (n_2), .I1 (seed_value[0]), .S
       (load_req), .Z (n_3));
  CKXOR2D1BWP7T g216__6417(.A1 (prbs_out), .A2 (lfsr_q[13]), .Z (n_2));
  DFKCNQD1BWP7T \lfsr_q_reg[13] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_1), .Q (lfsr_q[13]));
  DFKCNQD1BWP7T \lfsr_q_reg[14] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_0), .Q (prbs_out));
  CKMUX2D1BWP7T g218__5477(.I0 (lfsr_q[12]), .I1 (seed_value[13]), .S
       (load_req), .Z (n_1));
  CKMUX2D1BWP7T g219__2398(.I0 (lfsr_q[13]), .I1 (seed_value[14]), .S
       (load_req), .Z (n_0));
  TIELBWP7T tie_0_cell(.ZN (logic_0_1_net));
  TIELBWP7T tie_0_cell1(.ZN (state_out[0]));
  TIELBWP7T tie_0_cell2(.ZN (state_out[10]));
  TIELBWP7T tie_0_cell3(.ZN (state_out[11]));
  TIELBWP7T tie_0_cell4(.ZN (state_out[12]));
  TIELBWP7T tie_0_cell5(.ZN (state_out[13]));
  TIELBWP7T tie_0_cell6(.ZN (state_out[14]));
  TIELBWP7T tie_0_cell7(.ZN (state_out[1]));
  TIELBWP7T tie_0_cell8(.ZN (state_out[2]));
  TIELBWP7T tie_0_cell9(.ZN (state_out[3]));
  TIELBWP7T tie_0_cell10(.ZN (state_out[4]));
  TIELBWP7T tie_0_cell11(.ZN (state_out[5]));
  TIELBWP7T tie_0_cell12(.ZN (state_out[6]));
  TIELBWP7T tie_0_cell13(.ZN (state_out[7]));
  TIELBWP7T tie_0_cell14(.ZN (state_out[8]));
  TIELBWP7T tie_0_cell15(.ZN (state_out[9]));
endmodule

module prbs15_ctrl_LFSR_W15_DEFAULT_SEED1_mapped(seed_load, seed_in,
     en, load_req, seed_value, step_en);
  input seed_load, en;
  input [14:0] seed_in;
  output load_req, step_en;
  output [14:0] seed_value;
  wire seed_load, en;
  wire [14:0] seed_in;
  wire load_req, step_en;
  wire [14:0] seed_value;
  wire n_1, n_2, n_3, n_4, n_5;
  OR2D0BWP7T g261__5107(.A1 (n_5), .A2 (seed_in[0]), .Z
       (seed_value[0]));
  NR4D0BWP7T g262__6260(.A1 (n_4), .A2 (seed_in[7]), .A3 (seed_in[5]),
       .A4 (seed_in[3]), .ZN (n_5));
  IND4D0BWP7T g263__4319(.A1 (seed_in[9]), .B1 (n_1), .B2 (n_3), .B3
       (n_2), .ZN (n_4));
  NR4D0BWP7T g264__8428(.A1 (seed_in[14]), .A2 (seed_in[10]), .A3
       (seed_in[4]), .A4 (seed_in[2]), .ZN (n_3));
  NR4D0BWP7T g265__5526(.A1 (seed_in[13]), .A2 (seed_in[11]), .A3
       (seed_in[6]), .A4 (seed_in[1]), .ZN (n_2));
  NR2D0BWP7T g266__6783(.A1 (seed_in[12]), .A2 (seed_in[8]), .ZN (n_1));
  TIELBWP7T tie_0_cell(.ZN (load_req));
  TIELBWP7T tie_0_cell1(.ZN (seed_value[10]));
  TIELBWP7T tie_0_cell2(.ZN (seed_value[11]));
  TIELBWP7T tie_0_cell3(.ZN (seed_value[12]));
  TIELBWP7T tie_0_cell4(.ZN (seed_value[13]));
  TIELBWP7T tie_0_cell5(.ZN (seed_value[14]));
  TIELBWP7T tie_0_cell6(.ZN (seed_value[1]));
  TIELBWP7T tie_0_cell7(.ZN (seed_value[2]));
  TIELBWP7T tie_0_cell8(.ZN (seed_value[3]));
  TIELBWP7T tie_0_cell9(.ZN (seed_value[4]));
  TIELBWP7T tie_0_cell10(.ZN (seed_value[5]));
  TIELBWP7T tie_0_cell11(.ZN (seed_value[6]));
  TIELBWP7T tie_0_cell12(.ZN (seed_value[7]));
  TIELBWP7T tie_0_cell13(.ZN (seed_value[8]));
  TIELBWP7T tie_0_cell14(.ZN (seed_value[9]));
  TIELBWP7T tie_0_cell15(.ZN (step_en));
endmodule

module prbs15_top_mapped(clk, rst_n, en, seed_load, seed_in, prbs_out);
  input clk, rst_n, en, seed_load;
  input [14:0] seed_in;
  output prbs_out;
  wire clk, rst_n, en, seed_load;
  wire [14:0] seed_in;
  wire prbs_out;
  wire [14:0] seed_value;
  wire [14:0] prbs_state;
  wire UNCONNECTED9, UNCONNECTED10, UNCONNECTED11, UNCONNECTED12,
       UNCONNECTED13, UNCONNECTED14, UNCONNECTED15, UNCONNECTED16;
  wire UNCONNECTED17, UNCONNECTED18, UNCONNECTED19, UNCONNECTED20,
       UNCONNECTED21, UNCONNECTED22, UNCONNECTED23, UNCONNECTED24;
  wire logic_0_1_net, logic_0_2_net;
  prbs15_core_LFSR_W15_DEFAULT_SEED1_mapped u_prbs15_core(.clk (clk),
       .rst_n (rst_n), .load_req (seed_load), .seed_value
       ({seed_in[14:1], seed_value[0]}), .step_en (en), .prbs_out
       (prbs_out), .state_out (prbs_state));
  prbs15_ctrl_LFSR_W15_DEFAULT_SEED1_mapped u_prbs15_ctrl(.seed_load
       (logic_0_2_net), .seed_in (seed_in), .en (logic_0_1_net),
       .load_req (UNCONNECTED9), .seed_value ({UNCONNECTED23,
       UNCONNECTED22, UNCONNECTED21, UNCONNECTED20, UNCONNECTED19,
       UNCONNECTED18, UNCONNECTED17, UNCONNECTED16, UNCONNECTED15,
       UNCONNECTED14, UNCONNECTED13, UNCONNECTED12, UNCONNECTED11,
       UNCONNECTED10, seed_value[0]}), .step_en (UNCONNECTED24));
  TIELBWP7T tie_0_cell(.ZN (logic_0_1_net));
  TIELBWP7T tie_0_cell1(.ZN (logic_0_2_net));
endmodule

module prbs_gen_top(clk, rst_n, en, seed_load, mode_select, seed_in,
     prbs_out);
  input clk, rst_n, en, seed_load, mode_select;
  input [14:0] seed_in;
  output prbs_out;
  wire clk, rst_n, en, seed_load, mode_select;
  wire [14:0] seed_in;
  wire prbs_out;
  wire n_0, n_13, n_14, n_22, n_23, prbs7_out, prbs15_out;
  prbs_top_mapped u_prbs7_top(.clk (clk), .rst_n (rst_n), .en (n_23),
       .seed_load (n_22), .seed_in (seed_in[6:0]), .prbs_out
       (prbs7_out));
  prbs15_top_mapped u_prbs15_top(.clk (clk), .rst_n (rst_n), .en
       (n_14), .seed_load (n_13), .seed_in (seed_in), .prbs_out
       (prbs15_out));
  MUX2D0BWP7T g90__3680(.I0 (prbs7_out), .I1 (prbs15_out), .S
       (mode_select), .Z (prbs_out));
  CKAN2D1BWP7T g91__1617(.A1 (n_0), .A2 (seed_load), .Z (n_22));
  INR2D0BWP7T g92__2802(.A1 (en), .B1 (mode_select), .ZN (n_23));
  INR2D0BWP7T g93__1705(.A1 (en), .B1 (n_0), .ZN (n_14));
  CKAN2D1BWP7T g94__5122(.A1 (seed_load), .A2 (mode_select), .Z (n_13));
  INVD1BWP7T g95(.I (mode_select), .ZN (n_0));
endmodule

