################################################################################
#       Setting dont_touch and dont_use preserve setting
################################################################################
catch {set_db base_cell:BHDBWP7T .dont_use true}
catch {set_db base_cell:GAN2D1BWP7T .dont_use true}
catch {set_db base_cell:GAN2D2BWP7T .dont_use true}
catch {set_db base_cell:GAOI21D1BWP7T .dont_use true}
catch {set_db base_cell:GAOI21D2BWP7T .dont_use true}
catch {set_db base_cell:GAOI22D1BWP7T .dont_use true}
catch {set_db base_cell:GBUFFD1BWP7T .dont_use true}
catch {set_db base_cell:GBUFFD2BWP7T .dont_use true}
catch {set_db base_cell:GBUFFD3BWP7T .dont_use true}
catch {set_db base_cell:GBUFFD8BWP7T .dont_use true}
catch {set_db base_cell:GDCAP10BWP7T .dont_use true}
catch {set_db base_cell:GDCAP2BWP7T .dont_use true}
catch {set_db base_cell:GDCAP3BWP7T .dont_use true}
catch {set_db base_cell:GDCAP4BWP7T .dont_use true}
catch {set_db base_cell:GDCAPBWP7T .dont_use true}
catch {set_db base_cell:GDFCNQD1BWP7T .dont_use true}
catch {set_db base_cell:GDFQD1BWP7T .dont_use true}
catch {set_db base_cell:GFILL10BWP7T .dont_use true}
catch {set_db base_cell:GFILL2BWP7T .dont_use true}
catch {set_db base_cell:GFILL3BWP7T .dont_use true}
catch {set_db base_cell:GFILL4BWP7T .dont_use true}
catch {set_db base_cell:GFILLBWP7T .dont_use true}
catch {set_db base_cell:GINVD1BWP7T .dont_use true}
catch {set_db base_cell:GINVD2BWP7T .dont_use true}
catch {set_db base_cell:GINVD3BWP7T .dont_use true}
catch {set_db base_cell:GINVD8BWP7T .dont_use true}
catch {set_db base_cell:GMUX2D1BWP7T .dont_use true}
catch {set_db base_cell:GMUX2D2BWP7T .dont_use true}
catch {set_db base_cell:GMUX2ND1BWP7T .dont_use true}
catch {set_db base_cell:GMUX2ND2BWP7T .dont_use true}
catch {set_db base_cell:GND2D1BWP7T .dont_use true}
catch {set_db base_cell:GND2D2BWP7T .dont_use true}
catch {set_db base_cell:GND2D3BWP7T .dont_use true}
catch {set_db base_cell:GND3D1BWP7T .dont_use true}
catch {set_db base_cell:GND3D2BWP7T .dont_use true}
catch {set_db base_cell:GNR2D1BWP7T .dont_use true}
catch {set_db base_cell:GNR2D2BWP7T .dont_use true}
catch {set_db base_cell:GNR3D1BWP7T .dont_use true}
catch {set_db base_cell:GNR3D2BWP7T .dont_use true}
catch {set_db base_cell:GOAI21D1BWP7T .dont_use true}
catch {set_db base_cell:GOAI21D2BWP7T .dont_use true}
catch {set_db base_cell:GOR2D1BWP7T .dont_use true}
catch {set_db base_cell:GOR2D2BWP7T .dont_use true}
catch {set_db base_cell:GSDFCNQD1BWP7T .dont_use true}
catch {set_db base_cell:GTIEHBWP7T .dont_use true}
catch {set_db base_cell:GTIELBWP7T .dont_use true}
catch {set_db base_cell:GXNR2D1BWP7T .dont_use true}
catch {set_db base_cell:GXNR2D2BWP7T .dont_use true}
catch {set_db base_cell:GXOR2D1BWP7T .dont_use true}
catch {set_db base_cell:GXOR2D2BWP7T .dont_use true}
catch {set_db base_cell:BHDBWP7T .dont_touch true}
catch {set_db base_cell:GAN2D1BWP7T .dont_touch true}
catch {set_db base_cell:GAN2D2BWP7T .dont_touch true}
catch {set_db base_cell:GAOI21D1BWP7T .dont_touch true}
catch {set_db base_cell:GAOI21D2BWP7T .dont_touch true}
catch {set_db base_cell:GAOI22D1BWP7T .dont_touch true}
catch {set_db base_cell:GBUFFD1BWP7T .dont_touch true}
catch {set_db base_cell:GBUFFD2BWP7T .dont_touch true}
catch {set_db base_cell:GBUFFD3BWP7T .dont_touch true}
catch {set_db base_cell:GBUFFD8BWP7T .dont_touch true}
catch {set_db base_cell:GDCAP10BWP7T .dont_touch true}
catch {set_db base_cell:GDCAP2BWP7T .dont_touch true}
catch {set_db base_cell:GDCAP3BWP7T .dont_touch true}
catch {set_db base_cell:GDCAP4BWP7T .dont_touch true}
catch {set_db base_cell:GDCAPBWP7T .dont_touch true}
catch {set_db base_cell:GDFCNQD1BWP7T .dont_touch true}
catch {set_db base_cell:GDFQD1BWP7T .dont_touch true}
catch {set_db base_cell:GFILL10BWP7T .dont_touch true}
catch {set_db base_cell:GFILL2BWP7T .dont_touch true}
catch {set_db base_cell:GFILL3BWP7T .dont_touch true}
catch {set_db base_cell:GFILL4BWP7T .dont_touch true}
catch {set_db base_cell:GFILLBWP7T .dont_touch true}
catch {set_db base_cell:GINVD1BWP7T .dont_touch true}
catch {set_db base_cell:GINVD2BWP7T .dont_touch true}
catch {set_db base_cell:GINVD3BWP7T .dont_touch true}
catch {set_db base_cell:GINVD8BWP7T .dont_touch true}
catch {set_db base_cell:GMUX2D1BWP7T .dont_touch true}
catch {set_db base_cell:GMUX2D2BWP7T .dont_touch true}
catch {set_db base_cell:GMUX2ND1BWP7T .dont_touch true}
catch {set_db base_cell:GMUX2ND2BWP7T .dont_touch true}
catch {set_db base_cell:GND2D1BWP7T .dont_touch true}
catch {set_db base_cell:GND2D2BWP7T .dont_touch true}
catch {set_db base_cell:GND2D3BWP7T .dont_touch true}
catch {set_db base_cell:GND3D1BWP7T .dont_touch true}
catch {set_db base_cell:GND3D2BWP7T .dont_touch true}
catch {set_db base_cell:GNR2D1BWP7T .dont_touch true}
catch {set_db base_cell:GNR2D2BWP7T .dont_touch true}
catch {set_db base_cell:GNR3D1BWP7T .dont_touch true}
catch {set_db base_cell:GNR3D2BWP7T .dont_touch true}
catch {set_db base_cell:GOAI21D1BWP7T .dont_touch true}
catch {set_db base_cell:GOAI21D2BWP7T .dont_touch true}
catch {set_db base_cell:GOR2D1BWP7T .dont_touch true}
catch {set_db base_cell:GOR2D2BWP7T .dont_touch true}
catch {set_db base_cell:GSDFCNQD1BWP7T .dont_touch true}
catch {set_db base_cell:GTIEHBWP7T .dont_touch true}
catch {set_db base_cell:GTIELBWP7T .dont_touch true}
catch {set_db base_cell:GXNR2D1BWP7T .dont_touch true}
catch {set_db base_cell:GXNR2D2BWP7T .dont_touch true}
catch {set_db base_cell:GXOR2D1BWP7T .dont_touch true}
catch {set_db base_cell:GXOR2D2BWP7T .dont_touch true}
catch {set_db hinst:ber_checker_top/CLKGATE_RC_CG_HIER_INST0 .dont_touch_hports true}
catch {set_db hinst:ber_checker_top/CLKGATE_RC_CG_HIER_INST1 .dont_touch_hports true}
catch {set_db hinst:ber_checker_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/CLKGATE_RC_CG_HIER_INST2 .dont_touch_hports true}
catch {set_db hinst:ber_checker_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CLKGATE_RC_CG_HIER_INST3 .dont_touch_hports true}
