PROJECT_DIR := $(abspath .)
TOP_DIR := /w/home.09/home/liyuyao864/ee209/ee209-hammer-internal
OBJ_DIR := $(PROJECT_DIR)/build_ber_checker

# Avoid empty realpath in module_top.mk
BASEJUMP_STL_PATH := $(TOP_DIR)/misc-data

INPUT_CFGS := $(PROJECT_DIR)/cfg/ber_checker_top.yml
TB_CFGS := $(PROJECT_DIR)/cfg/ber_checker_tb.yml

include $(TOP_DIR)/module_top.mk