PROJECT_DIR := $(abspath .)
TOP_DIR := /w/home.09/home/liyuyao864/ee209/ee209-hammer-internal
OBJ_DIR := $(PROJECT_DIR)/build_prbs_gen

# Avoid empty realpath in module_top.mk
BASEJUMP_STL_PATH := $(TOP_DIR)/misc-data

INPUT_CFGS := $(PROJECT_DIR)/cfg/prbs_gen_top.yml
TB_CFGS := $(PROJECT_DIR)/cfg/prbs_gen_tb.yml

include $(TOP_DIR)/module_top.mk
