# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.19-s055_1 on Sat Apr 11 11:58:42 PDT 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design prbs_ber_top

create_clock -name "clk" -period 4.0 -waveform {0.0 2.0} [get_ports clk]
set_load -pin_load 0.005 [get_ports prbs_out]
set_load -pin_load 0.005 [get_ports checker_in]
set_load -pin_load 0.005 [get_ports checker_in_final]
set_load -pin_load 0.005 [get_ports ref_bit]
set_load -pin_load 0.005 [get_ports bit_error]
set_load -pin_load 0.005 [get_ports {error_count[31]}]
set_load -pin_load 0.005 [get_ports {error_count[30]}]
set_load -pin_load 0.005 [get_ports {error_count[29]}]
set_load -pin_load 0.005 [get_ports {error_count[28]}]
set_load -pin_load 0.005 [get_ports {error_count[27]}]
set_load -pin_load 0.005 [get_ports {error_count[26]}]
set_load -pin_load 0.005 [get_ports {error_count[25]}]
set_load -pin_load 0.005 [get_ports {error_count[24]}]
set_load -pin_load 0.005 [get_ports {error_count[23]}]
set_load -pin_load 0.005 [get_ports {error_count[22]}]
set_load -pin_load 0.005 [get_ports {error_count[21]}]
set_load -pin_load 0.005 [get_ports {error_count[20]}]
set_load -pin_load 0.005 [get_ports {error_count[19]}]
set_load -pin_load 0.005 [get_ports {error_count[18]}]
set_load -pin_load 0.005 [get_ports {error_count[17]}]
set_load -pin_load 0.005 [get_ports {error_count[16]}]
set_load -pin_load 0.005 [get_ports {error_count[15]}]
set_load -pin_load 0.005 [get_ports {error_count[14]}]
set_load -pin_load 0.005 [get_ports {error_count[13]}]
set_load -pin_load 0.005 [get_ports {error_count[12]}]
set_load -pin_load 0.005 [get_ports {error_count[11]}]
set_load -pin_load 0.005 [get_ports {error_count[10]}]
set_load -pin_load 0.005 [get_ports {error_count[9]}]
set_load -pin_load 0.005 [get_ports {error_count[8]}]
set_load -pin_load 0.005 [get_ports {error_count[7]}]
set_load -pin_load 0.005 [get_ports {error_count[6]}]
set_load -pin_load 0.005 [get_ports {error_count[5]}]
set_load -pin_load 0.005 [get_ports {error_count[4]}]
set_load -pin_load 0.005 [get_ports {error_count[3]}]
set_load -pin_load 0.005 [get_ports {error_count[2]}]
set_load -pin_load 0.005 [get_ports {error_count[1]}]
set_load -pin_load 0.005 [get_ports {error_count[0]}]
set_load -pin_load 0.005 [get_ports {total_count[31]}]
set_load -pin_load 0.005 [get_ports {total_count[30]}]
set_load -pin_load 0.005 [get_ports {total_count[29]}]
set_load -pin_load 0.005 [get_ports {total_count[28]}]
set_load -pin_load 0.005 [get_ports {total_count[27]}]
set_load -pin_load 0.005 [get_ports {total_count[26]}]
set_load -pin_load 0.005 [get_ports {total_count[25]}]
set_load -pin_load 0.005 [get_ports {total_count[24]}]
set_load -pin_load 0.005 [get_ports {total_count[23]}]
set_load -pin_load 0.005 [get_ports {total_count[22]}]
set_load -pin_load 0.005 [get_ports {total_count[21]}]
set_load -pin_load 0.005 [get_ports {total_count[20]}]
set_load -pin_load 0.005 [get_ports {total_count[19]}]
set_load -pin_load 0.005 [get_ports {total_count[18]}]
set_load -pin_load 0.005 [get_ports {total_count[17]}]
set_load -pin_load 0.005 [get_ports {total_count[16]}]
set_load -pin_load 0.005 [get_ports {total_count[15]}]
set_load -pin_load 0.005 [get_ports {total_count[14]}]
set_load -pin_load 0.005 [get_ports {total_count[13]}]
set_load -pin_load 0.005 [get_ports {total_count[12]}]
set_load -pin_load 0.005 [get_ports {total_count[11]}]
set_load -pin_load 0.005 [get_ports {total_count[10]}]
set_load -pin_load 0.005 [get_ports {total_count[9]}]
set_load -pin_load 0.005 [get_ports {total_count[8]}]
set_load -pin_load 0.005 [get_ports {total_count[7]}]
set_load -pin_load 0.005 [get_ports {total_count[6]}]
set_load -pin_load 0.005 [get_ports {total_count[5]}]
set_load -pin_load 0.005 [get_ports {total_count[4]}]
set_load -pin_load 0.005 [get_ports {total_count[3]}]
set_load -pin_load 0.005 [get_ports {total_count[2]}]
set_load -pin_load 0.005 [get_ports {total_count[1]}]
set_load -pin_load 0.005 [get_ports {total_count[0]}]
set_clock_groups -name "clock_groups_clk_to_others" -asynchronous -group [get_clocks clk]
set_clock_gating_check -setup 0.0 
