catch {set_db port:prbs_ber_top/clk .original_name clk}
catch {set_db port:prbs_ber_top/rst_n .original_name rst_n}
catch {set_db port:prbs_ber_top/en .original_name en}
catch {set_db port:prbs_ber_top/clear_count .original_name clear_count}
catch {set_db port:prbs_ber_top/seed_load .original_name seed_load}
catch {set_db port:prbs_ber_top/mode_select .original_name mode_select}
catch {set_db {port:prbs_ber_top/seed_in[14]} .original_name {seed_in[14]}}
catch {set_db {port:prbs_ber_top/seed_in[13]} .original_name {seed_in[13]}}
catch {set_db {port:prbs_ber_top/seed_in[12]} .original_name {seed_in[12]}}
catch {set_db {port:prbs_ber_top/seed_in[11]} .original_name {seed_in[11]}}
catch {set_db {port:prbs_ber_top/seed_in[10]} .original_name {seed_in[10]}}
catch {set_db {port:prbs_ber_top/seed_in[9]} .original_name {seed_in[9]}}
catch {set_db {port:prbs_ber_top/seed_in[8]} .original_name {seed_in[8]}}
catch {set_db {port:prbs_ber_top/seed_in[7]} .original_name {seed_in[7]}}
catch {set_db {port:prbs_ber_top/seed_in[6]} .original_name {seed_in[6]}}
catch {set_db {port:prbs_ber_top/seed_in[5]} .original_name {seed_in[5]}}
catch {set_db {port:prbs_ber_top/seed_in[4]} .original_name {seed_in[4]}}
catch {set_db {port:prbs_ber_top/seed_in[3]} .original_name {seed_in[3]}}
catch {set_db {port:prbs_ber_top/seed_in[2]} .original_name {seed_in[2]}}
catch {set_db {port:prbs_ber_top/seed_in[1]} .original_name {seed_in[1]}}
catch {set_db {port:prbs_ber_top/seed_in[0]} .original_name {seed_in[0]}}
catch {set_db port:prbs_ber_top/input_select .original_name input_select}
catch {set_db port:prbs_ber_top/inject_error_enable .original_name inject_error_enable}
catch {set_db port:prbs_ber_top/ext_serial_in .original_name ext_serial_in}
catch {set_db port:prbs_ber_top/prbs_out .original_name prbs_out}
catch {set_db port:prbs_ber_top/checker_in .original_name checker_in}
catch {set_db port:prbs_ber_top/checker_in_final .original_name checker_in_final}
catch {set_db port:prbs_ber_top/ref_bit .original_name ref_bit}
catch {set_db port:prbs_ber_top/bit_error .original_name bit_error}
catch {set_db {port:prbs_ber_top/error_count[31]} .original_name {error_count[31]}}
catch {set_db {port:prbs_ber_top/error_count[30]} .original_name {error_count[30]}}
catch {set_db {port:prbs_ber_top/error_count[29]} .original_name {error_count[29]}}
catch {set_db {port:prbs_ber_top/error_count[28]} .original_name {error_count[28]}}
catch {set_db {port:prbs_ber_top/error_count[27]} .original_name {error_count[27]}}
catch {set_db {port:prbs_ber_top/error_count[26]} .original_name {error_count[26]}}
catch {set_db {port:prbs_ber_top/error_count[25]} .original_name {error_count[25]}}
catch {set_db {port:prbs_ber_top/error_count[24]} .original_name {error_count[24]}}
catch {set_db {port:prbs_ber_top/error_count[23]} .original_name {error_count[23]}}
catch {set_db {port:prbs_ber_top/error_count[22]} .original_name {error_count[22]}}
catch {set_db {port:prbs_ber_top/error_count[21]} .original_name {error_count[21]}}
catch {set_db {port:prbs_ber_top/error_count[20]} .original_name {error_count[20]}}
catch {set_db {port:prbs_ber_top/error_count[19]} .original_name {error_count[19]}}
catch {set_db {port:prbs_ber_top/error_count[18]} .original_name {error_count[18]}}
catch {set_db {port:prbs_ber_top/error_count[17]} .original_name {error_count[17]}}
catch {set_db {port:prbs_ber_top/error_count[16]} .original_name {error_count[16]}}
catch {set_db {port:prbs_ber_top/error_count[15]} .original_name {error_count[15]}}
catch {set_db {port:prbs_ber_top/error_count[14]} .original_name {error_count[14]}}
catch {set_db {port:prbs_ber_top/error_count[13]} .original_name {error_count[13]}}
catch {set_db {port:prbs_ber_top/error_count[12]} .original_name {error_count[12]}}
catch {set_db {port:prbs_ber_top/error_count[11]} .original_name {error_count[11]}}
catch {set_db {port:prbs_ber_top/error_count[10]} .original_name {error_count[10]}}
catch {set_db {port:prbs_ber_top/error_count[9]} .original_name {error_count[9]}}
catch {set_db {port:prbs_ber_top/error_count[8]} .original_name {error_count[8]}}
catch {set_db {port:prbs_ber_top/error_count[7]} .original_name {error_count[7]}}
catch {set_db {port:prbs_ber_top/error_count[6]} .original_name {error_count[6]}}
catch {set_db {port:prbs_ber_top/error_count[5]} .original_name {error_count[5]}}
catch {set_db {port:prbs_ber_top/error_count[4]} .original_name {error_count[4]}}
catch {set_db {port:prbs_ber_top/error_count[3]} .original_name {error_count[3]}}
catch {set_db {port:prbs_ber_top/error_count[2]} .original_name {error_count[2]}}
catch {set_db {port:prbs_ber_top/error_count[1]} .original_name {error_count[1]}}
catch {set_db {port:prbs_ber_top/error_count[0]} .original_name {error_count[0]}}
catch {set_db {port:prbs_ber_top/total_count[31]} .original_name {total_count[31]}}
catch {set_db {port:prbs_ber_top/total_count[30]} .original_name {total_count[30]}}
catch {set_db {port:prbs_ber_top/total_count[29]} .original_name {total_count[29]}}
catch {set_db {port:prbs_ber_top/total_count[28]} .original_name {total_count[28]}}
catch {set_db {port:prbs_ber_top/total_count[27]} .original_name {total_count[27]}}
catch {set_db {port:prbs_ber_top/total_count[26]} .original_name {total_count[26]}}
catch {set_db {port:prbs_ber_top/total_count[25]} .original_name {total_count[25]}}
catch {set_db {port:prbs_ber_top/total_count[24]} .original_name {total_count[24]}}
catch {set_db {port:prbs_ber_top/total_count[23]} .original_name {total_count[23]}}
catch {set_db {port:prbs_ber_top/total_count[22]} .original_name {total_count[22]}}
catch {set_db {port:prbs_ber_top/total_count[21]} .original_name {total_count[21]}}
catch {set_db {port:prbs_ber_top/total_count[20]} .original_name {total_count[20]}}
catch {set_db {port:prbs_ber_top/total_count[19]} .original_name {total_count[19]}}
catch {set_db {port:prbs_ber_top/total_count[18]} .original_name {total_count[18]}}
catch {set_db {port:prbs_ber_top/total_count[17]} .original_name {total_count[17]}}
catch {set_db {port:prbs_ber_top/total_count[16]} .original_name {total_count[16]}}
catch {set_db {port:prbs_ber_top/total_count[15]} .original_name {total_count[15]}}
catch {set_db {port:prbs_ber_top/total_count[14]} .original_name {total_count[14]}}
catch {set_db {port:prbs_ber_top/total_count[13]} .original_name {total_count[13]}}
catch {set_db {port:prbs_ber_top/total_count[12]} .original_name {total_count[12]}}
catch {set_db {port:prbs_ber_top/total_count[11]} .original_name {total_count[11]}}
catch {set_db {port:prbs_ber_top/total_count[10]} .original_name {total_count[10]}}
catch {set_db {port:prbs_ber_top/total_count[9]} .original_name {total_count[9]}}
catch {set_db {port:prbs_ber_top/total_count[8]} .original_name {total_count[8]}}
catch {set_db {port:prbs_ber_top/total_count[7]} .original_name {total_count[7]}}
catch {set_db {port:prbs_ber_top/total_count[6]} .original_name {total_count[6]}}
catch {set_db {port:prbs_ber_top/total_count[5]} .original_name {total_count[5]}}
catch {set_db {port:prbs_ber_top/total_count[4]} .original_name {total_count[4]}}
catch {set_db {port:prbs_ber_top/total_count[3]} .original_name {total_count[3]}}
catch {set_db {port:prbs_ber_top/total_count[2]} .original_name {total_count[2]}}
catch {set_db {port:prbs_ber_top/total_count[1]} .original_name {total_count[1]}}
catch {set_db {port:prbs_ber_top/total_count[0]} .original_name {total_count[0]}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[4]/Q} .original_name {u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[4]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[3]/Q} .original_name {u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[3]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[2]/Q} .original_name {u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[2]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[1]/Q} .original_name {u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[1]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[0]/Q} .original_name {u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[0]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[0]/QN} .original_name {u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[0]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[5]/Q} .original_name {u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[5]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[6]/Q} .original_name {u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[6]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[12]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[12]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[11]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[11]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[10]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[10]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[9]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[9]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[8]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[8]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[7]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[7]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[6]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[6]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[5]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[5]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[4]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[4]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[3]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[3]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[2]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[2]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[1]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[1]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[0]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[0]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[0]/QN} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[0]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[13]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[13]/q}}
catch {set_db {pin:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[14]/Q} .original_name {u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[14]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[0]/Q} .original_name {error_count[0]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[1]/Q} .original_name {error_count[1]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[2]/Q} .original_name {error_count[2]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[3]/Q} .original_name {error_count[3]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[4]/Q} .original_name {error_count[4]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[5]/Q} .original_name {error_count[5]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[6]/Q} .original_name {error_count[6]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[7]/Q} .original_name {error_count[7]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[8]/Q} .original_name {error_count[8]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[9]/Q} .original_name {error_count[9]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[10]/Q} .original_name {error_count[10]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[11]/Q} .original_name {error_count[11]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[12]/Q} .original_name {error_count[12]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[13]/Q} .original_name {error_count[13]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[14]/Q} .original_name {error_count[14]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[15]/Q} .original_name {error_count[15]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[16]/Q} .original_name {error_count[16]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[17]/Q} .original_name {error_count[17]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[18]/Q} .original_name {error_count[18]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[19]/Q} .original_name {error_count[19]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[20]/Q} .original_name {error_count[20]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[21]/Q} .original_name {error_count[21]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[22]/Q} .original_name {error_count[22]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[23]/Q} .original_name {error_count[23]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[24]/Q} .original_name {error_count[24]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[25]/Q} .original_name {error_count[25]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[26]/Q} .original_name {error_count[26]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[27]/Q} .original_name {error_count[27]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[28]/Q} .original_name {error_count[28]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[29]/Q} .original_name {error_count[29]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[30]/Q} .original_name {error_count[30]/q}}
catch {set_db {pin:prbs_ber_top/error_count_reg[31]/Q} .original_name {error_count[31]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[0]/Q} .original_name {total_count[0]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[1]/Q} .original_name {total_count[1]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[2]/Q} .original_name {total_count[2]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[3]/Q} .original_name {total_count[3]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[4]/Q} .original_name {total_count[4]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[5]/Q} .original_name {total_count[5]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[6]/Q} .original_name {total_count[6]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[7]/Q} .original_name {total_count[7]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[8]/Q} .original_name {total_count[8]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[9]/Q} .original_name {total_count[9]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[10]/Q} .original_name {total_count[10]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[11]/Q} .original_name {total_count[11]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[12]/Q} .original_name {total_count[12]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[13]/Q} .original_name {total_count[13]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[14]/Q} .original_name {total_count[14]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[15]/Q} .original_name {total_count[15]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[16]/Q} .original_name {total_count[16]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[17]/Q} .original_name {total_count[17]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[18]/Q} .original_name {total_count[18]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[19]/Q} .original_name {total_count[19]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[20]/Q} .original_name {total_count[20]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[21]/Q} .original_name {total_count[21]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[22]/Q} .original_name {total_count[22]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[23]/Q} .original_name {total_count[23]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[24]/Q} .original_name {total_count[24]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[25]/Q} .original_name {total_count[25]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[26]/Q} .original_name {total_count[26]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[27]/Q} .original_name {total_count[27]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[28]/Q} .original_name {total_count[28]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[29]/Q} .original_name {total_count[29]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[30]/Q} .original_name {total_count[30]/q}}
catch {set_db {pin:prbs_ber_top/total_count_reg[31]/Q} .original_name {total_count[31]/q}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[4]} .original_name {{u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[4]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[3]} .original_name {{u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[3]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[2]} .original_name {{u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[2]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[1]} .original_name {{u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[1]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[0]} .original_name {{u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[0]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[5]} .original_name {{u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[5]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[6]} .original_name {{u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[6]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[12]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[12]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[11]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[11]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[10]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[10]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[9]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[9]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[8]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[8]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[7]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[7]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[6]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[6]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[5]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[5]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[4]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[4]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[3]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[3]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[2]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[2]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[1]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[1]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[0]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[0]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[13]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[13]}}}
catch {set_db {inst:prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[14]} .original_name {{u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[14]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[0]} .original_name {{error_count[0]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[1]} .original_name {{error_count[1]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[2]} .original_name {{error_count[2]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[3]} .original_name {{error_count[3]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[4]} .original_name {{error_count[4]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[5]} .original_name {{error_count[5]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[6]} .original_name {{error_count[6]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[7]} .original_name {{error_count[7]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[8]} .original_name {{error_count[8]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[9]} .original_name {{error_count[9]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[10]} .original_name {{error_count[10]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[11]} .original_name {{error_count[11]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[12]} .original_name {{error_count[12]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[13]} .original_name {{error_count[13]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[14]} .original_name {{error_count[14]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[15]} .original_name {{error_count[15]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[16]} .original_name {{error_count[16]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[17]} .original_name {{error_count[17]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[18]} .original_name {{error_count[18]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[19]} .original_name {{error_count[19]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[20]} .original_name {{error_count[20]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[21]} .original_name {{error_count[21]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[22]} .original_name {{error_count[22]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[23]} .original_name {{error_count[23]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[24]} .original_name {{error_count[24]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[25]} .original_name {{error_count[25]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[26]} .original_name {{error_count[26]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[27]} .original_name {{error_count[27]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[28]} .original_name {{error_count[28]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[29]} .original_name {{error_count[29]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[30]} .original_name {{error_count[30]}}}
catch {set_db {inst:prbs_ber_top/error_count_reg[31]} .original_name {{error_count[31]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[0]} .original_name {{total_count[0]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[1]} .original_name {{total_count[1]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[2]} .original_name {{total_count[2]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[3]} .original_name {{total_count[3]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[4]} .original_name {{total_count[4]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[5]} .original_name {{total_count[5]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[6]} .original_name {{total_count[6]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[7]} .original_name {{total_count[7]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[8]} .original_name {{total_count[8]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[9]} .original_name {{total_count[9]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[10]} .original_name {{total_count[10]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[11]} .original_name {{total_count[11]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[12]} .original_name {{total_count[12]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[13]} .original_name {{total_count[13]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[14]} .original_name {{total_count[14]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[15]} .original_name {{total_count[15]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[16]} .original_name {{total_count[16]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[17]} .original_name {{total_count[17]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[18]} .original_name {{total_count[18]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[19]} .original_name {{total_count[19]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[20]} .original_name {{total_count[20]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[21]} .original_name {{total_count[21]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[22]} .original_name {{total_count[22]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[23]} .original_name {{total_count[23]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[24]} .original_name {{total_count[24]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[25]} .original_name {{total_count[25]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[26]} .original_name {{total_count[26]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[27]} .original_name {{total_count[27]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[28]} .original_name {{total_count[28]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[29]} .original_name {{total_count[29]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[30]} .original_name {{total_count[30]}}}
catch {set_db {inst:prbs_ber_top/total_count_reg[31]} .original_name {{total_count[31]}}}
