
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point ext_serial_in ext_serial_in -type PI PI
add mapped point cfg_sclk cfg_sclk -type PI PI
add mapped point cfg_cs_n cfg_cs_n -type PI PI
add mapped point cfg_mosi cfg_mosi -type PI PI

//output ports
add mapped point cfg_miso cfg_miso -type PO PO
add mapped point busy busy -type PO PO
add mapped point done done -type PO PO
add mapped point prbs_out prbs_out -type PO PO
add mapped point bit_error bit_error -type PO PO

//inout ports




//Sequential Pins
add mapped point u_cfg_serial_if/cfg_cs_n_meta/q u_cfg_serial_if/cfg_cs_n_meta_reg/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_cs_n_sync_d/q u_cfg_serial_if/cfg_cs_n_sync_d_reg/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_mosi_meta/q u_cfg_serial_if/cfg_mosi_meta_reg/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_mosi_sync/q u_cfg_serial_if/cfg_mosi_sync_reg/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_sclk_meta/q u_cfg_serial_if/cfg_sclk_meta_reg/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_sclk_sync_d/q u_cfg_serial_if/cfg_sclk_sync_d_reg/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_sclk_sync/q u_cfg_serial_if/cfg_sclk_sync_reg/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[0]/q u_cfg_serial_if/cmd_shift_q_reg[0]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[1]/q u_cfg_serial_if/cmd_shift_q_reg[1]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[2]/q u_cfg_serial_if/cmd_shift_q_reg[2]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[3]/q u_cfg_serial_if/cmd_shift_q_reg[3]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[4]/q u_cfg_serial_if/cmd_shift_q_reg[4]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[5]/q u_cfg_serial_if/cmd_shift_q_reg[5]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[6]/q u_cfg_serial_if/cmd_shift_q_reg[6]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[7]/q u_cfg_serial_if/cmd_shift_q_reg[7]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[8]/q u_cfg_serial_if/cmd_shift_q_reg[8]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[9]/q u_cfg_serial_if/cmd_shift_q_reg[9]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[10]/q u_cfg_serial_if/cmd_shift_q_reg[10]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[11]/q u_cfg_serial_if/cmd_shift_q_reg[11]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[12]/q u_cfg_serial_if/cmd_shift_q_reg[12]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[13]/q u_cfg_serial_if/cmd_shift_q_reg[13]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[14]/q u_cfg_serial_if/cmd_shift_q_reg[14]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[15]/q u_cfg_serial_if/cmd_shift_q_reg[15]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[16]/q u_cfg_serial_if/cmd_shift_q_reg[16]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[17]/q u_cfg_serial_if/cmd_shift_q_reg[17]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[18]/q u_cfg_serial_if/cmd_shift_q_reg[18]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[19]/q u_cfg_serial_if/cmd_shift_q_reg[19]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[20]/q u_cfg_serial_if/cmd_shift_q_reg[20]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[21]/q u_cfg_serial_if/cmd_shift_q_reg[21]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[22]/q u_cfg_serial_if/cmd_shift_q_reg[22]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[23]/q u_cfg_serial_if/cmd_shift_q_reg[23]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[24]/q u_cfg_serial_if/cmd_shift_q_reg[24]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[25]/q u_cfg_serial_if/cmd_shift_q_reg[25]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[26]/q u_cfg_serial_if/cmd_shift_q_reg[26]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[27]/q u_cfg_serial_if/cmd_shift_q_reg[27]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[28]/q u_cfg_serial_if/cmd_shift_q_reg[28]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[29]/q u_cfg_serial_if/cmd_shift_q_reg[29]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[30]/q u_cfg_serial_if/cmd_shift_q_reg[30]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[31]/q u_cfg_serial_if/cmd_shift_q_reg[31]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[34]/q u_cfg_serial_if/cmd_shift_q_reg[34]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[35]/q u_cfg_serial_if/cmd_shift_q_reg[35]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[36]/q u_cfg_serial_if/cmd_shift_q_reg[36]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[0]/q u_cfg_serial_if/rd_shift_q_reg[0]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[1]/q u_cfg_serial_if/rd_shift_q_reg[1]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[2]/q u_cfg_serial_if/rd_shift_q_reg[2]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[3]/q u_cfg_serial_if/rd_shift_q_reg[3]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[4]/q u_cfg_serial_if/rd_shift_q_reg[4]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[5]/q u_cfg_serial_if/rd_shift_q_reg[5]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[6]/q u_cfg_serial_if/rd_shift_q_reg[6]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[7]/q u_cfg_serial_if/rd_shift_q_reg[7]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[8]/q u_cfg_serial_if/rd_shift_q_reg[8]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[9]/q u_cfg_serial_if/rd_shift_q_reg[9]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[10]/q u_cfg_serial_if/rd_shift_q_reg[10]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[11]/q u_cfg_serial_if/rd_shift_q_reg[11]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[12]/q u_cfg_serial_if/rd_shift_q_reg[12]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[13]/q u_cfg_serial_if/rd_shift_q_reg[13]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[14]/q u_cfg_serial_if/rd_shift_q_reg[14]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[15]/q u_cfg_serial_if/rd_shift_q_reg[15]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[16]/q u_cfg_serial_if/rd_shift_q_reg[16]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[17]/q u_cfg_serial_if/rd_shift_q_reg[17]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[18]/q u_cfg_serial_if/rd_shift_q_reg[18]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[19]/q u_cfg_serial_if/rd_shift_q_reg[19]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[20]/q u_cfg_serial_if/rd_shift_q_reg[20]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[21]/q u_cfg_serial_if/rd_shift_q_reg[21]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[22]/q u_cfg_serial_if/rd_shift_q_reg[22]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[23]/q u_cfg_serial_if/rd_shift_q_reg[23]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[24]/q u_cfg_serial_if/rd_shift_q_reg[24]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[25]/q u_cfg_serial_if/rd_shift_q_reg[25]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[26]/q u_cfg_serial_if/rd_shift_q_reg[26]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[27]/q u_cfg_serial_if/rd_shift_q_reg[27]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[28]/q u_cfg_serial_if/rd_shift_q_reg[28]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[29]/q u_cfg_serial_if/rd_shift_q_reg[29]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[30]/q u_cfg_serial_if/rd_shift_q_reg[30]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rd_shift_q[31]/q u_cfg_serial_if/rd_shift_q_reg[31]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rx_bit_cnt_q[5]/q u_cfg_serial_if/rx_bit_cnt_q_reg[5]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rx_bit_cnt_q[4]/q u_cfg_serial_if/rx_bit_cnt_q_reg[4]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rx_bit_cnt_q[3]/q u_cfg_serial_if/rx_bit_cnt_q_reg[3]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rx_bit_cnt_q[1]/q u_cfg_serial_if/rx_bit_cnt_q_reg[1]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rx_bit_cnt_q[2]/q u_cfg_serial_if/rx_bit_cnt_q_reg[2]/Q -type DFF DFF
add mapped point u_cfg_serial_if/state_q[1]/q u_cfg_serial_if/state_q_reg[1]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[33]/q u_cfg_serial_if/cmd_shift_q_reg[33]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[38]/q u_cfg_serial_if/cmd_shift_q_reg[38]/Q -type DFF DFF
add mapped point u_cfg_serial_if/rx_bit_cnt_q[0]/q u_cfg_serial_if/rx_bit_cnt_q_reg[0]/Q -type DFF DFF
add mapped point u_cfg_serial_if/state_q[2]/q u_cfg_serial_if/state_q_reg[2]/Q -type DFF DFF
add mapped point u_cfg_serial_if/state_q[0]/q u_cfg_serial_if/state_q_reg[0]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_we/q u_cfg_serial_if/cfg_we_reg/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_re/q u_cfg_serial_if/cfg_re_reg/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[32]/q u_cfg_serial_if/cmd_shift_q_reg[32]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cmd_shift_q[37]/q u_cfg_serial_if/cmd_shift_q_reg[37]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_cs_n_sync/q u_cfg_serial_if/cfg_cs_n_sync_reg/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_addr[1]/q u_cfg_serial_if/cfg_addr_reg[1]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[31]/q u_cfg_serial_if/cfg_wdata_reg[31]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[29]/q u_cfg_serial_if/cfg_wdata_reg[29]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[30]/q u_cfg_serial_if/cfg_wdata_reg[30]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_addr[2]/q u_cfg_serial_if/cfg_addr_reg[2]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[28]/q u_cfg_serial_if/cfg_wdata_reg[28]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_addr[3]/q u_cfg_serial_if/cfg_addr_reg[3]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_addr[4]/q u_cfg_serial_if/cfg_addr_reg[4]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_addr[0]/q u_cfg_serial_if/cfg_addr_reg[0]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[24]/q u_cfg_serial_if/cfg_wdata_reg[24]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[0]/q u_cfg_serial_if/cfg_wdata_reg[0]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[1]/q u_cfg_serial_if/cfg_wdata_reg[1]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[2]/q u_cfg_serial_if/cfg_wdata_reg[2]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[20]/q u_cfg_serial_if/cfg_wdata_reg[20]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[3]/q u_cfg_serial_if/cfg_wdata_reg[3]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[4]/q u_cfg_serial_if/cfg_wdata_reg[4]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[5]/q u_cfg_serial_if/cfg_wdata_reg[5]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[6]/q u_cfg_serial_if/cfg_wdata_reg[6]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[7]/q u_cfg_serial_if/cfg_wdata_reg[7]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[9]/q u_cfg_serial_if/cfg_wdata_reg[9]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[10]/q u_cfg_serial_if/cfg_wdata_reg[10]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[11]/q u_cfg_serial_if/cfg_wdata_reg[11]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[12]/q u_cfg_serial_if/cfg_wdata_reg[12]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[13]/q u_cfg_serial_if/cfg_wdata_reg[13]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[14]/q u_cfg_serial_if/cfg_wdata_reg[14]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[15]/q u_cfg_serial_if/cfg_wdata_reg[15]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[16]/q u_cfg_serial_if/cfg_wdata_reg[16]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[17]/q u_cfg_serial_if/cfg_wdata_reg[17]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[18]/q u_cfg_serial_if/cfg_wdata_reg[18]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[19]/q u_cfg_serial_if/cfg_wdata_reg[19]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[21]/q u_cfg_serial_if/cfg_wdata_reg[21]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[22]/q u_cfg_serial_if/cfg_wdata_reg[22]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[23]/q u_cfg_serial_if/cfg_wdata_reg[23]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[25]/q u_cfg_serial_if/cfg_wdata_reg[25]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[26]/q u_cfg_serial_if/cfg_wdata_reg[26]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[27]/q u_cfg_serial_if/cfg_wdata_reg[27]/Q -type DFF DFF
add mapped point u_cfg_serial_if/cfg_wdata[8]/q u_cfg_serial_if/cfg_wdata_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[5]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[6]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[7]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[8]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[9]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[10]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[11]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[12]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[13]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[14]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[15]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[15]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[16]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[16]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[17]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[17]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[18]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[18]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[19]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[19]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[20]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[20]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[21]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[21]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[22]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[22]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[23]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[23]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[24]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[24]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[25]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[25]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[26]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[26]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[27]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[27]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[28]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[28]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[29]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[29]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[30]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[30]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[31]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[31]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/done_d/q u_prbs_ber_chip_top/u_csr_regbank/done_d_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[0]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[1]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[2]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[3]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[4]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[5]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[6]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[7]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[8]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[9]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[10]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[11]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[12]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[13]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[14]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[15]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[15]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[16]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[16]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[17]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[17]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[18]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[18]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[19]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[19]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[20]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[20]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[21]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[21]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[22]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[22]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[23]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[23]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[24]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[24]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[25]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[25]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[26]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[26]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[27]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[27]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[28]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[28]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[29]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[29]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[30]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[30]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg[31]/q u_prbs_ber_chip_top/u_csr_regbank/first_error_index_reg_reg[31]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[0]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[1]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[2]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[3]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[4]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[5]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[6]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[7]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[8]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[9]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[10]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[11]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[12]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[13]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[14]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[15]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[15]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[16]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[16]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[17]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[17]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[18]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[18]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[19]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[19]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[20]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[20]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[21]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[21]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[22]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[22]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[23]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[23]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[24]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[24]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[25]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[25]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[26]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[26]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[27]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[27]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[28]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[28]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[29]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[29]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[30]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[30]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg[31]/q u_prbs_ber_chip_top/u_csr_regbank/last_errcnt_reg_reg[31]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_status_reg[0]/q u_prbs_ber_chip_top/u_csr_regbank/last_status_reg_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_status_reg[1]/q u_prbs_ber_chip_top/u_csr_regbank/last_status_reg_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_status_reg[2]/q u_prbs_ber_chip_top/u_csr_regbank/last_status_reg_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_status_reg[3]/q u_prbs_ber_chip_top/u_csr_regbank/last_status_reg_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_status_reg[4]/q u_prbs_ber_chip_top/u_csr_regbank/last_status_reg_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_status_reg[5]/q u_prbs_ber_chip_top/u_csr_regbank/last_status_reg_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_status_reg[6]/q u_prbs_ber_chip_top/u_csr_regbank/last_status_reg_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_status_reg[7]/q u_prbs_ber_chip_top/u_csr_regbank/last_status_reg_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[0]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[1]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[2]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[3]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[4]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[5]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[6]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[7]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[8]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[9]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[10]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[11]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[12]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[13]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[14]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[15]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[15]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[16]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[16]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[17]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[17]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[18]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[18]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[19]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[19]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[20]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[20]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[21]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[21]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[22]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[22]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[23]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[23]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[24]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[24]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[25]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[25]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[26]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[26]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[27]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[27]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[28]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[28]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[29]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[29]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[30]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[30]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg[31]/q u_prbs_ber_chip_top/u_csr_regbank/last_totcnt_reg_reg[31]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[15]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[15]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[16]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[16]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[17]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[17]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[18]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[18]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[19]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[19]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[20]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[20]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[21]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[21]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[22]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[22]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[23]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[23]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[24]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[24]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[25]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[25]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[26]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[26]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[27]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[27]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[28]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[28]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[29]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[29]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[30]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[30]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[31]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[31]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg[0]/q u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg[1]/q u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg[2]/q u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg[4]/q u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg[5]/q u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg[6]/q u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg[7]/q u_prbs_ber_chip_top/u_csr_regbank/snapshot0_reg_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[0]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[1]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[2]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[3]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[4]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[5]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[6]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[7]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[8]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[9]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[10]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[11]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[12]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[13]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[14]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[15]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[15]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[16]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[16]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[17]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[17]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[18]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[18]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[19]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[19]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[20]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[20]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[21]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[21]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[22]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[22]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[23]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[23]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[24]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[24]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[25]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[25]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[26]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[26]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[27]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[27]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[28]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[28]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[29]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[29]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[30]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[30]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg[31]/q u_prbs_ber_chip_top/u_csr_regbank/fail_count_reg_reg[31]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/first_error_seen_reg/q u_prbs_ber_chip_top/u_csr_regbank/first_error_seen_reg_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[0]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[1]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[2]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[3]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[4]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[5]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[6]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[7]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[8]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[9]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[10]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[11]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[12]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[13]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[14]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[15]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[15]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[16]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[16]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[17]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[17]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[18]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[18]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[19]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[19]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[20]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[20]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[21]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[21]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[22]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[22]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[23]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[23]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[24]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[24]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[25]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[25]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[26]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[26]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[27]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[27]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[28]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[28]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[29]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[29]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[30]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[30]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg[31]/q u_prbs_ber_chip_top/u_csr_regbank/pass_count_reg_reg[31]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[0]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[1]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[2]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[3]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[4]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[5]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[6]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[7]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[8]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[9]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[10]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[11]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[12]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[13]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[14]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[15]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[15]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[16]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[16]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[17]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[17]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[18]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[18]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[19]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[19]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[20]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[20]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[21]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[21]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[22]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[22]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[23]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[23]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[24]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[24]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[25]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[25]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[26]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[26]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[27]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[27]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[28]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[28]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[29]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[29]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[30]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[30]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/run_count_reg[31]/q u_prbs_ber_chip_top/u_csr_regbank/run_count_reg_reg[31]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/sticky_done_reg/q u_prbs_ber_chip_top/u_csr_regbank/sticky_done_reg_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/sticky_error_seen_reg/q u_prbs_ber_chip_top/u_csr_regbank/sticky_error_seen_reg_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/sticky_overflow_reg/q u_prbs_ber_chip_top/u_csr_regbank/sticky_overflow_reg_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_load_pulse/q u_prbs_ber_chip_top/u_csr_regbank/seed_load_pulse_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/stop_pulse/q u_prbs_ber_chip_top/u_csr_regbank/stop_pulse_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/start_pulse/q u_prbs_ber_chip_top/u_csr_regbank/start_pulse_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/manual_clear_pulse/q u_prbs_ber_chip_top/u_csr_regbank/manual_clear_pulse_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[2]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[4]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[0]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[9]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[10]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[11]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[12]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[13]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[14]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[8]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[0]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[1]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[3]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[7]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[5]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[6]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[7]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[8]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[9]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[10]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[11]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[12]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[13]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[14]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[15]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[15]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[16]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[16]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[17]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[17]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[18]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[18]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[19]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[19]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[20]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[20]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[21]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[21]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[1]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[22]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[22]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[23]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[23]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[24]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[24]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[25]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[25]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[26]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[26]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[27]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[27]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[28]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[28]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[29]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[29]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[2]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[4]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[30]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[30]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/window_reg[31]/q u_prbs_ber_chip_top/u_csr_regbank/window_reg_reg[31]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[3]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg[0]/q u_prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[1]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[2]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[3]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[4]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[5]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_csr_regbank/seed_reg[6]/q u_prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_measure_ctrl/clear_count_pulse/q u_prbs_ber_chip_top/u_measure_ctrl/clear_count_pulse_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_measure_ctrl/busy_q/q u_prbs_ber_chip_top/u_measure_ctrl/busy_q_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_measure_ctrl/done_q/q u_prbs_ber_chip_top/u_measure_ctrl/done_q_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_measure_ctrl/overflow_q/q u_prbs_ber_chip_top/u_measure_ctrl/overflow_q_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_measure_ctrl/skip_window_check_q/q u_prbs_ber_chip_top/u_measure_ctrl/skip_window_check_q_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[4]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[3]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[2]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[1]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[0]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[5]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[6]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[12]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[11]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[10]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[9]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[8]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[7]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[6]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[5]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[4]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[3]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[2]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[1]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[0]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[13]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[14]/q u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/ref_bit_q/q u_prbs_ber_chip_top/u_prbs_ber_top/ref_bit_q_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/ext_serial_in_q/q u_prbs_ber_chip_top/u_prbs_ber_top/ext_serial_in_q_reg/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[0]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[1]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[2]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[3]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[4]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[5]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[6]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[7]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[8]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[9]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[10]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[11]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[12]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[13]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[14]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[15]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[15]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[16]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[16]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[17]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[17]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[18]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[18]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[19]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[19]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[20]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[20]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[21]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[21]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[22]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[22]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[23]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[23]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[24]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[24]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[25]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[25]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[26]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[26]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[27]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[27]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[28]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[28]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[29]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[29]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[30]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[30]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/error_count[31]/q u_prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[31]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[0]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[1]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[2]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[3]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[4]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[5]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[6]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[7]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[8]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[9]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[10]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[11]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[12]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[13]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[14]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[15]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[15]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[16]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[16]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[17]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[17]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[18]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[18]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[19]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[19]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[20]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[20]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[21]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[21]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[22]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[22]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[23]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[23]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[24]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[24]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[25]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[25]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[26]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[26]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[27]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[27]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[28]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[28]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[29]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[29]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[30]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[30]/Q -type DFF DFF
add mapped point u_prbs_ber_chip_top/u_prbs_ber_top/total_count[31]/q u_prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[31]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
