#==============================================================================
# Hierarchical dofile generated by Conformal LEC
# Version: 24.10-p100 (30-May-2024) (64 bit executable)
#------------------------------------------------------------------------------
# Hierarchical dofile is generated by following configuration:
# write_hier_compare_dofile
#     -NOExact_pin_match
#     -Constraints
#     -INPUT_OUTPUT_Pin_equivalence
#     -BALANCED_EXTractions
#     -PREPEND_String 'report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -verbose'
#     -Usage
#     -Replace
#     -VERbose
#     'hier_compare.tcl'
#------------------------------------------------------------------------------
# For additional reporting on 'not written' modules, see the 'VERBOSE REPORTING'
# section at the end of the hierarchical dofile
#------------------------------------------------------------------------------
# The command 'set module property' sets the instance context for the current
# root module. It is intended only for hierarchical comparison, and should
# not be modified by the user.
#------------------------------------------------------------------------------
# TERMS AND NOTATIONS USED
#------------------------------------------------------------------------------
# Module Instantiation Ratio: Average number of instantiations per matching module
# Wrapper size: Logic gates enclosing the module's instance, and bounded by key-points
# Periphery size: Logic gates in the fanin and fanout cone of instance's input and output boundary, and bounded by key-points
# 0: Indicates pin is constant zero
# 1: Indicates pin is constant one
# X: Indicates pin is full DC
# U: Indicates pin is unreachable
# Z: Indicates pin is floating
# KP<--: Indicates pin's fanin is directly connected to key-point (ignores buffers/inverters)
# -->KP: Indicates pin's fanout is directly connected to key-point (ignores buffers/inverters)
# REP: Indicates pin is representative pin
# EQ_REP: <polarity> rep_pinname>: Indicates pin is a member EQ pin with
# 'rep_pinname' specifying the representative, and 'polarity' specifying
# if it is positive or negative equivalent
# = : Indicates that the pins on LHS and RHS are mapped
# + : Indicates positive polarity for pin mapping
# - : Indicates negative polarity for pin mapping
# ? : Indicates unknown polarity for pin mapping
# G: Indicates that the pin belongs to Golden
# R: Indicates that the pin belongs to Revised
# IN: Indicates that the pin is an Input pin
# OUT: Indicates that the pin is an Output pin
# IO: Indicates that the pin is an Inout pin. Polarity of Inout pin is
#     always '?' because of name-only mapping
#==============================================================================

set_system_mode setup
# Comparing
#-------------------------------------------------------------------------------
# MODULE cfg_serial_if (G) INSTANCE /u_cfg_serial_if (G)
# MODULE cfg_serial_if_mapped (R) INSTANCE /u_cfg_serial_if (R)
# Wrapper size: (G) = 2399  (R) = 1851
# Periphery size: (G) = 2466  (R) = 1949
# Pins directly connected to key-points/constants: (G) = 58.44%  (R) = 58.44%
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk  (KP<--)(REP)  =   (R) clk  (KP<--)(REP) (by sim and name)
# IN (G) rst_n  (KP<--)(REP)  =   (R) rst_n  (KP<--)(REP) (by sim and name)
# IN (G) cfg_sclk  (KP<--)(REP)  =   (R) cfg_sclk  (KP<--)(REP) (by sim and name)
# IN (G) cfg_cs_n  (KP<--)(REP)  =   (R) cfg_cs_n  (KP<--)(REP) (by sim and name)
# IN (G) cfg_mosi  (KP<--)(REP)  =   (R) cfg_mosi  (KP<--)(REP) (by sim and name)
# IN (G) cfg_rdata[31] (REP)  =   (R) cfg_rdata[31] (REP) (by sim and name)
# IN (G) cfg_rdata[30] (REP)  =   (R) cfg_rdata[30] (REP) (by sim and name)
# IN (G) cfg_rdata[29] (REP)  =   (R) cfg_rdata[29] (REP) (by sim and name)
# IN (G) cfg_rdata[28] (REP)  =   (R) cfg_rdata[28] (REP) (by sim and name)
# IN (G) cfg_rdata[27] (REP)  =   (R) cfg_rdata[27] (REP) (by sim and name)
# IN (G) cfg_rdata[26] (REP)  =   (R) cfg_rdata[26] (REP) (by sim and name)
# IN (G) cfg_rdata[25] (REP)  =   (R) cfg_rdata[25] (REP) (by sim and name)
# IN (G) cfg_rdata[24] (REP)  =   (R) cfg_rdata[24] (REP) (by sim and name)
# IN (G) cfg_rdata[23] (REP)  =   (R) cfg_rdata[23] (REP) (by sim and name)
# IN (G) cfg_rdata[22] (REP)  =   (R) cfg_rdata[22] (REP) (by sim and name)
# IN (G) cfg_rdata[21] (REP)  =   (R) cfg_rdata[21] (REP) (by sim and name)
# IN (G) cfg_rdata[20] (REP)  =   (R) cfg_rdata[20] (REP) (by sim and name)
# IN (G) cfg_rdata[19] (REP)  =   (R) cfg_rdata[19] (REP) (by sim and name)
# IN (G) cfg_rdata[18] (REP)  =   (R) cfg_rdata[18] (REP) (by sim and name)
# IN (G) cfg_rdata[17] (REP)  =   (R) cfg_rdata[17] (REP) (by sim and name)
# IN (G) cfg_rdata[16] (REP)  =   (R) cfg_rdata[16] (REP) (by sim and name)
# IN (G) cfg_rdata[15] (REP)  =   (R) cfg_rdata[15] (REP) (by sim and name)
# IN (G) cfg_rdata[14] (REP)  =   (R) cfg_rdata[14] (REP) (by sim and name)
# IN (G) cfg_rdata[13] (REP)  =   (R) cfg_rdata[13] (REP) (by sim and name)
# IN (G) cfg_rdata[12] (REP)  =   (R) cfg_rdata[12] (REP) (by sim and name)
# IN (G) cfg_rdata[11] (REP)  =   (R) cfg_rdata[11] (REP) (by sim and name)
# IN (G) cfg_rdata[10] (REP)  =   (R) cfg_rdata[10] (REP) (by sim and name)
# IN (G) cfg_rdata[9] (REP)  =   (R) cfg_rdata[9] (REP) (by sim and name)
# IN (G) cfg_rdata[8] (REP)  =   (R) cfg_rdata[8] (REP) (by sim and name)
# IN (G) cfg_rdata[7] (REP)  =   (R) cfg_rdata[7] (REP) (by sim and name)
# IN (G) cfg_rdata[6] (REP)  =   (R) cfg_rdata[6] (REP) (by sim and name)
# IN (G) cfg_rdata[5] (REP)  =   (R) cfg_rdata[5] (REP) (by sim and name)
# IN (G) cfg_rdata[4] (REP)  =   (R) cfg_rdata[4] (REP) (by sim and name)
# IN (G) cfg_rdata[3] (REP)  =   (R) cfg_rdata[3] (REP) (by sim and name)
# IN (G) cfg_rdata[2] (REP)  =   (R) cfg_rdata[2] (REP) (by sim and name)
# IN (G) cfg_rdata[1] (REP)  =   (R) cfg_rdata[1] (REP) (by sim and name)
# IN (G) cfg_rdata[0] (REP)  =   (R) cfg_rdata[0] (REP) (by sim and name)
# RESOLVED Constraints
# OUT (G) cfg_miso  (-->KP)(REP)  =   (R) cfg_miso  (-->KP)(REP) (by sim and name)
# OUT (G) cfg_we  (KP<--)(REP)  =   (R) cfg_we  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_re  (KP<--)(REP)  =   (R) cfg_re  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_addr[4]  (KP<--)(REP)  =   (R) cfg_addr[4]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_addr[3]  (KP<--)(REP)  =   (R) cfg_addr[3]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_addr[2]  (KP<--)(REP)  =   (R) cfg_addr[2]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_addr[1]  (KP<--)(REP)  =   (R) cfg_addr[1]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_addr[0]  (KP<--)(REP)  =   (R) cfg_addr[0]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[31]  (KP<--)(REP)  =   (R) cfg_wdata[31]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[30]  (KP<--)(REP)  =   (R) cfg_wdata[30]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[29]  (KP<--)(REP)  =   (R) cfg_wdata[29]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[28]  (KP<--)(REP)  =   (R) cfg_wdata[28]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[27]  (KP<--)(REP)  =   (R) cfg_wdata[27]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[26]  (KP<--)(REP)  =   (R) cfg_wdata[26]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[25]  (KP<--)(REP)  =   (R) cfg_wdata[25]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[24]  (KP<--)(REP)  =   (R) cfg_wdata[24]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[23]  (KP<--)(REP)  =   (R) cfg_wdata[23]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[22]  (KP<--)(REP)  =   (R) cfg_wdata[22]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[21]  (KP<--)(REP)  =   (R) cfg_wdata[21]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[20]  (KP<--)(REP)  =   (R) cfg_wdata[20]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[19]  (KP<--)(REP)  =   (R) cfg_wdata[19]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[18]  (KP<--)(REP)  =   (R) cfg_wdata[18]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[17]  (KP<--)(REP)  =   (R) cfg_wdata[17]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[16]  (KP<--)(REP)  =   (R) cfg_wdata[16]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[15]  (KP<--)(REP)  =   (R) cfg_wdata[15]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[14]  (KP<--)(REP)  =   (R) cfg_wdata[14]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[13]  (KP<--)(REP)  =   (R) cfg_wdata[13]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[12]  (KP<--)(REP)  =   (R) cfg_wdata[12]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[11]  (KP<--)(REP)  =   (R) cfg_wdata[11]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[10]  (KP<--)(REP)  =   (R) cfg_wdata[10]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[9]  (KP<--)(REP)  =   (R) cfg_wdata[9]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[8]  (KP<--)(REP)  =   (R) cfg_wdata[8]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[7]  (KP<--)(REP)  =   (R) cfg_wdata[7]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[6]  (KP<--)(REP)  =   (R) cfg_wdata[6]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[5]  (KP<--)(REP)  =   (R) cfg_wdata[5]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[4]  (KP<--)(REP)  =   (R) cfg_wdata[4]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[3]  (KP<--)(REP)  =   (R) cfg_wdata[3]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[2]  (KP<--)(REP)  =   (R) cfg_wdata[2]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[1]  (KP<--)(REP)  =   (R) cfg_wdata[1]  (KP<--)(REP) (by sim and name)
# OUT (G) cfg_wdata[0]  (KP<--)(REP)  =   (R) cfg_wdata[0]  (KP<--)(REP) (by sim and name)
set_root_module cfg_serial_if -Golden
set_root_module cfg_serial_if_mapped -Revised
set_module_property -instance /u_cfg_serial_if -Golden
set_module_property -instance /u_cfg_serial_if -Revised
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
add_black_box cfg_serial_if -module -hier -Golden
add_black_box cfg_serial_if_mapped -module -hier -Revised
usage
# Comparing
#-------------------------------------------------------------------------------
# MODULE csr_regbank (G) INSTANCE /u_prbs_ber_chip_top/u_csr_regbank (G)
# MODULE csr_regbank_mapped (R) INSTANCE /u_prbs_ber_chip_top/u_csr_regbank (R)
# Wrapper size: (G) = 513  (R) = 731
# Periphery size: (G) = 2915  (R) = 2849
# Pins directly connected to key-points/constants: (G) = 81.59%  (R) = 82.09%
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk  (KP<--)(REP)  =   (R) clk  (KP<--)(REP) (by sim and name)
# IN (G) rst_n  (KP<--)(REP)  =   (R) rst_n  (KP<--)(REP) (by sim and name)
# IN (G) cfg_we  (KP<--)(REP)  =   (R) cfg_we  (KP<--)(REP) (by sim and name)
# IN (G) cfg_re  (KP<--)(REP)  =   (R) cfg_re  (KP<--)(REP) (by sim and name)
# IN (G) cfg_addr[4]  (KP<--)(REP)  =   (R) cfg_addr[4]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_addr[3]  (KP<--)(REP)  =   (R) cfg_addr[3]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_addr[2]  (KP<--)(REP)  =   (R) cfg_addr[2]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_addr[1]  (KP<--)(REP)  =   (R) cfg_addr[1]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_addr[0]  (KP<--)(REP)  =   (R) cfg_addr[0]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[31]  (KP<--)(REP)  =   (R) cfg_wdata[31]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[30]  (KP<--)(REP)  =   (R) cfg_wdata[30]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[29]  (KP<--)(REP)  =   (R) cfg_wdata[29]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[28]  (KP<--)(REP)  =   (R) cfg_wdata[28]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[27]  (KP<--)(REP)  =   (R) cfg_wdata[27]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[26]  (KP<--)(REP)  =   (R) cfg_wdata[26]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[25]  (KP<--)(REP)  =   (R) cfg_wdata[25]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[24]  (KP<--)(REP)  =   (R) cfg_wdata[24]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[23]  (KP<--)(REP)  =   (R) cfg_wdata[23]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[22]  (KP<--)(REP)  =   (R) cfg_wdata[22]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[21]  (KP<--)(REP)  =   (R) cfg_wdata[21]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[20]  (KP<--)(REP)  =   (R) cfg_wdata[20]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[19]  (KP<--)(REP)  =   (R) cfg_wdata[19]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[18]  (KP<--)(REP)  =   (R) cfg_wdata[18]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[17]  (KP<--)(REP)  =   (R) cfg_wdata[17]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[16]  (KP<--)(REP)  =   (R) cfg_wdata[16]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[15]  (KP<--)(REP)  =   (R) cfg_wdata[15]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[14]  (KP<--)(REP)  =   (R) cfg_wdata[14]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[13]  (KP<--)(REP)  =   (R) cfg_wdata[13]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[12]  (KP<--)(REP)  =   (R) cfg_wdata[12]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[11]  (KP<--)(REP)  =   (R) cfg_wdata[11]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[10]  (KP<--)(REP)  =   (R) cfg_wdata[10]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[9]  (KP<--)(REP)  =   (R) cfg_wdata[9]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[8]  (KP<--)(REP)  =   (R) cfg_wdata[8]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[7]  (KP<--)(REP)  =   (R) cfg_wdata[7]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[6]  (KP<--)(REP)  =   (R) cfg_wdata[6]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[5]  (KP<--)(REP)  =   (R) cfg_wdata[5]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[4]  (KP<--)(REP)  =   (R) cfg_wdata[4]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[3]  (KP<--)(REP)  =   (R) cfg_wdata[3]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[2]  (KP<--)(REP)  =   (R) cfg_wdata[2]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[1]  (KP<--)(REP)  =   (R) cfg_wdata[1]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[0]  (KP<--)(REP)  =   (R) cfg_wdata[0]  (KP<--)(REP) (by sim and name)
# IN (G) busy  (KP<--)(REP)  =   (R) busy  (KP<--)(REP) (by sim and name)
# IN (G) done  (KP<--)(REP)  =   (R) done  (KP<--)(REP) (by sim and name)
# IN (G) overflow  (KP<--)(REP)  =   (R) overflow  (KP<--)(REP) (by sim and name)
# IN (G) bit_error (REP)  =   (R) bit_error (REP) (by name)
# IN (G) prbs_out  (EQ_REP: +ref_bit)  =   (R) prbs_out 0U(REP) (by name)
# IN (G) checker_in (REP)  =   (R) checker_in (REP) (by sim and name)
# IN (G) checker_in_final (REP)  =   (R) checker_in_final (REP) (by sim and name)
# IN (G) ref_bit (REP)  =   (R) ref_bit (REP) (by sim and name)
# IN (G) error_count[31]  (KP<--)(REP)  =   (R) error_count[31]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[30]  (KP<--)(REP)  =   (R) error_count[30]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[29]  (KP<--)(REP)  =   (R) error_count[29]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[28]  (KP<--)(REP)  =   (R) error_count[28]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[27]  (KP<--)(REP)  =   (R) error_count[27]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[26]  (KP<--)(REP)  =   (R) error_count[26]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[25]  (KP<--)(REP)  =   (R) error_count[25]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[24]  (KP<--)(REP)  =   (R) error_count[24]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[23]  (KP<--)(REP)  =   (R) error_count[23]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[22]  (KP<--)(REP)  =   (R) error_count[22]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[21]  (KP<--)(REP)  =   (R) error_count[21]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[20]  (KP<--)(REP)  =   (R) error_count[20]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[19]  (KP<--)(REP)  =   (R) error_count[19]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[18]  (KP<--)(REP)  =   (R) error_count[18]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[17]  (KP<--)(REP)  =   (R) error_count[17]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[16]  (KP<--)(REP)  =   (R) error_count[16]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[15]  (KP<--)(REP)  =   (R) error_count[15]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[14]  (KP<--)(REP)  =   (R) error_count[14]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[13]  (KP<--)(REP)  =   (R) error_count[13]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[12]  (KP<--)(REP)  =   (R) error_count[12]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[11]  (KP<--)(REP)  =   (R) error_count[11]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[10]  (KP<--)(REP)  =   (R) error_count[10]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[9]  (KP<--)(REP)  =   (R) error_count[9]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[8]  (KP<--)(REP)  =   (R) error_count[8]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[7]  (KP<--)(REP)  =   (R) error_count[7]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[6]  (KP<--)(REP)  =   (R) error_count[6]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[5]  (KP<--)(REP)  =   (R) error_count[5]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[4]  (KP<--)(REP)  =   (R) error_count[4]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[3]  (KP<--)(REP)  =   (R) error_count[3]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[2]  (KP<--)(REP)  =   (R) error_count[2]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[1]  (KP<--)(REP)  =   (R) error_count[1]  (KP<--)(REP) (by sim and name)
# IN (G) error_count[0]  (KP<--)(REP)  =   (R) error_count[0]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[31]  (KP<--)(REP)  =   (R) total_count[31]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[30]  (KP<--)(REP)  =   (R) total_count[30]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[29]  (KP<--)(REP)  =   (R) total_count[29]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[28]  (KP<--)(REP)  =   (R) total_count[28]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[27]  (KP<--)(REP)  =   (R) total_count[27]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[26]  (KP<--)(REP)  =   (R) total_count[26]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[25]  (KP<--)(REP)  =   (R) total_count[25]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[24]  (KP<--)(REP)  =   (R) total_count[24]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[23]  (KP<--)(REP)  =   (R) total_count[23]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[22]  (KP<--)(REP)  =   (R) total_count[22]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[21]  (KP<--)(REP)  =   (R) total_count[21]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[20]  (KP<--)(REP)  =   (R) total_count[20]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[19]  (KP<--)(REP)  =   (R) total_count[19]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[18]  (KP<--)(REP)  =   (R) total_count[18]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[17]  (KP<--)(REP)  =   (R) total_count[17]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[16]  (KP<--)(REP)  =   (R) total_count[16]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[15]  (KP<--)(REP)  =   (R) total_count[15]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[14]  (KP<--)(REP)  =   (R) total_count[14]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[13]  (KP<--)(REP)  =   (R) total_count[13]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[12]  (KP<--)(REP)  =   (R) total_count[12]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[11]  (KP<--)(REP)  =   (R) total_count[11]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[10]  (KP<--)(REP)  =   (R) total_count[10]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[9]  (KP<--)(REP)  =   (R) total_count[9]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[8]  (KP<--)(REP)  =   (R) total_count[8]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[7]  (KP<--)(REP)  =   (R) total_count[7]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[6]  (KP<--)(REP)  =   (R) total_count[6]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[5]  (KP<--)(REP)  =   (R) total_count[5]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[4]  (KP<--)(REP)  =   (R) total_count[4]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[3]  (KP<--)(REP)  =   (R) total_count[3]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[2]  (KP<--)(REP)  =   (R) total_count[2]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[1]  (KP<--)(REP)  =   (R) total_count[1]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[0]  (KP<--)(REP)  =   (R) total_count[0]  (KP<--)(REP) (by sim and name)
# RESOLVED Constraints
# OUT (G) cfg_rdata[31] (REP)  =   (R) cfg_rdata[31] (REP) (by sim and name)
# OUT (G) cfg_rdata[30] (REP)  =   (R) cfg_rdata[30] (REP) (by sim and name)
# OUT (G) cfg_rdata[29] (REP)  =   (R) cfg_rdata[29] (REP) (by sim and name)
# OUT (G) cfg_rdata[28] (REP)  =   (R) cfg_rdata[28] (REP) (by sim and name)
# OUT (G) cfg_rdata[27] (REP)  =   (R) cfg_rdata[27] (REP) (by sim and name)
# OUT (G) cfg_rdata[26] (REP)  =   (R) cfg_rdata[26] (REP) (by sim and name)
# OUT (G) cfg_rdata[25] (REP)  =   (R) cfg_rdata[25] (REP) (by sim and name)
# OUT (G) cfg_rdata[24] (REP)  =   (R) cfg_rdata[24] (REP) (by sim and name)
# OUT (G) cfg_rdata[23] (REP)  =   (R) cfg_rdata[23] (REP) (by sim and name)
# OUT (G) cfg_rdata[22] (REP)  =   (R) cfg_rdata[22] (REP) (by sim and name)
# OUT (G) cfg_rdata[21] (REP)  =   (R) cfg_rdata[21] (REP) (by sim and name)
# OUT (G) cfg_rdata[20] (REP)  =   (R) cfg_rdata[20] (REP) (by sim and name)
# OUT (G) cfg_rdata[19] (REP)  =   (R) cfg_rdata[19] (REP) (by sim and name)
# OUT (G) cfg_rdata[18] (REP)  =   (R) cfg_rdata[18] (REP) (by sim and name)
# OUT (G) cfg_rdata[17] (REP)  =   (R) cfg_rdata[17] (REP) (by sim and name)
# OUT (G) cfg_rdata[16] (REP)  =   (R) cfg_rdata[16] (REP) (by sim and name)
# OUT (G) cfg_rdata[15] (REP)  =   (R) cfg_rdata[15] (REP) (by sim and name)
# OUT (G) cfg_rdata[14] (REP)  =   (R) cfg_rdata[14] (REP) (by sim and name)
# OUT (G) cfg_rdata[13] (REP)  =   (R) cfg_rdata[13] (REP) (by sim and name)
# OUT (G) cfg_rdata[12] (REP)  =   (R) cfg_rdata[12] (REP) (by sim and name)
# OUT (G) cfg_rdata[11] (REP)  =   (R) cfg_rdata[11] (REP) (by sim and name)
# OUT (G) cfg_rdata[10] (REP)  =   (R) cfg_rdata[10] (REP) (by sim and name)
# OUT (G) cfg_rdata[9] (REP)  =   (R) cfg_rdata[9] (REP) (by sim and name)
# OUT (G) cfg_rdata[8] (REP)  =   (R) cfg_rdata[8] (REP) (by sim and name)
# OUT (G) cfg_rdata[7] (REP)  =   (R) cfg_rdata[7] (REP) (by sim and name)
# OUT (G) cfg_rdata[6] (REP)  =   (R) cfg_rdata[6] (REP) (by sim and name)
# OUT (G) cfg_rdata[5] (REP)  =   (R) cfg_rdata[5] (REP) (by sim and name)
# OUT (G) cfg_rdata[4] (REP)  =   (R) cfg_rdata[4] (REP) (by sim and name)
# OUT (G) cfg_rdata[3] (REP)  =   (R) cfg_rdata[3] (REP) (by sim and name)
# OUT (G) cfg_rdata[2] (REP)  =   (R) cfg_rdata[2] (REP) (by sim and name)
# OUT (G) cfg_rdata[1] (REP)  =   (R) cfg_rdata[1] (REP) (by sim and name)
# OUT (G) cfg_rdata[0] (REP)  =   (R) cfg_rdata[0] (REP) (by sim and name)
# OUT (G) ctrl_enable  (KP<--)(REP)  =   (R) ctrl_enable  (KP<--)(REP) (by sim and name)
# OUT (G) mode_select  (KP<--)(REP)  =   (R) mode_select  (KP<--)(REP) (by sim and name)
# OUT (G) input_select  (KP<--)(REP)  =   (R) input_select  (KP<--)(REP) (by sim and name)
# OUT (G) inject_error_enable  (KP<--)(REP)  =   (R) inject_error_enable  (KP<--)(REP) (by sim and name)
# OUT (G) continuous_mode  (KP<--)(REP)  =   (R) continuous_mode  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[14]  (KP<--)(REP)  =   (R) seed_value[14]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[13]  (KP<--)(REP)  =   (R) seed_value[13]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[12]  (KP<--)(REP)  =   (R) seed_value[12]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[11]  (KP<--)(REP)  =   (R) seed_value[11]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[10]  (KP<--)(REP)  =   (R) seed_value[10]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[9]  (KP<--)(REP)  =   (R) seed_value[9]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[8]  (KP<--)(REP)  =   (R) seed_value[8]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[7]  (KP<--)(REP)  =   (R) seed_value[7]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[6]  (KP<--)(REP)  =   (R) seed_value[6]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[5]  (KP<--)(REP)  =   (R) seed_value[5]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[4]  (KP<--)(REP)  =   (R) seed_value[4]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[3]  (KP<--)(REP)  =   (R) seed_value[3]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[2]  (KP<--)(REP)  =   (R) seed_value[2]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[1]  (KP<--)(REP)  =   (R) seed_value[1]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_value[0]  (KP<--)(REP)  =   (R) seed_value[0]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[31]  (KP<--)(REP)  =   (R) window_cfg[31]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[30]  (KP<--)(REP)  =   (R) window_cfg[30]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[29]  (KP<--)(REP)  =   (R) window_cfg[29]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[28]  (KP<--)(REP)  =   (R) window_cfg[28]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[27]  (KP<--)(REP)  =   (R) window_cfg[27]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[26]  (KP<--)(REP)  =   (R) window_cfg[26]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[25]  (KP<--)(REP)  =   (R) window_cfg[25]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[24]  (KP<--)(REP)  =   (R) window_cfg[24]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[23]  (KP<--)(REP)  =   (R) window_cfg[23]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[22]  (KP<--)(REP)  =   (R) window_cfg[22]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[21]  (KP<--)(REP)  =   (R) window_cfg[21]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[20]  (KP<--)(REP)  =   (R) window_cfg[20]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[19]  (KP<--)(REP)  =   (R) window_cfg[19]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[18]  (KP<--)(REP)  =   (R) window_cfg[18]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[17]  (KP<--)(REP)  =   (R) window_cfg[17]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[16]  (KP<--)(REP)  =   (R) window_cfg[16]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[15]  (KP<--)(REP)  =   (R) window_cfg[15]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[14]  (KP<--)(REP)  =   (R) window_cfg[14]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[13]  (KP<--)(REP)  =   (R) window_cfg[13]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[12]  (KP<--)(REP)  =   (R) window_cfg[12]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[11]  (KP<--)(REP)  =   (R) window_cfg[11]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[10]  (KP<--)(REP)  =   (R) window_cfg[10]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[9]  (KP<--)(REP)  =   (R) window_cfg[9]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[8]  (KP<--)(REP)  =   (R) window_cfg[8]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[7]  (KP<--)(REP)  =   (R) window_cfg[7]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[6]  (KP<--)(REP)  =   (R) window_cfg[6]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[5]  (KP<--)(REP)  =   (R) window_cfg[5]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[4]  (KP<--)(REP)  =   (R) window_cfg[4]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[3]  (KP<--)(REP)  =   (R) window_cfg[3]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[2]  (KP<--)(REP)  =   (R) window_cfg[2]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[1]  (KP<--)(REP)  =   (R) window_cfg[1]  (KP<--)(REP) (by sim and name)
# OUT (G) window_cfg[0]  (KP<--)(REP)  =   (R) window_cfg[0]  (KP<--)(REP) (by sim and name)
# OUT (G) seed_load_pulse  (KP<--)(REP)  =   (R) seed_load_pulse  (KP<--)(REP) (by sim and name)
# OUT (G) start_pulse  (KP<--)(REP)  =   (R) start_pulse  (KP<--)(REP) (by sim and name)
# OUT (G) stop_pulse  (KP<--)(REP)  =   (R) stop_pulse  (KP<--)(REP) (by sim and name)
# OUT (G) manual_clear_pulse  (KP<--)(REP)  =   (R) manual_clear_pulse  (KP<--)(REP) (by sim and name)
set_root_module csr_regbank -Golden
set_root_module csr_regbank_mapped -Revised
set_module_property -instance /u_prbs_ber_chip_top/u_csr_regbank -Golden
set_module_property -instance /u_prbs_ber_chip_top/u_csr_regbank -Revised
# Constraint commands 
add_pin_equivalences ref_bit prbs_out -hier -Golden
add_pin_constraints 0 prbs_out -Revised
add_ignored_inputs prbs_out -Revised
# UR stuck_at
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
add_black_box csr_regbank -module -hier -Golden
add_black_box csr_regbank_mapped -module -hier -Revised
usage
#-------------------------------------------------------------------------------
# MODULE measure_ctrl (G) INSTANCE /u_prbs_ber_chip_top/u_measure_ctrl (G)
# MODULE measure_ctrl_mapped (R) INSTANCE /u_prbs_ber_chip_top/u_measure_ctrl (R)
# Wrapper size: (G) = 775  (R) = 790
# Periphery size: (G) = 986  (R) = 1087
# Pins directly connected to key-points/constants: (G) = 100.00%  (R) = 100.00%
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk  (KP<--)(REP)  =   (R) clk  (KP<--)(REP) (by sim and name)
# IN (G) rst_n  (KP<--)(REP)  =   (R) rst_n  (KP<--)(REP) (by sim and name)
# IN (G) start_pulse  (KP<--)(REP)  =   (R) start_pulse  (KP<--)(REP) (by sim and name)
# IN (G) stop_pulse  (KP<--)(REP)  =   (R) stop_pulse  (KP<--)(REP) (by sim and name)
# IN (G) continuous_mode  (KP<--)(REP)  =   (R) continuous_mode  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[31]  (KP<--)(REP)  =   (R) window_cfg[31]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[30]  (KP<--)(REP)  =   (R) window_cfg[30]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[29]  (KP<--)(REP)  =   (R) window_cfg[29]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[28]  (KP<--)(REP)  =   (R) window_cfg[28]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[27]  (KP<--)(REP)  =   (R) window_cfg[27]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[26]  (KP<--)(REP)  =   (R) window_cfg[26]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[25]  (KP<--)(REP)  =   (R) window_cfg[25]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[24]  (KP<--)(REP)  =   (R) window_cfg[24]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[23]  (KP<--)(REP)  =   (R) window_cfg[23]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[22]  (KP<--)(REP)  =   (R) window_cfg[22]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[21]  (KP<--)(REP)  =   (R) window_cfg[21]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[20]  (KP<--)(REP)  =   (R) window_cfg[20]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[19]  (KP<--)(REP)  =   (R) window_cfg[19]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[18]  (KP<--)(REP)  =   (R) window_cfg[18]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[17]  (KP<--)(REP)  =   (R) window_cfg[17]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[16]  (KP<--)(REP)  =   (R) window_cfg[16]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[15]  (KP<--)(REP)  =   (R) window_cfg[15]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[14]  (KP<--)(REP)  =   (R) window_cfg[14]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[13]  (KP<--)(REP)  =   (R) window_cfg[13]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[12]  (KP<--)(REP)  =   (R) window_cfg[12]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[11]  (KP<--)(REP)  =   (R) window_cfg[11]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[10]  (KP<--)(REP)  =   (R) window_cfg[10]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[9]  (KP<--)(REP)  =   (R) window_cfg[9]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[8]  (KP<--)(REP)  =   (R) window_cfg[8]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[7]  (KP<--)(REP)  =   (R) window_cfg[7]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[6]  (KP<--)(REP)  =   (R) window_cfg[6]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[5]  (KP<--)(REP)  =   (R) window_cfg[5]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[4]  (KP<--)(REP)  =   (R) window_cfg[4]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[3]  (KP<--)(REP)  =   (R) window_cfg[3]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[2]  (KP<--)(REP)  =   (R) window_cfg[2]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[1]  (KP<--)(REP)  =   (R) window_cfg[1]  (KP<--)(REP) (by sim and name)
# IN (G) window_cfg[0]  (KP<--)(REP)  =   (R) window_cfg[0]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[31]  (KP<--)(REP)  =   (R) total_count[31]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[30]  (KP<--)(REP)  =   (R) total_count[30]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[29]  (KP<--)(REP)  =   (R) total_count[29]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[28]  (KP<--)(REP)  =   (R) total_count[28]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[27]  (KP<--)(REP)  =   (R) total_count[27]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[26]  (KP<--)(REP)  =   (R) total_count[26]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[25]  (KP<--)(REP)  =   (R) total_count[25]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[24]  (KP<--)(REP)  =   (R) total_count[24]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[23]  (KP<--)(REP)  =   (R) total_count[23]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[22]  (KP<--)(REP)  =   (R) total_count[22]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[21]  (KP<--)(REP)  =   (R) total_count[21]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[20]  (KP<--)(REP)  =   (R) total_count[20]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[19]  (KP<--)(REP)  =   (R) total_count[19]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[18]  (KP<--)(REP)  =   (R) total_count[18]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[17]  (KP<--)(REP)  =   (R) total_count[17]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[16]  (KP<--)(REP)  =   (R) total_count[16]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[15]  (KP<--)(REP)  =   (R) total_count[15]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[14]  (KP<--)(REP)  =   (R) total_count[14]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[13]  (KP<--)(REP)  =   (R) total_count[13]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[12]  (KP<--)(REP)  =   (R) total_count[12]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[11]  (KP<--)(REP)  =   (R) total_count[11]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[10]  (KP<--)(REP)  =   (R) total_count[10]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[9]  (KP<--)(REP)  =   (R) total_count[9]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[8]  (KP<--)(REP)  =   (R) total_count[8]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[7]  (KP<--)(REP)  =   (R) total_count[7]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[6]  (KP<--)(REP)  =   (R) total_count[6]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[5]  (KP<--)(REP)  =   (R) total_count[5]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[4]  (KP<--)(REP)  =   (R) total_count[4]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[3]  (KP<--)(REP)  =   (R) total_count[3]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[2]  (KP<--)(REP)  =   (R) total_count[2]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[1]  (KP<--)(REP)  =   (R) total_count[1]  (KP<--)(REP) (by sim and name)
# IN (G) total_count[0]  (KP<--)(REP)  =   (R) total_count[0]  (KP<--)(REP) (by sim and name)
# RESOLVED Constraints
# OUT (G) core_en  (KP<--)(REP)  =   (R) core_en  (KP<--)(REP) (by name)
# OUT (G) clear_count_pulse  (KP<--)(REP)  =   (R) clear_count_pulse  (KP<--)(REP) (by sim and name)
# OUT (G) busy  (KP<--)(REP)  =   (R) busy 0(REP) (by name)
# OUT (G) done  (KP<--)(REP)  =   (R) done  (KP<--)(REP) (by sim and name)
# OUT (G) overflow  (KP<--)(REP)  =   (R) overflow  (KP<--)(REP) (by sim and name)
# Comparing
#-------------------------------------------------------------------------------
# MODULE prbs_core_LFSR_W7_DEFAULT_SEED1 (G) INSTANCE /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core (G)
# MODULE prbs_core_LFSR_W7_DEFAULT_SEED1_mapped (R) INSTANCE /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core (R)
# Primitive count:  (G) = 37  (R) = 59
# Wrapper size: (G) = 364  (R) = 209
# Periphery size: (G) = 385  (R) = 253
# Pins directly connected to key-points/constants: (G) = 52.63%  (R) = 84.21%
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk  (KP<--)(REP)  =   (R) clk  (KP<--)(REP) (by sim and name)
# IN (G) rst_n  (KP<--)(REP)  =   (R) rst_n  (KP<--)(REP) (by sim and name)
# IN (G) load_req (REP)  =   (R) load_req (REP) (by sim and name)
# IN (G) seed_value[6] (REP)  =   (R) seed_value[6]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[5] (REP)  =   (R) seed_value[5]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[4] (REP)  =   (R) seed_value[4]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[3] (REP)  =   (R) seed_value[3]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[2] (REP)  =   (R) seed_value[2]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[1] (REP)  =   (R) seed_value[1]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[0] (REP)  =   (R) seed_value[0] (REP) (by sim and name)
# IN (G) step_en (REP)  =   (R) step_en (REP) (by name)
# RESOLVED Constraints
# OUT (G) prbs_out  (KP<--)(REP)  =   (R) prbs_out  (KP<--)(REP) (by sim and name)
# OUT (G) state_out[6] U (KP<--) (EQ_REP: +prbs_out)  =   (R) state_out[6] 0U(REP) (by name)
# OUT (G) state_out[5] U (KP<--)(REP)  =   (R) state_out[5] 0U(REP) (by name)
# OUT (G) state_out[4] U (KP<--)(REP)  =   (R) state_out[4] 0U(REP) (by name)
# OUT (G) state_out[3] U (KP<--)(REP)  =   (R) state_out[3] 0U(REP) (by name)
# OUT (G) state_out[2] U (KP<--)(REP)  =   (R) state_out[2] 0U(REP) (by name)
# OUT (G) state_out[1] U (KP<--)(REP)  =   (R) state_out[1] 0U(REP) (by name)
# OUT (G) state_out[0] U (KP<--)(REP)  =   (R) state_out[0] 0U(REP) (by name)
set_root_module prbs_core_LFSR_W7_DEFAULT_SEED1 -Golden
set_root_module prbs_core_LFSR_W7_DEFAULT_SEED1_mapped -Revised
set_module_property -instance /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core -Golden
set_module_property -instance /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core -Revised
# Constraint commands 
add_output_equivalences prbs_out {state_out[6]} -hier -Golden
add_ignored_outputs {state_out[6]} -Golden -System
# (EQ)
add_ignored_outputs {state_out[5]} -Golden -System
# UR
add_ignored_outputs {state_out[4]} -Golden -System
# UR
add_ignored_outputs {state_out[3]} -Golden -System
# UR
add_ignored_outputs {state_out[2]} -Golden -System
# UR
add_ignored_outputs {state_out[1]} -Golden -System
# UR
add_ignored_outputs {state_out[0]} -Golden -System
# UR
add_output_stuck_at 0 {state_out[6]} -Revised -hier
add_ignored_outputs {state_out[6]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[5]} -Revised -hier
add_ignored_outputs {state_out[5]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[4]} -Revised -hier
add_ignored_outputs {state_out[4]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[3]} -Revised -hier
add_ignored_outputs {state_out[3]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[2]} -Revised -hier
add_ignored_outputs {state_out[2]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[1]} -Revised -hier
add_ignored_outputs {state_out[1]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[0]} -Revised -hier
add_ignored_outputs {state_out[0]} -Revised -System
# UR stuck_at
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
add_black_box prbs_core_LFSR_W7_DEFAULT_SEED1 -module -hier -Golden
add_black_box prbs_core_LFSR_W7_DEFAULT_SEED1_mapped -module -hier -Revised
usage
# Comparing
#-------------------------------------------------------------------------------
# MODULE prbs_top (G) INSTANCE /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top (G)
# MODULE prbs_top_mapped (R) INSTANCE /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top (R)
# Primitive count:  (G) = 47  (R) = 73
# Wrapper size: (G) = 356  (R) = 198
# Periphery size: (G) = 385  (R) = 239
# Pins directly connected to key-points/constants: (G) = 83.33%  (R) = 83.33%
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk  (KP<--)(REP)  =   (R) clk  (KP<--)(REP) (by sim and name)
# IN (G) rst_n  (KP<--)(REP)  =   (R) rst_n  (KP<--)(REP) (by sim and name)
# IN (G) en (REP)  =   (R) en (REP) (by name)
# IN (G) seed_load (REP)  =   (R) seed_load (REP) (by sim and name)
# IN (G) seed_in[6]  (KP<--)(REP)  =   (R) seed_in[6]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[5]  (KP<--)(REP)  =   (R) seed_in[5]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[4]  (KP<--)(REP)  =   (R) seed_in[4]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[3]  (KP<--)(REP)  =   (R) seed_in[3]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[2]  (KP<--)(REP)  =   (R) seed_in[2]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[1]  (KP<--)(REP)  =   (R) seed_in[1]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[0]  (KP<--)(REP)  =   (R) seed_in[0]  (KP<--)(REP) (by sim and name)
# RESOLVED Constraints
# OUT (G) prbs_out  (KP<--)(REP)  =   (R) prbs_out  (KP<--)(REP) (by sim and name)
set_root_module prbs_top -Golden
set_root_module prbs_top_mapped -Revised
set_module_property -instance /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top -Golden
set_module_property -instance /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top -Revised
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
add_black_box prbs_top -module -hier -Golden
add_black_box prbs_top_mapped -module -hier -Revised
usage
# Comparing
#-------------------------------------------------------------------------------
# MODULE prbs15_core_LFSR_W15_DEFAULT_SEED1 (G) INSTANCE /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core (G)
# MODULE prbs15_core_LFSR_W15_DEFAULT_SEED1_mapped (R) INSTANCE /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core (R)
# Wrapper size: (G) = 372  (R) = 219
# Periphery size: (G) = 417  (R) = 310
# Pins directly connected to key-points/constants: (G) = 51.43%  (R) = 91.43%
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk  (KP<--)(REP)  =   (R) clk  (KP<--)(REP) (by sim and name)
# IN (G) rst_n  (KP<--)(REP)  =   (R) rst_n  (KP<--)(REP) (by sim and name)
# IN (G) load_req (REP)  =   (R) load_req (REP) (by sim and name)
# IN (G) seed_value[14] (REP)  =   (R) seed_value[14]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[13] (REP)  =   (R) seed_value[13]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[12] (REP)  =   (R) seed_value[12]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[11] (REP)  =   (R) seed_value[11]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[10] (REP)  =   (R) seed_value[10]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[9] (REP)  =   (R) seed_value[9]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[8] (REP)  =   (R) seed_value[8]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[7] (REP)  =   (R) seed_value[7]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[6] (REP)  =   (R) seed_value[6]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[5] (REP)  =   (R) seed_value[5]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[4] (REP)  =   (R) seed_value[4]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[3] (REP)  =   (R) seed_value[3]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[2] (REP)  =   (R) seed_value[2]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[1] (REP)  =   (R) seed_value[1]  (KP<--)(REP) (by sim and name)
# IN (G) seed_value[0] (REP)  =   (R) seed_value[0] (REP) (by sim and name)
# IN (G) step_en (REP)  =   (R) step_en (REP) (by name)
# RESOLVED Constraints
# OUT (G) prbs_out  (KP<--)(REP)  =   (R) prbs_out  (KP<--)(REP) (by sim and name)
# OUT (G) state_out[14] U (KP<--) (EQ_REP: +prbs_out)  =   (R) state_out[14] 0U(REP) (by name)
# OUT (G) state_out[13] U (KP<--)(REP)  =   (R) state_out[13] 0U(REP) (by name)
# OUT (G) state_out[12] U (KP<--)(REP)  =   (R) state_out[12] 0U(REP) (by name)
# OUT (G) state_out[11] U (KP<--)(REP)  =   (R) state_out[11] 0U(REP) (by name)
# OUT (G) state_out[10] U (KP<--)(REP)  =   (R) state_out[10] 0U(REP) (by name)
# OUT (G) state_out[9] U (KP<--)(REP)  =   (R) state_out[9] 0U(REP) (by name)
# OUT (G) state_out[8] U (KP<--)(REP)  =   (R) state_out[8] 0U(REP) (by name)
# OUT (G) state_out[7] U (KP<--)(REP)  =   (R) state_out[7] 0U(REP) (by name)
# OUT (G) state_out[6] U (KP<--)(REP)  =   (R) state_out[6] 0U(REP) (by name)
# OUT (G) state_out[5] U (KP<--)(REP)  =   (R) state_out[5] 0U(REP) (by name)
# OUT (G) state_out[4] U (KP<--)(REP)  =   (R) state_out[4] 0U(REP) (by name)
# OUT (G) state_out[3] U (KP<--)(REP)  =   (R) state_out[3] 0U(REP) (by name)
# OUT (G) state_out[2] U (KP<--)(REP)  =   (R) state_out[2] 0U(REP) (by name)
# OUT (G) state_out[1] U (KP<--)(REP)  =   (R) state_out[1] 0U(REP) (by name)
# OUT (G) state_out[0] U (KP<--)(REP)  =   (R) state_out[0] 0U(REP) (by name)
set_root_module prbs15_core_LFSR_W15_DEFAULT_SEED1 -Golden
set_root_module prbs15_core_LFSR_W15_DEFAULT_SEED1_mapped -Revised
set_module_property -instance /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core -Golden
set_module_property -instance /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core -Revised
# Constraint commands 
add_output_equivalences prbs_out {state_out[14]} -hier -Golden
add_ignored_outputs {state_out[14]} -Golden -System
# (EQ)
add_ignored_outputs {state_out[13]} -Golden -System
# UR
add_ignored_outputs {state_out[12]} -Golden -System
# UR
add_ignored_outputs {state_out[11]} -Golden -System
# UR
add_ignored_outputs {state_out[10]} -Golden -System
# UR
add_ignored_outputs {state_out[9]} -Golden -System
# UR
add_ignored_outputs {state_out[8]} -Golden -System
# UR
add_ignored_outputs {state_out[7]} -Golden -System
# UR
add_ignored_outputs {state_out[6]} -Golden -System
# UR
add_ignored_outputs {state_out[5]} -Golden -System
# UR
add_ignored_outputs {state_out[4]} -Golden -System
# UR
add_ignored_outputs {state_out[3]} -Golden -System
# UR
add_ignored_outputs {state_out[2]} -Golden -System
# UR
add_ignored_outputs {state_out[1]} -Golden -System
# UR
add_ignored_outputs {state_out[0]} -Golden -System
# UR
add_output_stuck_at 0 {state_out[14]} -Revised -hier
add_ignored_outputs {state_out[14]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[13]} -Revised -hier
add_ignored_outputs {state_out[13]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[12]} -Revised -hier
add_ignored_outputs {state_out[12]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[11]} -Revised -hier
add_ignored_outputs {state_out[11]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[10]} -Revised -hier
add_ignored_outputs {state_out[10]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[9]} -Revised -hier
add_ignored_outputs {state_out[9]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[8]} -Revised -hier
add_ignored_outputs {state_out[8]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[7]} -Revised -hier
add_ignored_outputs {state_out[7]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[6]} -Revised -hier
add_ignored_outputs {state_out[6]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[5]} -Revised -hier
add_ignored_outputs {state_out[5]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[4]} -Revised -hier
add_ignored_outputs {state_out[4]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[3]} -Revised -hier
add_ignored_outputs {state_out[3]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[2]} -Revised -hier
add_ignored_outputs {state_out[2]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[1]} -Revised -hier
add_ignored_outputs {state_out[1]} -Revised -System
# UR stuck_at
add_output_stuck_at 0 {state_out[0]} -Revised -hier
add_ignored_outputs {state_out[0]} -Revised -System
# UR stuck_at
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
add_black_box prbs15_core_LFSR_W15_DEFAULT_SEED1 -module -hier -Golden
add_black_box prbs15_core_LFSR_W15_DEFAULT_SEED1_mapped -module -hier -Revised
usage
# Comparing
#-------------------------------------------------------------------------------
# MODULE prbs15_top (G) INSTANCE /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top (G)
# MODULE prbs15_top_mapped (R) INSTANCE /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top (R)
# Wrapper size: (G) = 356  (R) = 198
# Periphery size: (G) = 417  (R) = 280
# Pins directly connected to key-points/constants: (G) = 90.00%  (R) = 90.00%
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk  (KP<--)(REP)  =   (R) clk  (KP<--)(REP) (by sim and name)
# IN (G) rst_n  (KP<--)(REP)  =   (R) rst_n  (KP<--)(REP) (by sim and name)
# IN (G) en (REP)  =   (R) en (REP) (by name)
# IN (G) seed_load (REP)  =   (R) seed_load (REP) (by sim and name)
# IN (G) seed_in[14]  (KP<--)(REP)  =   (R) seed_in[14]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[13]  (KP<--)(REP)  =   (R) seed_in[13]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[12]  (KP<--)(REP)  =   (R) seed_in[12]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[11]  (KP<--)(REP)  =   (R) seed_in[11]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[10]  (KP<--)(REP)  =   (R) seed_in[10]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[9]  (KP<--)(REP)  =   (R) seed_in[9]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[8]  (KP<--)(REP)  =   (R) seed_in[8]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[7]  (KP<--)(REP)  =   (R) seed_in[7]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[6]  (KP<--)(REP)  =   (R) seed_in[6]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[5]  (KP<--)(REP)  =   (R) seed_in[5]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[4]  (KP<--)(REP)  =   (R) seed_in[4]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[3]  (KP<--)(REP)  =   (R) seed_in[3]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[2]  (KP<--)(REP)  =   (R) seed_in[2]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[1]  (KP<--)(REP)  =   (R) seed_in[1]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[0]  (KP<--)(REP)  =   (R) seed_in[0]  (KP<--)(REP) (by sim and name)
# RESOLVED Constraints
# OUT (G) prbs_out  (KP<--)(REP)  =   (R) prbs_out  (KP<--)(REP) (by sim and name)
set_root_module prbs15_top -Golden
set_root_module prbs15_top_mapped -Revised
set_module_property -instance /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top -Golden
set_module_property -instance /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top -Revised
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
add_black_box prbs15_top -module -hier -Golden
add_black_box prbs15_top_mapped -module -hier -Revised
usage
# Comparing
#-------------------------------------------------------------------------------
# MODULE prbs_gen_top (G) INSTANCE /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top (G)
# MODULE prbs_gen_top_mapped (R) INSTANCE /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top (R)
# Wrapper size: (G) = 353  (R) = 194
# Periphery size: (G) = 449  (R) = 327
# Pins directly connected to key-points/constants: (G) = 90.48%  (R) = 90.48%
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk  (KP<--)(REP)  =   (R) clk  (KP<--)(REP) (by sim and name)
# IN (G) rst_n  (KP<--)(REP)  =   (R) rst_n  (KP<--)(REP) (by sim and name)
# IN (G) en (REP)  =   (R) en (REP) (by name)
# IN (G) seed_load  (KP<--)(REP)  =   (R) seed_load  (KP<--)(REP) (by sim and name)
# IN (G) mode_select  (KP<--)(REP)  =   (R) mode_select  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[14]  (KP<--)(REP)  =   (R) seed_in[14]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[13]  (KP<--)(REP)  =   (R) seed_in[13]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[12]  (KP<--)(REP)  =   (R) seed_in[12]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[11]  (KP<--)(REP)  =   (R) seed_in[11]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[10]  (KP<--)(REP)  =   (R) seed_in[10]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[9]  (KP<--)(REP)  =   (R) seed_in[9]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[8]  (KP<--)(REP)  =   (R) seed_in[8]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[7]  (KP<--)(REP)  =   (R) seed_in[7]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[6]  (KP<--)(REP)  =   (R) seed_in[6]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[5]  (KP<--)(REP)  =   (R) seed_in[5]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[4]  (KP<--)(REP)  =   (R) seed_in[4]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[3]  (KP<--)(REP)  =   (R) seed_in[3]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[2]  (KP<--)(REP)  =   (R) seed_in[2]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[1]  (KP<--)(REP)  =   (R) seed_in[1]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[0]  (KP<--)(REP)  =   (R) seed_in[0]  (KP<--)(REP) (by sim and name)
# RESOLVED Constraints
# OUT (G) prbs_out (REP)  =   (R) prbs_out (REP) (by sim and name)
set_root_module prbs_gen_top -Golden
set_root_module prbs_gen_top_mapped -Revised
set_module_property -instance /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top -Golden
set_module_property -instance /u_prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top -Revised
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
add_black_box prbs_gen_top -module -hier -Golden
add_black_box prbs_gen_top_mapped -module -hier -Revised
usage
# Comparing
#-------------------------------------------------------------------------------
# MODULE prbs_ber_top (G) INSTANCE /u_prbs_ber_chip_top/u_prbs_ber_top (G)
# MODULE prbs_ber_top_mapped (R) INSTANCE /u_prbs_ber_chip_top/u_prbs_ber_top (R)
# Wrapper size: (G) = 856  (R) = 901
# Periphery size: (G) = 1094  (R) = 1250
# Pins directly connected to key-points/constants: (G) = 92.47%  (R) = 93.55%
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk  (KP<--)(REP)  =   (R) clk  (KP<--)(REP) (by sim and name)
# IN (G) rst_n  (KP<--)(REP)  =   (R) rst_n  (KP<--)(REP) (by sim and name)
# IN (G) en (REP)  =   (R) en (REP) (by name)
# IN (G) clear_count (REP)  =   (R) clear_count (REP) (by sim and name)
# IN (G) seed_load  (KP<--)(REP)  =   (R) seed_load  (KP<--)(REP) (by sim and name)
# IN (G) mode_select  (KP<--)(REP)  =   (R) mode_select  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[14]  (KP<--)(REP)  =   (R) seed_in[14]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[13]  (KP<--)(REP)  =   (R) seed_in[13]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[12]  (KP<--)(REP)  =   (R) seed_in[12]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[11]  (KP<--)(REP)  =   (R) seed_in[11]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[10]  (KP<--)(REP)  =   (R) seed_in[10]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[9]  (KP<--)(REP)  =   (R) seed_in[9]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[8]  (KP<--)(REP)  =   (R) seed_in[8]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[7]  (KP<--)(REP)  =   (R) seed_in[7]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[6]  (KP<--)(REP)  =   (R) seed_in[6]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[5]  (KP<--)(REP)  =   (R) seed_in[5]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[4]  (KP<--)(REP)  =   (R) seed_in[4]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[3]  (KP<--)(REP)  =   (R) seed_in[3]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[2]  (KP<--)(REP)  =   (R) seed_in[2]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[1]  (KP<--)(REP)  =   (R) seed_in[1]  (KP<--)(REP) (by sim and name)
# IN (G) seed_in[0]  (KP<--)(REP)  =   (R) seed_in[0]  (KP<--)(REP) (by sim and name)
# IN (G) input_select  (KP<--)(REP)  =   (R) input_select  (KP<--)(REP) (by sim and name)
# IN (G) inject_error_enable  (KP<--)(REP)  =   (R) inject_error_enable  (KP<--)(REP) (by sim and name)
# IN (G) ext_serial_in  (KP<--)(REP)  =   (R) ext_serial_in  (KP<--)(REP) (by sim and name)
# RESOLVED Constraints
# OUT (G) prbs_out (REP)  =   (R) prbs_out (REP) (by sim and name)
# OUT (G) checker_in (REP)  =   (R) checker_in (REP) (by sim and name)
# OUT (G) checker_in_final (REP)  =   (R) checker_in_final (REP) (by sim and name)
# OUT (G) ref_bit  (EQ_REP: +prbs_out)  =   (R) ref_bit 0U(REP) (by name)
# OUT (G) bit_error (REP)  =   (R) bit_error (REP) (by name)
# OUT (G) error_count[31]  (KP<--)(REP)  =   (R) error_count[31]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[30]  (KP<--)(REP)  =   (R) error_count[30]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[29]  (KP<--)(REP)  =   (R) error_count[29]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[28]  (KP<--)(REP)  =   (R) error_count[28]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[27]  (KP<--)(REP)  =   (R) error_count[27]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[26]  (KP<--)(REP)  =   (R) error_count[26]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[25]  (KP<--)(REP)  =   (R) error_count[25]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[24]  (KP<--)(REP)  =   (R) error_count[24]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[23]  (KP<--)(REP)  =   (R) error_count[23]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[22]  (KP<--)(REP)  =   (R) error_count[22]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[21]  (KP<--)(REP)  =   (R) error_count[21]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[20]  (KP<--)(REP)  =   (R) error_count[20]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[19]  (KP<--)(REP)  =   (R) error_count[19]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[18]  (KP<--)(REP)  =   (R) error_count[18]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[17]  (KP<--)(REP)  =   (R) error_count[17]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[16]  (KP<--)(REP)  =   (R) error_count[16]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[15]  (KP<--)(REP)  =   (R) error_count[15]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[14]  (KP<--)(REP)  =   (R) error_count[14]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[13]  (KP<--)(REP)  =   (R) error_count[13]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[12]  (KP<--)(REP)  =   (R) error_count[12]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[11]  (KP<--)(REP)  =   (R) error_count[11]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[10]  (KP<--)(REP)  =   (R) error_count[10]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[9]  (KP<--)(REP)  =   (R) error_count[9]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[8]  (KP<--)(REP)  =   (R) error_count[8]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[7]  (KP<--)(REP)  =   (R) error_count[7]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[6]  (KP<--)(REP)  =   (R) error_count[6]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[5]  (KP<--)(REP)  =   (R) error_count[5]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[4]  (KP<--)(REP)  =   (R) error_count[4]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[3]  (KP<--)(REP)  =   (R) error_count[3]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[2]  (KP<--)(REP)  =   (R) error_count[2]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[1]  (KP<--)(REP)  =   (R) error_count[1]  (KP<--)(REP) (by sim and name)
# OUT (G) error_count[0]  (KP<--)(REP)  =   (R) error_count[0]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[31]  (KP<--)(REP)  =   (R) total_count[31]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[30]  (KP<--)(REP)  =   (R) total_count[30]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[29]  (KP<--)(REP)  =   (R) total_count[29]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[28]  (KP<--)(REP)  =   (R) total_count[28]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[27]  (KP<--)(REP)  =   (R) total_count[27]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[26]  (KP<--)(REP)  =   (R) total_count[26]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[25]  (KP<--)(REP)  =   (R) total_count[25]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[24]  (KP<--)(REP)  =   (R) total_count[24]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[23]  (KP<--)(REP)  =   (R) total_count[23]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[22]  (KP<--)(REP)  =   (R) total_count[22]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[21]  (KP<--)(REP)  =   (R) total_count[21]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[20]  (KP<--)(REP)  =   (R) total_count[20]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[19]  (KP<--)(REP)  =   (R) total_count[19]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[18]  (KP<--)(REP)  =   (R) total_count[18]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[17]  (KP<--)(REP)  =   (R) total_count[17]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[16]  (KP<--)(REP)  =   (R) total_count[16]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[15]  (KP<--)(REP)  =   (R) total_count[15]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[14]  (KP<--)(REP)  =   (R) total_count[14]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[13]  (KP<--)(REP)  =   (R) total_count[13]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[12]  (KP<--)(REP)  =   (R) total_count[12]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[11]  (KP<--)(REP)  =   (R) total_count[11]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[10]  (KP<--)(REP)  =   (R) total_count[10]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[9]  (KP<--)(REP)  =   (R) total_count[9]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[8]  (KP<--)(REP)  =   (R) total_count[8]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[7]  (KP<--)(REP)  =   (R) total_count[7]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[6]  (KP<--)(REP)  =   (R) total_count[6]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[5]  (KP<--)(REP)  =   (R) total_count[5]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[4]  (KP<--)(REP)  =   (R) total_count[4]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[3]  (KP<--)(REP)  =   (R) total_count[3]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[2]  (KP<--)(REP)  =   (R) total_count[2]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[1]  (KP<--)(REP)  =   (R) total_count[1]  (KP<--)(REP) (by sim and name)
# OUT (G) total_count[0]  (KP<--)(REP)  =   (R) total_count[0]  (KP<--)(REP) (by sim and name)
set_root_module prbs_ber_top -Golden
set_root_module prbs_ber_top_mapped -Revised
set_module_property -instance /u_prbs_ber_chip_top/u_prbs_ber_top -Golden
set_module_property -instance /u_prbs_ber_chip_top/u_prbs_ber_top -Revised
# Constraint commands 
add_output_equivalences prbs_out ref_bit -hier -Golden
add_ignored_outputs ref_bit -Golden -System
# (EQ)
add_output_stuck_at 0 ref_bit -Revised -hier
add_ignored_outputs ref_bit -Revised -System
# UR stuck_at
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
add_black_box prbs_ber_top -module -hier -Golden
add_black_box prbs_ber_top_mapped -module -hier -Revised
usage
# Comparing
#-------------------------------------------------------------------------------
# MODULE prbs_ber_chip_top (G) INSTANCE /u_prbs_ber_chip_top (G)
# MODULE prbs_ber_chip_top_mapped (R) INSTANCE /u_prbs_ber_chip_top (R)
# Wrapper size: (G) = 64  (R) = 95
# Periphery size: (G) = 2560  (R) = 2295
# Pins directly connected to key-points/constants: (G) = 58.97%  (R) = 58.97%
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk  (KP<--)(REP)  =   (R) clk  (KP<--)(REP) (by sim and name)
# IN (G) rst_n  (KP<--)(REP)  =   (R) rst_n  (KP<--)(REP) (by sim and name)
# IN (G) ext_serial_in  (KP<--)(REP)  =   (R) ext_serial_in  (KP<--)(REP) (by sim and name)
# IN (G) cfg_we  (KP<--)(REP)  =   (R) cfg_we  (KP<--)(REP) (by sim and name)
# IN (G) cfg_re  (KP<--)(REP)  =   (R) cfg_re  (KP<--)(REP) (by sim and name)
# IN (G) cfg_addr[4]  (KP<--)(REP)  =   (R) cfg_addr[4]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_addr[3]  (KP<--)(REP)  =   (R) cfg_addr[3]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_addr[2]  (KP<--)(REP)  =   (R) cfg_addr[2]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_addr[1]  (KP<--)(REP)  =   (R) cfg_addr[1]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_addr[0]  (KP<--)(REP)  =   (R) cfg_addr[0]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[31]  (KP<--)(REP)  =   (R) cfg_wdata[31]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[30]  (KP<--)(REP)  =   (R) cfg_wdata[30]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[29]  (KP<--)(REP)  =   (R) cfg_wdata[29]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[28]  (KP<--)(REP)  =   (R) cfg_wdata[28]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[27]  (KP<--)(REP)  =   (R) cfg_wdata[27]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[26]  (KP<--)(REP)  =   (R) cfg_wdata[26]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[25]  (KP<--)(REP)  =   (R) cfg_wdata[25]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[24]  (KP<--)(REP)  =   (R) cfg_wdata[24]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[23]  (KP<--)(REP)  =   (R) cfg_wdata[23]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[22]  (KP<--)(REP)  =   (R) cfg_wdata[22]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[21]  (KP<--)(REP)  =   (R) cfg_wdata[21]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[20]  (KP<--)(REP)  =   (R) cfg_wdata[20]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[19]  (KP<--)(REP)  =   (R) cfg_wdata[19]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[18]  (KP<--)(REP)  =   (R) cfg_wdata[18]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[17]  (KP<--)(REP)  =   (R) cfg_wdata[17]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[16]  (KP<--)(REP)  =   (R) cfg_wdata[16]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[15]  (KP<--)(REP)  =   (R) cfg_wdata[15]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[14]  (KP<--)(REP)  =   (R) cfg_wdata[14]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[13]  (KP<--)(REP)  =   (R) cfg_wdata[13]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[12]  (KP<--)(REP)  =   (R) cfg_wdata[12]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[11]  (KP<--)(REP)  =   (R) cfg_wdata[11]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[10]  (KP<--)(REP)  =   (R) cfg_wdata[10]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[9]  (KP<--)(REP)  =   (R) cfg_wdata[9]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[8]  (KP<--)(REP)  =   (R) cfg_wdata[8]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[7]  (KP<--)(REP)  =   (R) cfg_wdata[7]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[6]  (KP<--)(REP)  =   (R) cfg_wdata[6]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[5]  (KP<--)(REP)  =   (R) cfg_wdata[5]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[4]  (KP<--)(REP)  =   (R) cfg_wdata[4]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[3]  (KP<--)(REP)  =   (R) cfg_wdata[3]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[2]  (KP<--)(REP)  =   (R) cfg_wdata[2]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[1]  (KP<--)(REP)  =   (R) cfg_wdata[1]  (KP<--)(REP) (by sim and name)
# IN (G) cfg_wdata[0]  (KP<--)(REP)  =   (R) cfg_wdata[0]  (KP<--)(REP) (by sim and name)
# RESOLVED Constraints
# OUT (G) cfg_rdata[31] (REP)  =   (R) cfg_rdata[31] (REP) (by sim and name)
# OUT (G) cfg_rdata[30] (REP)  =   (R) cfg_rdata[30] (REP) (by sim and name)
# OUT (G) cfg_rdata[29] (REP)  =   (R) cfg_rdata[29] (REP) (by sim and name)
# OUT (G) cfg_rdata[28] (REP)  =   (R) cfg_rdata[28] (REP) (by sim and name)
# OUT (G) cfg_rdata[27] (REP)  =   (R) cfg_rdata[27] (REP) (by sim and name)
# OUT (G) cfg_rdata[26] (REP)  =   (R) cfg_rdata[26] (REP) (by sim and name)
# OUT (G) cfg_rdata[25] (REP)  =   (R) cfg_rdata[25] (REP) (by sim and name)
# OUT (G) cfg_rdata[24] (REP)  =   (R) cfg_rdata[24] (REP) (by sim and name)
# OUT (G) cfg_rdata[23] (REP)  =   (R) cfg_rdata[23] (REP) (by sim and name)
# OUT (G) cfg_rdata[22] (REP)  =   (R) cfg_rdata[22] (REP) (by sim and name)
# OUT (G) cfg_rdata[21] (REP)  =   (R) cfg_rdata[21] (REP) (by sim and name)
# OUT (G) cfg_rdata[20] (REP)  =   (R) cfg_rdata[20] (REP) (by sim and name)
# OUT (G) cfg_rdata[19] (REP)  =   (R) cfg_rdata[19] (REP) (by sim and name)
# OUT (G) cfg_rdata[18] (REP)  =   (R) cfg_rdata[18] (REP) (by sim and name)
# OUT (G) cfg_rdata[17] (REP)  =   (R) cfg_rdata[17] (REP) (by sim and name)
# OUT (G) cfg_rdata[16] (REP)  =   (R) cfg_rdata[16] (REP) (by sim and name)
# OUT (G) cfg_rdata[15] (REP)  =   (R) cfg_rdata[15] (REP) (by sim and name)
# OUT (G) cfg_rdata[14] (REP)  =   (R) cfg_rdata[14] (REP) (by sim and name)
# OUT (G) cfg_rdata[13] (REP)  =   (R) cfg_rdata[13] (REP) (by sim and name)
# OUT (G) cfg_rdata[12] (REP)  =   (R) cfg_rdata[12] (REP) (by sim and name)
# OUT (G) cfg_rdata[11] (REP)  =   (R) cfg_rdata[11] (REP) (by sim and name)
# OUT (G) cfg_rdata[10] (REP)  =   (R) cfg_rdata[10] (REP) (by sim and name)
# OUT (G) cfg_rdata[9] (REP)  =   (R) cfg_rdata[9] (REP) (by sim and name)
# OUT (G) cfg_rdata[8] (REP)  =   (R) cfg_rdata[8] (REP) (by sim and name)
# OUT (G) cfg_rdata[7] (REP)  =   (R) cfg_rdata[7] (REP) (by sim and name)
# OUT (G) cfg_rdata[6] (REP)  =   (R) cfg_rdata[6] (REP) (by sim and name)
# OUT (G) cfg_rdata[5] (REP)  =   (R) cfg_rdata[5] (REP) (by sim and name)
# OUT (G) cfg_rdata[4] (REP)  =   (R) cfg_rdata[4] (REP) (by sim and name)
# OUT (G) cfg_rdata[3] (REP)  =   (R) cfg_rdata[3] (REP) (by sim and name)
# OUT (G) cfg_rdata[2] (REP)  =   (R) cfg_rdata[2] (REP) (by sim and name)
# OUT (G) cfg_rdata[1] (REP)  =   (R) cfg_rdata[1] (REP) (by sim and name)
# OUT (G) cfg_rdata[0] (REP)  =   (R) cfg_rdata[0] (REP) (by sim and name)
# OUT (G) busy  (KP<--)(REP)  =   (R) busy  (KP<--)(REP) (by sim and name)
# OUT (G) done  (KP<--)(REP)  =   (R) done  (KP<--)(REP) (by sim and name)
# OUT (G) prbs_out  (-->KP)(REP)  =   (R) prbs_out  (-->KP)(REP) (by sim and name)
# OUT (G) bit_error  (-->KP)(REP)  =   (R) bit_error  (-->KP)(REP) (by name)
set_root_module prbs_ber_chip_top -Golden
set_root_module prbs_ber_chip_top_mapped -Revised
set_module_property -instance /u_prbs_ber_chip_top -Golden
set_module_property -instance /u_prbs_ber_chip_top -Revised
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
add_black_box prbs_ber_chip_top -module -hier -Golden
add_black_box prbs_ber_chip_top_mapped -module -hier -Revised
usage
# Root Modules
# Comparing
#-------------------------------------------------------------------------------
# MODULE prbs_ber_pad_top (G) INSTANCE / (G)
# MODULE prbs_ber_pad_top (R) INSTANCE / (R)
# Wrapper size: (G) = 0  (R) = 0
# Periphery size: (G) = 0  (R) = 0
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk (REP)  =   (R) clk (REP) (by name)
# IN (G) rst_n (REP)  =   (R) rst_n (REP) (by name)
# IN (G) ext_serial_in (REP)  =   (R) ext_serial_in (REP) (by name)
# IN (G) cfg_sclk (REP)  =   (R) cfg_sclk (REP) (by name)
# IN (G) cfg_cs_n (REP)  =   (R) cfg_cs_n (REP) (by name)
# IN (G) cfg_mosi (REP)  =   (R) cfg_mosi (REP) (by name)
# RESOLVED Constraints
# OUT (G) cfg_miso (REP)  =   (R) cfg_miso (REP) (by name)
# OUT (G) busy (REP)  =   (R) busy (REP) (by name)
# OUT (G) done (REP)  =   (R) done (REP) (by name)
# OUT (G) prbs_out (REP)  =   (R) prbs_out (REP) (by name)
# OUT (G) bit_error (REP)  =   (R) bit_error (REP) (by name)
set_root_module prbs_ber_pad_top -Golden
set_root_module prbs_ber_pad_top -Revised
set_module_property -instance / -Golden
set_module_property -instance / -Revised
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
usage
report_hier_compare_result
report_hier_compare_result -Nonequivalent
report_hier_compare_result -Abort
report_hier_compare_result -Uncompared
#-------------------------------------------------------------------------------
# VERBOSE REPORTING
#-------------------------------------------------------------------------------
# The following module pairs are not written because of number of primitive
# instances less than 50:
# prbs_ctrl_LFSR_W7_DEFAULT_SEED1, prim-cnt = 10 (G) and prbs_ctrl_LFSR_W7_DEFAULT_SEED1_mapped, prim-cnt = 12 (R)
# prbs15_ctrl_LFSR_W15_DEFAULT_SEED1, prim-cnt = 18 (G) and prbs15_ctrl_LFSR_W15_DEFAULT_SEED1_mapped, prim-cnt = 23 (R)
#-------------------------------------------------------------------------------
# The following module pairs are not written because of mismatched ports:
# Module Pair: measure_ctrl (G) and measure_ctrl_mapped (R)
# Cause for mismatched ports is pin constants and unreachables
# OUT (G) busy  (KP<--)(REP)  =    (R) busy 0U(REP) 
#-------------------------------------------------------------------------------
# _END_OF_LEC_HIERARCHICAL_DOFILE_
