catch {set_db port:prbs15_top/clk .original_name clk}
catch {set_db port:prbs15_top/rst_n .original_name rst_n}
catch {set_db port:prbs15_top/en .original_name en}
catch {set_db port:prbs15_top/seed_load .original_name seed_load}
catch {set_db {port:prbs15_top/seed_in[14]} .original_name {seed_in[14]}}
catch {set_db {port:prbs15_top/seed_in[13]} .original_name {seed_in[13]}}
catch {set_db {port:prbs15_top/seed_in[12]} .original_name {seed_in[12]}}
catch {set_db {port:prbs15_top/seed_in[11]} .original_name {seed_in[11]}}
catch {set_db {port:prbs15_top/seed_in[10]} .original_name {seed_in[10]}}
catch {set_db {port:prbs15_top/seed_in[9]} .original_name {seed_in[9]}}
catch {set_db {port:prbs15_top/seed_in[8]} .original_name {seed_in[8]}}
catch {set_db {port:prbs15_top/seed_in[7]} .original_name {seed_in[7]}}
catch {set_db {port:prbs15_top/seed_in[6]} .original_name {seed_in[6]}}
catch {set_db {port:prbs15_top/seed_in[5]} .original_name {seed_in[5]}}
catch {set_db {port:prbs15_top/seed_in[4]} .original_name {seed_in[4]}}
catch {set_db {port:prbs15_top/seed_in[3]} .original_name {seed_in[3]}}
catch {set_db {port:prbs15_top/seed_in[2]} .original_name {seed_in[2]}}
catch {set_db {port:prbs15_top/seed_in[1]} .original_name {seed_in[1]}}
catch {set_db {port:prbs15_top/seed_in[0]} .original_name {seed_in[0]}}
catch {set_db port:prbs15_top/prbs_out .original_name prbs_out}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[14]/Q} .original_name {u_prbs15_core/lfsr_q[14]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[13]/Q} .original_name {u_prbs15_core/lfsr_q[13]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[12]/Q} .original_name {u_prbs15_core/lfsr_q[12]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[11]/Q} .original_name {u_prbs15_core/lfsr_q[11]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[10]/Q} .original_name {u_prbs15_core/lfsr_q[10]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[9]/Q} .original_name {u_prbs15_core/lfsr_q[9]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[8]/Q} .original_name {u_prbs15_core/lfsr_q[8]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[7]/Q} .original_name {u_prbs15_core/lfsr_q[7]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[6]/Q} .original_name {u_prbs15_core/lfsr_q[6]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[5]/Q} .original_name {u_prbs15_core/lfsr_q[5]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[4]/Q} .original_name {u_prbs15_core/lfsr_q[4]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[3]/Q} .original_name {u_prbs15_core/lfsr_q[3]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[2]/Q} .original_name {u_prbs15_core/lfsr_q[2]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[1]/Q} .original_name {u_prbs15_core/lfsr_q[1]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[0]/Q} .original_name {u_prbs15_core/lfsr_q[0]/q}}
catch {set_db {pin:prbs15_top/u_prbs15_core/lfsr_q_reg[0]/QN} .original_name {u_prbs15_core/lfsr_q[0]/q}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[14]} .original_name {{u_prbs15_core/lfsr_q[14]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[13]} .original_name {{u_prbs15_core/lfsr_q[13]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[12]} .original_name {{u_prbs15_core/lfsr_q[12]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[11]} .original_name {{u_prbs15_core/lfsr_q[11]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[10]} .original_name {{u_prbs15_core/lfsr_q[10]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[9]} .original_name {{u_prbs15_core/lfsr_q[9]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[8]} .original_name {{u_prbs15_core/lfsr_q[8]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[7]} .original_name {{u_prbs15_core/lfsr_q[7]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[6]} .original_name {{u_prbs15_core/lfsr_q[6]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[5]} .original_name {{u_prbs15_core/lfsr_q[5]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[4]} .original_name {{u_prbs15_core/lfsr_q[4]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[3]} .original_name {{u_prbs15_core/lfsr_q[3]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[2]} .original_name {{u_prbs15_core/lfsr_q[2]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[1]} .original_name {{u_prbs15_core/lfsr_q[1]}}}
catch {set_db {inst:prbs15_top/u_prbs15_core/lfsr_q_reg[0]} .original_name {{u_prbs15_core/lfsr_q[0]}}}
