###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID eeapps03.labidm.seas.ucla.edu)
#  Generated on:      Fri Apr 24 20:03:23 2026
#  Design:            prbs_ber_pad_top
#  Command:           write_db pre_innovus_snap_floorplan
###############################################################
current_design prbs_ber_pad_top
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {clk}]  -name clk -period 4.000000 -waveform {0.000000 2.000000}
set_load -pin_load -max  0.005  [get_ports {cfg_miso}]
set_load -pin_load -min  0.005  [get_ports {cfg_miso}]
set_load -pin_load -max  0.005  [get_ports {busy}]
set_load -pin_load -min  0.005  [get_ports {busy}]
set_load -pin_load -max  0.005  [get_ports {done}]
set_load -pin_load -min  0.005  [get_ports {done}]
set_load -pin_load -max  0.005  [get_ports {prbs_out}]
set_load -pin_load -min  0.005  [get_ports {prbs_out}]
set_load -pin_load -max  0.005  [get_ports {bit_error}]
set_load -pin_load -min  0.005  [get_ports {bit_error}]
set_clock_groups -name clock_groups_clk_to_others -asynchronous  -group  [get_clocks {clk}]
