/*
###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID eeapps03.labidm.seas.ucla.edu)
#  Generated on:      Sat Apr 11 12:05:20 2026
#  Design:            prbs_ber_top
#  Command:           write_netlist /w/home.09/home/liyuyao864/ee209/prbs_project/build_prbs_ber/par-rundir/prbs_ber_top.sim.v -top_module_first -top_module prbs_ber_top -exclude_leaf_cells -exclude_insts_of_cells { TAPCELLBWP7T FILL1BWP7T FILL2BWP7T FILL4BWP7T FILL8BWP7T FILL16BWP7T FILL32BWP7T FILL64BWP7T PCORNER PFILLER20 PFILLER10 PFILLER5 PFILLER1 PFILLER05 PFILLER0005 PAD50LAU_TRL PAD60LAU_TRL PAD60LU_TRL }
###############################################################
*/
module prbs_ber_top (
	clk, 
	rst_n, 
	en, 
	clear_count, 
	seed_load, 
	mode_select, 
	seed_in, 
	input_select, 
	inject_error_enable, 
	ext_serial_in, 
	prbs_out, 
	checker_in, 
	checker_in_final, 
	ref_bit, 
	bit_error, 
	error_count, 
	total_count);
   input clk;
   input rst_n;
   input en;
   input clear_count;
   input seed_load;
   input mode_select;
   input [14:0] seed_in;
   input input_select;
   input inject_error_enable;
   input ext_serial_in;
   output prbs_out;
   output checker_in;
   output checker_in_final;
   output ref_bit;
   output bit_error;
   output [31:0] error_count;
   output [31:0] total_count;

   // Internal wires
   wire FE_PHN25_clear_count;
   wire FE_PHN20_clear_count;
   wire FE_PHN19_clear_count;
   wire FE_PHN3_rst_n;
   wire CTS_7;
   wire CTS_6;
   wire CTS_10;
   wire CTS_9;
   wire CTS_8;
   wire CTS_2;
   wire CTS_1;
   wire CTS_5;
   wire CTS_4;
   wire CTS_3;
   wire FE_OFN19_rst_n;
   wire inc_add_80_40_n_0;
   wire inc_add_80_40_n_1;
   wire inc_add_80_40_n_2;
   wire inc_add_80_40_n_3;
   wire inc_add_80_40_n_4;
   wire inc_add_80_40_n_5;
   wire inc_add_80_40_n_6;
   wire inc_add_80_40_n_7;
   wire inc_add_80_40_n_9;
   wire inc_add_80_40_n_10;
   wire inc_add_80_40_n_11;
   wire inc_add_80_40_n_12;
   wire inc_add_80_40_n_13;
   wire inc_add_80_40_n_14;
   wire inc_add_80_40_n_15;
   wire inc_add_80_40_n_16;
   wire inc_add_80_40_n_18;
   wire inc_add_80_40_n_19;
   wire inc_add_80_40_n_20;
   wire inc_add_80_40_n_23;
   wire inc_add_80_40_n_24;
   wire inc_add_80_40_n_27;
   wire inc_add_80_40_n_28;
   wire inc_add_80_40_n_29;
   wire inc_add_80_40_n_32;
   wire inc_add_80_40_n_33;
   wire inc_add_80_40_n_34;
   wire inc_add_80_40_n_36;
   wire inc_add_80_40_n_37;
   wire inc_add_80_40_n_39;
   wire inc_add_80_40_n_42;
   wire inc_add_80_40_n_43;
   wire inc_add_80_40_n_45;
   wire inc_add_80_40_n_48;
   wire inc_add_80_40_n_49;
   wire inc_add_80_40_n_51;
   wire inc_add_80_40_n_54;
   wire inc_add_80_40_n_56;
   wire inc_add_80_40_n_60;
   wire inc_add_80_40_n_62;
   wire inc_add_80_40_n_65;
   wire inc_add_80_40_n_69;
   wire inc_add_82_44_n_0;
   wire inc_add_82_44_n_1;
   wire inc_add_82_44_n_2;
   wire inc_add_82_44_n_3;
   wire inc_add_82_44_n_4;
   wire inc_add_82_44_n_5;
   wire inc_add_82_44_n_6;
   wire inc_add_82_44_n_7;
   wire inc_add_82_44_n_9;
   wire inc_add_82_44_n_10;
   wire inc_add_82_44_n_11;
   wire inc_add_82_44_n_12;
   wire inc_add_82_44_n_13;
   wire inc_add_82_44_n_14;
   wire inc_add_82_44_n_15;
   wire inc_add_82_44_n_16;
   wire inc_add_82_44_n_18;
   wire inc_add_82_44_n_19;
   wire inc_add_82_44_n_20;
   wire inc_add_82_44_n_23;
   wire inc_add_82_44_n_24;
   wire inc_add_82_44_n_27;
   wire inc_add_82_44_n_28;
   wire inc_add_82_44_n_29;
   wire inc_add_82_44_n_32;
   wire inc_add_82_44_n_33;
   wire inc_add_82_44_n_34;
   wire inc_add_82_44_n_36;
   wire inc_add_82_44_n_37;
   wire inc_add_82_44_n_39;
   wire inc_add_82_44_n_42;
   wire inc_add_82_44_n_43;
   wire inc_add_82_44_n_45;
   wire inc_add_82_44_n_48;
   wire inc_add_82_44_n_49;
   wire inc_add_82_44_n_51;
   wire inc_add_82_44_n_54;
   wire inc_add_82_44_n_56;
   wire inc_add_82_44_n_60;
   wire inc_add_82_44_n_62;
   wire inc_add_82_44_n_65;
   wire inc_add_82_44_n_69;
   wire logic_0_1_net;
   wire logic_0_2_net;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;

   assign ref_bit = prbs_out ;

   DEL0BWP7T FE_PHC25_clear_count (.I(clear_count),
	.Z(FE_PHN25_clear_count));
   BUFFD1P5BWP7T FE_PHC20_clear_count (.I(clear_count),
	.Z(FE_PHN20_clear_count));
   BUFFD4BWP7T FE_PHC19_clear_count (.I(clear_count),
	.Z(FE_PHN19_clear_count));
   BUFFD1P5BWP7T FE_PHC3_rst_n (.I(rst_n),
	.Z(FE_PHN3_rst_n));
   CKBD2BWP7T CTS_ccl_a_buf_00010 (.I(CTS_7),
	.Z(CTS_6));
   CKBD2BWP7T CTS_ccl_a_buf_00009 (.I(CTS_7),
	.Z(CTS_10));
   CKBD2BWP7T CTS_ccl_a_buf_00008 (.I(CTS_7),
	.Z(CTS_9));
   CKBD2BWP7T CTS_ccl_a_buf_00007 (.I(CTS_7),
	.Z(CTS_8));
   CKBD2BWP7T CTS_ccl_a_buf_00006 (.I(CTS_2),
	.Z(CTS_1));
   CKBD2BWP7T CTS_ccl_a_buf_00005 (.I(CTS_2),
	.Z(CTS_5));
   CKBD3BWP7T CTS_ccl_a_buf_00004 (.I(CTS_2),
	.Z(CTS_4));
   CKBD2BWP7T CTS_ccl_a_buf_00003 (.I(CTS_2),
	.Z(CTS_3));
   BUFFD1BWP7T FE_OFC2_rst_n (.I(rst_n),
	.Z(FE_OFN19_rst_n));
   CKND1BWP7T FE_OFC1_add_82_44_n_18 (.I(inc_add_82_44_n_18),
	.ZN(inc_add_82_44_n_19));
   CLKGATE_RC_CG_MOD_mapped CLKGATE_RC_CG_HIER_INST0 (.enable(n_69),
	.ck_in(clk),
	.ck_out(CTS_7),
	.test(logic_0_1_net));
   CLKGATE_RC_CG_MOD_1_mapped CLKGATE_RC_CG_HIER_INST1 (.enable(n_68),
	.ck_in(clk),
	.ck_out(CTS_2),
	.test(logic_0_2_net));
   prbs_gen_top_mapped u_prbs_gen_top (.clk(clk),
	.rst_n(rst_n),
	.en(en),
	.seed_load(seed_load),
	.mode_select(mode_select),
	.seed_in(seed_in),
	.prbs_out(prbs_out),
	.p1(FE_PHN3_rst_n));
   OR2D1BWP7T g646__8246 (.A1(bit_error),
	.A2(n_64),
	.Z(n_69));
   CKAN2D1BWP7T g647__7098 (.A1(n_65),
	.A2(en),
	.Z(bit_error));
   CKXOR2D1BWP7T g648__6131 (.A1(checker_in_final),
	.A2(prbs_out),
	.Z(n_65));
   CKXOR2D1BWP7T g649__1881 (.A1(checker_in),
	.A2(inject_error_enable),
	.Z(checker_in_final));
   OR2D0BWP7T g650__5115 (.A1(n_64),
	.A2(en),
	.Z(n_68));
   CKMUX2D1BWP7T g651__7482 (.I0(prbs_out),
	.I1(ext_serial_in),
	.S(input_select),
	.Z(checker_in));
   IND2D0BWP7T g652__4733 (.A1(clear_count),
	.B1(rst_n),
	.ZN(n_64));
   DFKCNQD1BWP7T \error_count_reg[0]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_9),
	.D(n_53),
	.Q(error_count[0]));
   DFKCNQD1BWP7T \error_count_reg[1]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_9),
	.D(n_51),
	.Q(error_count[1]));
   DFKCNQD1BWP7T \error_count_reg[2]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_9),
	.D(n_13),
	.Q(error_count[2]));
   DFKCNQD1BWP7T \error_count_reg[3]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_9),
	.D(n_25),
	.Q(error_count[3]));
   DFKCNQD1BWP7T \error_count_reg[4]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_63),
	.Q(error_count[4]));
   DFKCNQD1BWP7T \error_count_reg[5]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_54),
	.Q(error_count[5]));
   DFKCNQD1BWP7T \error_count_reg[6]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_40),
	.Q(error_count[6]));
   DFKCNQD1BWP7T \error_count_reg[7]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_36),
	.Q(error_count[7]));
   DFKCNQD1BWP7T \error_count_reg[8]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_41),
	.Q(error_count[8]));
   DFKCNQD1BWP7T \error_count_reg[9]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_37),
	.Q(error_count[9]));
   DFKCNQD1BWP7T \error_count_reg[10]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_38),
	.Q(error_count[10]));
   DFKCNQD1BWP7T \error_count_reg[11]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_35),
	.Q(error_count[11]));
   DFKCNQD1BWP7T \error_count_reg[12]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_34),
	.Q(error_count[12]));
   DFKCNQD1BWP7T \error_count_reg[13]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_33),
	.Q(error_count[13]));
   DFKCNQD1BWP7T \error_count_reg[14]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_42),
	.Q(error_count[14]));
   DFKCNQD1BWP7T \error_count_reg[15]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_30),
	.Q(error_count[15]));
   DFKCNQD1BWP7T \error_count_reg[16]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_29),
	.Q(error_count[16]));
   DFKCNQD1BWP7T \error_count_reg[17]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_27),
	.Q(error_count[17]));
   DFKCNQD1BWP7T \error_count_reg[18]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_26),
	.Q(error_count[18]));
   DFKCNQD1BWP7T \error_count_reg[19]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_24),
	.Q(error_count[19]));
   DFKCNQD1BWP7T \error_count_reg[20]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_22),
	.Q(error_count[20]));
   DFKCNQD1BWP7T \error_count_reg[21]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_23),
	.Q(error_count[21]));
   DFKCNQD1BWP7T \error_count_reg[22]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_21),
	.Q(error_count[22]));
   DFKCNQD1BWP7T \error_count_reg[23]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_18),
	.Q(error_count[23]));
   DFKCNQD1BWP7T \error_count_reg[24]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_9),
	.D(n_17),
	.Q(error_count[24]));
   DFKCNQD1BWP7T \error_count_reg[25]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_9),
	.D(n_16),
	.Q(error_count[25]));
   DFKCNQD1BWP7T \error_count_reg[26]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_9),
	.D(n_31),
	.Q(error_count[26]));
   DFKCNQD1BWP7T \error_count_reg[27]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_9),
	.D(n_20),
	.Q(error_count[27]));
   DFKCNQD1BWP7T \error_count_reg[28]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_12),
	.Q(error_count[28]));
   DFKCNQD1BWP7T \error_count_reg[29]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_11),
	.Q(error_count[29]));
   DFKCNQD1BWP7T \error_count_reg[30]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_15),
	.Q(error_count[30]));
   DFKCNQD1BWP7T \error_count_reg[31]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_9),
	.Q(error_count[31]));
   DFKCNQD1BWP7T \total_count_reg[0]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_8),
	.Q(total_count[0]));
   DFKCNQD1BWP7T \total_count_reg[1]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_7),
	.Q(total_count[1]));
   DFKCNQD1BWP7T \total_count_reg[2]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_6),
	.Q(total_count[2]));
   DFKCNQD1BWP7T \total_count_reg[3]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_5),
	.Q(total_count[3]));
   DFKCNQD1BWP7T \total_count_reg[4]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_4),
	.Q(total_count[4]));
   DFKCNQD1BWP7T \total_count_reg[5]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_3),
	.Q(total_count[5]));
   DFKCNQD1BWP7T \total_count_reg[6]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_2),
	.Q(total_count[6]));
   DFKCNQD1BWP7T \total_count_reg[7]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_1),
	.Q(total_count[7]));
   DFKCNQD1BWP7T \total_count_reg[8]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_0),
	.Q(total_count[8]));
   DFKCNQD1BWP7T \total_count_reg[9]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_1),
	.D(n_62),
	.Q(total_count[9]));
   DFKCNQD1BWP7T \total_count_reg[10]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_1),
	.D(n_61),
	.Q(total_count[10]));
   DFKCNQD1BWP7T \total_count_reg[11]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_1),
	.D(n_58),
	.Q(total_count[11]));
   DFKCNQD1BWP7T \total_count_reg[12]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_1),
	.D(n_57),
	.Q(total_count[12]));
   DFKCNQD1BWP7T \total_count_reg[13]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_1),
	.D(n_56),
	.Q(total_count[13]));
   DFKCNQD1BWP7T \total_count_reg[14]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_55),
	.Q(total_count[14]));
   DFKCNQD1BWP7T \total_count_reg[15]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_52),
	.Q(total_count[15]));
   DFKCNQD1BWP7T \total_count_reg[16]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_10),
	.Q(total_count[16]));
   DFKCNQD1BWP7T \total_count_reg[17]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_19),
	.Q(total_count[17]));
   DFKCNQD1BWP7T \total_count_reg[18]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_47),
	.Q(total_count[18]));
   DFKCNQD1BWP7T \total_count_reg[19]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_28),
	.Q(total_count[19]));
   DFKCNQD1BWP7T \total_count_reg[20]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_49),
	.Q(total_count[20]));
   DFKCNQD1BWP7T \total_count_reg[21]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_32),
	.Q(total_count[21]));
   DFKCNQD1BWP7T \total_count_reg[22]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_46),
	.Q(total_count[22]));
   DFKCNQD1BWP7T \total_count_reg[23]  (.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_44),
	.Q(total_count[23]));
   DFKCNQD1BWP7T \total_count_reg[24]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_39),
	.Q(total_count[24]));
   DFKCNQD1BWP7T \total_count_reg[25]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_43),
	.Q(total_count[25]));
   DFKCNQD1BWP7T \total_count_reg[26]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_48),
	.Q(total_count[26]));
   DFKCNQD1BWP7T \total_count_reg[27]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_45),
	.Q(total_count[27]));
   DFKCNQD1BWP7T \total_count_reg[28]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_60),
	.Q(total_count[28]));
   DFKCNQD1BWP7T \total_count_reg[29]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_50),
	.Q(total_count[29]));
   DFKCNQD1BWP7T \total_count_reg[30]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_14),
	.Q(total_count[30]));
   DFKCNQD1BWP7T \total_count_reg[31]  (.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_59),
	.Q(total_count[31]));
   INR2D1BWP7T g1110__6161 (.A1(n_104),
	.B1(FE_PHN19_clear_count),
	.ZN(n_63));
   INR2D1BWP7T g1111__9315 (.A1(n_78),
	.B1(FE_PHN19_clear_count),
	.ZN(n_62));
   INR2D1BWP7T g1112__9945 (.A1(n_79),
	.B1(FE_PHN19_clear_count),
	.ZN(n_61));
   INR2D1BWP7T g1113__2883 (.A1(n_97),
	.B1(FE_PHN20_clear_count),
	.ZN(n_60));
   INR2D1BWP7T g1114__2346 (.A1(n_100),
	.B1(FE_PHN20_clear_count),
	.ZN(n_59));
   INR2D1BWP7T g1115__1666 (.A1(n_80),
	.B1(FE_PHN19_clear_count),
	.ZN(n_58));
   INR2D1BWP7T g1116__7410 (.A1(n_81),
	.B1(FE_PHN19_clear_count),
	.ZN(n_57));
   INR2D1BWP7T g1117__6417 (.A1(n_82),
	.B1(FE_PHN19_clear_count),
	.ZN(n_56));
   INR2D1BWP7T g1118__5477 (.A1(n_83),
	.B1(FE_PHN19_clear_count),
	.ZN(n_55));
   INR2D1BWP7T g1119__2398 (.A1(n_105),
	.B1(FE_PHN19_clear_count),
	.ZN(n_54));
   NR2XD0BWP7T g1120__5107 (.A1(error_count[0]),
	.A2(FE_PHN20_clear_count),
	.ZN(n_53));
   INR2D1BWP7T g1121__6260 (.A1(n_84),
	.B1(FE_PHN19_clear_count),
	.ZN(n_52));
   INR2D1BWP7T g1122__4319 (.A1(n_101),
	.B1(FE_PHN20_clear_count),
	.ZN(n_51));
   INR2D1BWP7T g1123__8428 (.A1(n_98),
	.B1(FE_PHN20_clear_count),
	.ZN(n_50));
   INR2D1BWP7T g1124__5526 (.A1(n_89),
	.B1(FE_PHN19_clear_count),
	.ZN(n_49));
   INR2D1BWP7T g1125__6783 (.A1(n_95),
	.B1(FE_PHN20_clear_count),
	.ZN(n_48));
   INR2D1BWP7T g1126__3680 (.A1(n_87),
	.B1(FE_PHN19_clear_count),
	.ZN(n_47));
   INR2D1BWP7T g1127__1617 (.A1(n_91),
	.B1(FE_PHN19_clear_count),
	.ZN(n_46));
   INR2D1BWP7T g1128__2802 (.A1(n_96),
	.B1(FE_PHN20_clear_count),
	.ZN(n_45));
   INR2D1BWP7T g1129__1705 (.A1(n_92),
	.B1(FE_PHN19_clear_count),
	.ZN(n_44));
   INR2D1BWP7T g1130__5122 (.A1(n_94),
	.B1(FE_PHN20_clear_count),
	.ZN(n_43));
   INR2D1BWP7T g1131__8246 (.A1(n_114),
	.B1(FE_PHN19_clear_count),
	.ZN(n_42));
   INR2D1BWP7T g1132__7098 (.A1(n_108),
	.B1(FE_PHN19_clear_count),
	.ZN(n_41));
   INR2D1BWP7T g1133__6131 (.A1(n_106),
	.B1(FE_PHN19_clear_count),
	.ZN(n_40));
   INR2D1BWP7T g1134__1881 (.A1(n_93),
	.B1(FE_PHN20_clear_count),
	.ZN(n_39));
   INR2D1BWP7T g1135__5115 (.A1(n_110),
	.B1(FE_PHN19_clear_count),
	.ZN(n_38));
   INR2D1BWP7T g1136__7482 (.A1(n_109),
	.B1(FE_PHN19_clear_count),
	.ZN(n_37));
   INR2D1BWP7T g1137__4733 (.A1(n_107),
	.B1(FE_PHN19_clear_count),
	.ZN(n_36));
   INR2D1BWP7T g1138__6161 (.A1(n_111),
	.B1(FE_PHN19_clear_count),
	.ZN(n_35));
   INR2D1BWP7T g1139__9315 (.A1(n_112),
	.B1(FE_PHN19_clear_count),
	.ZN(n_34));
   INR2D1BWP7T g1140__9945 (.A1(n_113),
	.B1(FE_PHN19_clear_count),
	.ZN(n_33));
   INR2D1BWP7T g1141__2883 (.A1(n_90),
	.B1(FE_PHN19_clear_count),
	.ZN(n_32));
   INR2D1BWP7T g1142__2346 (.A1(n_126),
	.B1(FE_PHN20_clear_count),
	.ZN(n_31));
   INR2D1BWP7T g1143__1666 (.A1(n_115),
	.B1(FE_PHN19_clear_count),
	.ZN(n_30));
   INR2D1BWP7T g1144__7410 (.A1(n_116),
	.B1(FE_PHN20_clear_count),
	.ZN(n_29));
   INR2D1BWP7T g1145__6417 (.A1(n_88),
	.B1(FE_PHN19_clear_count),
	.ZN(n_28));
   INR2D1BWP7T g1146__5477 (.A1(n_117),
	.B1(FE_PHN20_clear_count),
	.ZN(n_27));
   INR2D1BWP7T g1147__2398 (.A1(n_118),
	.B1(FE_PHN20_clear_count),
	.ZN(n_26));
   INR2D1BWP7T g1148__5107 (.A1(n_103),
	.B1(FE_PHN20_clear_count),
	.ZN(n_25));
   INR2D1BWP7T g1149__6260 (.A1(n_119),
	.B1(FE_PHN20_clear_count),
	.ZN(n_24));
   INR2D1BWP7T g1150__4319 (.A1(n_121),
	.B1(FE_PHN20_clear_count),
	.ZN(n_23));
   INR2D1BWP7T g1151__8428 (.A1(n_120),
	.B1(FE_PHN20_clear_count),
	.ZN(n_22));
   INR2D1BWP7T g1152__5526 (.A1(n_122),
	.B1(FE_PHN20_clear_count),
	.ZN(n_21));
   INR2D1BWP7T g1153__6783 (.A1(n_127),
	.B1(FE_PHN25_clear_count),
	.ZN(n_20));
   INR2D1BWP7T g1154__3680 (.A1(n_86),
	.B1(FE_PHN19_clear_count),
	.ZN(n_19));
   INR2D1BWP7T g1155__1617 (.A1(n_123),
	.B1(FE_PHN20_clear_count),
	.ZN(n_18));
   INR2D1BWP7T g1156__2802 (.A1(n_124),
	.B1(FE_PHN20_clear_count),
	.ZN(n_17));
   INR2D1BWP7T g1157__1705 (.A1(n_125),
	.B1(FE_PHN20_clear_count),
	.ZN(n_16));
   INR2D1BWP7T g1158__5122 (.A1(n_130),
	.B1(FE_PHN19_clear_count),
	.ZN(n_15));
   INR2D1BWP7T g1159__8246 (.A1(n_99),
	.B1(FE_PHN20_clear_count),
	.ZN(n_14));
   INR2D1BWP7T g1160__7098 (.A1(n_102),
	.B1(FE_PHN20_clear_count),
	.ZN(n_13));
   INR2D1BWP7T g1161__6131 (.A1(n_128),
	.B1(FE_PHN19_clear_count),
	.ZN(n_12));
   INR2D1BWP7T g1162__1881 (.A1(n_129),
	.B1(FE_PHN19_clear_count),
	.ZN(n_11));
   INR2D1BWP7T g1163__5115 (.A1(n_85),
	.B1(FE_PHN19_clear_count),
	.ZN(n_10));
   INR2D1BWP7T g1164__7482 (.A1(n_131),
	.B1(FE_PHN19_clear_count),
	.ZN(n_9));
   NR2XD0BWP7T g1165__4733 (.A1(total_count[0]),
	.A2(FE_PHN20_clear_count),
	.ZN(n_8));
   INR2D1BWP7T g1166__6161 (.A1(n_70),
	.B1(FE_PHN20_clear_count),
	.ZN(n_7));
   INR2D1BWP7T g1167__9315 (.A1(n_71),
	.B1(FE_PHN20_clear_count),
	.ZN(n_6));
   INR2D1BWP7T g1168__9945 (.A1(n_72),
	.B1(FE_PHN20_clear_count),
	.ZN(n_5));
   INR2D1BWP7T g1169__2883 (.A1(n_73),
	.B1(FE_PHN20_clear_count),
	.ZN(n_4));
   INR2D1BWP7T g1170__2346 (.A1(n_74),
	.B1(FE_PHN20_clear_count),
	.ZN(n_3));
   INR2D1BWP7T g1171__1666 (.A1(n_75),
	.B1(FE_PHN20_clear_count),
	.ZN(n_2));
   INR2D1BWP7T g1172__7410 (.A1(n_76),
	.B1(FE_PHN20_clear_count),
	.ZN(n_1));
   INR2D1BWP7T g1173__6417 (.A1(n_77),
	.B1(FE_PHN19_clear_count),
	.ZN(n_0));
   CKXOR2D1BWP7T inc_add_80_40_g479__5477 (.A1(inc_add_80_40_n_69),
	.A2(total_count[19]),
	.Z(n_88));
   XOR2D1BWP7T inc_add_80_40_g480__2398 (.A1(inc_add_80_40_n_65),
	.A2(total_count[31]),
	.Z(n_100));
   HA1D0BWP7T inc_add_80_40_g481__5107 (.A(total_count[18]),
	.B(inc_add_80_40_n_56),
	.CO(inc_add_80_40_n_69),
	.S(n_87));
   CKXOR2D1BWP7T inc_add_80_40_g482__6260 (.A1(inc_add_80_40_n_62),
	.A2(total_count[29]),
	.Z(n_98));
   CKXOR2D1BWP7T inc_add_80_40_g483__4319 (.A1(inc_add_80_40_n_60),
	.A2(total_count[11]),
	.Z(n_80));
   HA1D1BWP7T inc_add_80_40_g484__8428 (.A(total_count[30]),
	.B(inc_add_80_40_n_48),
	.CO(inc_add_80_40_n_65),
	.S(n_99));
   CKXOR2D1BWP7T inc_add_80_40_g485__5526 (.A1(inc_add_80_40_n_54),
	.A2(total_count[27]),
	.Z(n_96));
   HA1D0BWP7T inc_add_80_40_g486__6783 (.A(total_count[28]),
	.B(inc_add_80_40_n_42),
	.CO(inc_add_80_40_n_62),
	.S(n_97));
   HA1D0BWP7T inc_add_80_40_g487__3680 (.A(total_count[10]),
	.B(inc_add_80_40_n_43),
	.CO(inc_add_80_40_n_60),
	.S(n_79));
   CKXOR2D1BWP7T inc_add_80_40_g488__1617 (.A1(inc_add_80_40_n_51),
	.A2(total_count[25]),
	.Z(n_94));
   CKXOR2D1BWP7T inc_add_80_40_g489__2802 (.A1(inc_add_80_40_n_49),
	.A2(total_count[23]),
	.Z(n_92));
   HA1D0BWP7T inc_add_80_40_g490__1705 (.A(total_count[17]),
	.B(inc_add_80_40_n_39),
	.CO(inc_add_80_40_n_56),
	.S(n_86));
   HA1D0BWP7T inc_add_80_40_g491__5122 (.A(total_count[26]),
	.B(inc_add_80_40_n_36),
	.CO(inc_add_80_40_n_54),
	.S(n_95));
   CKXOR2D1BWP7T inc_add_80_40_g492__8246 (.A1(inc_add_80_40_n_45),
	.A2(total_count[21]),
	.Z(n_90));
   HA1D0BWP7T inc_add_80_40_g493__7098 (.A(total_count[24]),
	.B(inc_add_80_40_n_32),
	.CO(inc_add_80_40_n_51),
	.S(n_93));
   HA1D0BWP7T inc_add_80_40_g494__6131 (.A(total_count[22]),
	.B(inc_add_80_40_n_33),
	.CO(inc_add_80_40_n_49),
	.S(n_91));
   AN3XD1BWP7T inc_add_80_40_g495__1881 (.A1(inc_add_80_40_n_42),
	.A2(total_count[29]),
	.A3(total_count[28]),
	.Z(inc_add_80_40_n_48));
   CKXOR2D1BWP7T inc_add_80_40_g496__5115 (.A1(inc_add_80_40_n_37),
	.A2(total_count[15]),
	.Z(n_84));
   HA1D0BWP7T inc_add_80_40_g497__7482 (.A(total_count[20]),
	.B(inc_add_80_40_n_28),
	.CO(inc_add_80_40_n_45),
	.S(n_89));
   HA1D0BWP7T inc_add_80_40_g498__4733 (.A(total_count[9]),
	.B(inc_add_80_40_n_29),
	.CO(inc_add_80_40_n_43),
	.S(n_78));
   AN3D2BWP7T inc_add_80_40_g499__6161 (.A1(inc_add_80_40_n_36),
	.A2(total_count[27]),
	.A3(total_count[26]),
	.Z(inc_add_80_40_n_42));
   CKXOR2D1BWP7T inc_add_80_40_g500__9315 (.A1(inc_add_80_40_n_34),
	.A2(total_count[13]),
	.Z(n_82));
   HA1D0BWP7T inc_add_80_40_g501__9945 (.A(total_count[16]),
	.B(inc_add_80_40_n_0),
	.CO(inc_add_80_40_n_39),
	.S(n_85));
   HA1D0BWP7T inc_add_80_40_g502__2883 (.A(total_count[14]),
	.B(inc_add_80_40_n_23),
	.CO(inc_add_80_40_n_37),
	.S(n_83));
   AN3D1BWP7T inc_add_80_40_g503__2346 (.A1(inc_add_80_40_n_32),
	.A2(total_count[25]),
	.A3(total_count[24]),
	.Z(inc_add_80_40_n_36));
   HA1D0BWP7T inc_add_80_40_g504__1666 (.A(total_count[12]),
	.B(inc_add_80_40_n_19),
	.CO(inc_add_80_40_n_34),
	.S(n_81));
   CKAN2D1BWP7T inc_add_80_40_g505__7410 (.A1(inc_add_80_40_n_28),
	.A2(inc_add_80_40_n_4),
	.Z(inc_add_80_40_n_33));
   NR2XD3BWP7T inc_add_80_40_g506__6417 (.A1(inc_add_80_40_n_27),
	.A2(inc_add_80_40_n_9),
	.ZN(inc_add_80_40_n_32));
   CKXOR2D1BWP7T inc_add_80_40_g507__5477 (.A1(inc_add_80_40_n_24),
	.A2(total_count[7]),
	.Z(n_76));
   HA1D0BWP7T inc_add_80_40_g508__2398 (.A(total_count[8]),
	.B(inc_add_80_40_n_15),
	.CO(inc_add_80_40_n_29),
	.S(n_77));
   INVD1BWP7T inc_add_80_40_g509 (.I(inc_add_80_40_n_27),
	.ZN(inc_add_80_40_n_28));
   ND2D1BWP7T inc_add_80_40_g510__5107 (.A1(inc_add_80_40_n_0),
	.A2(inc_add_80_40_n_6),
	.ZN(inc_add_80_40_n_27));
   CKXOR2D1BWP7T inc_add_80_40_g511__6260 (.A1(inc_add_80_40_n_20),
	.A2(total_count[5]),
	.Z(n_74));
   HA1D0BWP7T inc_add_80_40_g512__4319 (.A(total_count[6]),
	.B(inc_add_80_40_n_14),
	.CO(inc_add_80_40_n_24),
	.S(n_75));
   INR2XD0BWP7T inc_add_80_40_g513__8428 (.A1(inc_add_80_40_n_19),
	.B1(inc_add_80_40_n_2),
	.ZN(inc_add_80_40_n_23));
   NR2XD1BWP7T inc_add_80_40_g515__5526 (.A1(inc_add_80_40_n_18),
	.A2(inc_add_80_40_n_10),
	.ZN(inc_add_80_40_n_0));
   CKXOR2D1BWP7T inc_add_80_40_g516__6783 (.A1(inc_add_80_40_n_16),
	.A2(total_count[3]),
	.Z(n_72));
   HA1D0BWP7T inc_add_80_40_g517__3680 (.A(total_count[4]),
	.B(inc_add_80_40_n_12),
	.CO(inc_add_80_40_n_20),
	.S(n_73));
   INVD1BWP7T inc_add_80_40_g518 (.I(inc_add_80_40_n_18),
	.ZN(inc_add_80_40_n_19));
   ND2D2BWP7T inc_add_80_40_g519__1617 (.A1(inc_add_80_40_n_15),
	.A2(inc_add_80_40_n_7),
	.ZN(inc_add_80_40_n_18));
   HA1D0BWP7T inc_add_80_40_g520__2802 (.A(total_count[2]),
	.B(inc_add_80_40_n_11),
	.CO(inc_add_80_40_n_16),
	.S(n_71));
   NR2D3BWP7T inc_add_80_40_g521__1705 (.A1(inc_add_80_40_n_13),
	.A2(inc_add_80_40_n_3),
	.ZN(inc_add_80_40_n_15));
   INVD1BWP7T inc_add_80_40_g522 (.I(inc_add_80_40_n_13),
	.ZN(inc_add_80_40_n_14));
   ND3D2BWP7T inc_add_80_40_g523__5122 (.A1(inc_add_80_40_n_12),
	.A2(total_count[5]),
	.A3(total_count[4]),
	.ZN(inc_add_80_40_n_13));
   NR2D1BWP7T inc_add_80_40_g524__8246 (.A1(inc_add_80_40_n_1),
	.A2(inc_add_80_40_n_5),
	.ZN(inc_add_80_40_n_12));
   INVD1BWP7T inc_add_80_40_g525 (.I(inc_add_80_40_n_1),
	.ZN(inc_add_80_40_n_11));
   IND3D1BWP7T inc_add_80_40_g526__7098 (.A1(inc_add_80_40_n_2),
	.B1(total_count[15]),
	.B2(total_count[14]),
	.ZN(inc_add_80_40_n_10));
   ND3D0BWP7T inc_add_80_40_g527__6131 (.A1(inc_add_80_40_n_4),
	.A2(total_count[23]),
	.A3(total_count[22]),
	.ZN(inc_add_80_40_n_9));
   OA21D0BWP7T inc_add_80_40_g528__1881 (.A1(total_count[0]),
	.A2(total_count[1]),
	.B(inc_add_80_40_n_1),
	.Z(n_70));
   AN4D0BWP7T inc_add_80_40_g529__5115 (.A1(total_count[11]),
	.A2(total_count[10]),
	.A3(total_count[9]),
	.A4(total_count[8]),
	.Z(inc_add_80_40_n_7));
   AN4D0BWP7T inc_add_80_40_g530__7482 (.A1(total_count[19]),
	.A2(total_count[18]),
	.A3(total_count[17]),
	.A4(total_count[16]),
	.Z(inc_add_80_40_n_6));
   ND2D1BWP7T inc_add_80_40_g531__4733 (.A1(total_count[3]),
	.A2(total_count[2]),
	.ZN(inc_add_80_40_n_5));
   CKAN2D1BWP7T inc_add_80_40_g532__6161 (.A1(total_count[21]),
	.A2(total_count[20]),
	.Z(inc_add_80_40_n_4));
   ND2D1BWP7T inc_add_80_40_g533__9315 (.A1(total_count[7]),
	.A2(total_count[6]),
	.ZN(inc_add_80_40_n_3));
   ND2D1BWP7T inc_add_80_40_g534__9945 (.A1(total_count[13]),
	.A2(total_count[12]),
	.ZN(inc_add_80_40_n_2));
   ND2D1BWP7T inc_add_80_40_g535__2883 (.A1(total_count[1]),
	.A2(total_count[0]),
	.ZN(inc_add_80_40_n_1));
   CKXOR2D1BWP7T inc_add_82_44_g479__2346 (.A1(inc_add_82_44_n_69),
	.A2(error_count[19]),
	.Z(n_119));
   XOR2D1BWP7T inc_add_82_44_g480__1666 (.A1(inc_add_82_44_n_65),
	.A2(error_count[31]),
	.Z(n_131));
   HA1D0BWP7T inc_add_82_44_g481__7410 (.A(error_count[18]),
	.B(inc_add_82_44_n_56),
	.CO(inc_add_82_44_n_69),
	.S(n_118));
   CKXOR2D1BWP7T inc_add_82_44_g482__6417 (.A1(inc_add_82_44_n_62),
	.A2(error_count[29]),
	.Z(n_129));
   CKXOR2D1BWP7T inc_add_82_44_g483__5477 (.A1(inc_add_82_44_n_60),
	.A2(error_count[11]),
	.Z(n_111));
   HA1D1BWP7T inc_add_82_44_g484__2398 (.A(error_count[30]),
	.B(inc_add_82_44_n_48),
	.CO(inc_add_82_44_n_65),
	.S(n_130));
   CKXOR2D1BWP7T inc_add_82_44_g485__5107 (.A1(inc_add_82_44_n_54),
	.A2(error_count[27]),
	.Z(n_127));
   HA1D0BWP7T inc_add_82_44_g486__6260 (.A(error_count[28]),
	.B(inc_add_82_44_n_42),
	.CO(inc_add_82_44_n_62),
	.S(n_128));
   HA1D0BWP7T inc_add_82_44_g487__4319 (.A(error_count[10]),
	.B(inc_add_82_44_n_43),
	.CO(inc_add_82_44_n_60),
	.S(n_110));
   CKXOR2D1BWP7T inc_add_82_44_g488__8428 (.A1(inc_add_82_44_n_51),
	.A2(error_count[25]),
	.Z(n_125));
   CKXOR2D1BWP7T inc_add_82_44_g489__5526 (.A1(inc_add_82_44_n_49),
	.A2(error_count[23]),
	.Z(n_123));
   HA1D0BWP7T inc_add_82_44_g490__6783 (.A(error_count[17]),
	.B(inc_add_82_44_n_39),
	.CO(inc_add_82_44_n_56),
	.S(n_117));
   HA1D0BWP7T inc_add_82_44_g491__3680 (.A(error_count[26]),
	.B(inc_add_82_44_n_36),
	.CO(inc_add_82_44_n_54),
	.S(n_126));
   CKXOR2D1BWP7T inc_add_82_44_g492__1617 (.A1(inc_add_82_44_n_45),
	.A2(error_count[21]),
	.Z(n_121));
   HA1D0BWP7T inc_add_82_44_g493__2802 (.A(error_count[24]),
	.B(inc_add_82_44_n_32),
	.CO(inc_add_82_44_n_51),
	.S(n_124));
   HA1D0BWP7T inc_add_82_44_g494__1705 (.A(error_count[22]),
	.B(inc_add_82_44_n_33),
	.CO(inc_add_82_44_n_49),
	.S(n_122));
   AN3XD1BWP7T inc_add_82_44_g495__5122 (.A1(inc_add_82_44_n_42),
	.A2(error_count[29]),
	.A3(error_count[28]),
	.Z(inc_add_82_44_n_48));
   CKXOR2D1BWP7T inc_add_82_44_g496__8246 (.A1(inc_add_82_44_n_37),
	.A2(error_count[15]),
	.Z(n_115));
   HA1D0BWP7T inc_add_82_44_g497__7098 (.A(error_count[20]),
	.B(inc_add_82_44_n_28),
	.CO(inc_add_82_44_n_45),
	.S(n_120));
   HA1D0BWP7T inc_add_82_44_g498__6131 (.A(error_count[9]),
	.B(inc_add_82_44_n_29),
	.CO(inc_add_82_44_n_43),
	.S(n_109));
   AN3D2BWP7T inc_add_82_44_g499__1881 (.A1(inc_add_82_44_n_36),
	.A2(error_count[27]),
	.A3(error_count[26]),
	.Z(inc_add_82_44_n_42));
   CKXOR2D1BWP7T inc_add_82_44_g500__5115 (.A1(inc_add_82_44_n_34),
	.A2(error_count[13]),
	.Z(n_113));
   HA1D0BWP7T inc_add_82_44_g501__7482 (.A(error_count[16]),
	.B(inc_add_82_44_n_0),
	.CO(inc_add_82_44_n_39),
	.S(n_116));
   HA1D0BWP7T inc_add_82_44_g502__4733 (.A(error_count[14]),
	.B(inc_add_82_44_n_23),
	.CO(inc_add_82_44_n_37),
	.S(n_114));
   AN3D1BWP7T inc_add_82_44_g503__6161 (.A1(inc_add_82_44_n_32),
	.A2(error_count[25]),
	.A3(error_count[24]),
	.Z(inc_add_82_44_n_36));
   HA1D0BWP7T inc_add_82_44_g504__9315 (.A(error_count[12]),
	.B(inc_add_82_44_n_19),
	.CO(inc_add_82_44_n_34),
	.S(n_112));
   CKAN2D1BWP7T inc_add_82_44_g505__9945 (.A1(inc_add_82_44_n_28),
	.A2(inc_add_82_44_n_4),
	.Z(inc_add_82_44_n_33));
   NR2XD2BWP7T inc_add_82_44_g506__2883 (.A1(inc_add_82_44_n_27),
	.A2(inc_add_82_44_n_9),
	.ZN(inc_add_82_44_n_32));
   CKXOR2D1BWP7T inc_add_82_44_g507__2346 (.A1(inc_add_82_44_n_24),
	.A2(error_count[7]),
	.Z(n_107));
   HA1D0BWP7T inc_add_82_44_g508__1666 (.A(error_count[8]),
	.B(inc_add_82_44_n_15),
	.CO(inc_add_82_44_n_29),
	.S(n_108));
   INVD1BWP7T inc_add_82_44_g509 (.I(inc_add_82_44_n_27),
	.ZN(inc_add_82_44_n_28));
   ND2D1BWP7T inc_add_82_44_g510__7410 (.A1(inc_add_82_44_n_0),
	.A2(inc_add_82_44_n_6),
	.ZN(inc_add_82_44_n_27));
   CKXOR2D1BWP7T inc_add_82_44_g511__6417 (.A1(inc_add_82_44_n_20),
	.A2(error_count[5]),
	.Z(n_105));
   HA1D0BWP7T inc_add_82_44_g512__5477 (.A(error_count[6]),
	.B(inc_add_82_44_n_14),
	.CO(inc_add_82_44_n_24),
	.S(n_106));
   INR2XD0BWP7T inc_add_82_44_g513__2398 (.A1(inc_add_82_44_n_19),
	.B1(inc_add_82_44_n_2),
	.ZN(inc_add_82_44_n_23));
   NR2XD2BWP7T inc_add_82_44_g515__5107 (.A1(inc_add_82_44_n_18),
	.A2(inc_add_82_44_n_10),
	.ZN(inc_add_82_44_n_0));
   CKXOR2D1BWP7T inc_add_82_44_g516__6260 (.A1(inc_add_82_44_n_16),
	.A2(error_count[3]),
	.Z(n_103));
   HA1D0BWP7T inc_add_82_44_g517__4319 (.A(error_count[4]),
	.B(inc_add_82_44_n_12),
	.CO(inc_add_82_44_n_20),
	.S(n_104));
   ND2D1BWP7T inc_add_82_44_g519__8428 (.A1(inc_add_82_44_n_15),
	.A2(inc_add_82_44_n_7),
	.ZN(inc_add_82_44_n_18));
   HA1D0BWP7T inc_add_82_44_g520__5526 (.A(error_count[2]),
	.B(inc_add_82_44_n_11),
	.CO(inc_add_82_44_n_16),
	.S(n_102));
   NR2XD1BWP7T inc_add_82_44_g521__6783 (.A1(inc_add_82_44_n_13),
	.A2(inc_add_82_44_n_3),
	.ZN(inc_add_82_44_n_15));
   INVD1BWP7T inc_add_82_44_g522 (.I(inc_add_82_44_n_13),
	.ZN(inc_add_82_44_n_14));
   ND3D1BWP7T inc_add_82_44_g523__3680 (.A1(inc_add_82_44_n_12),
	.A2(error_count[5]),
	.A3(error_count[4]),
	.ZN(inc_add_82_44_n_13));
   NR2D2BWP7T inc_add_82_44_g524__1617 (.A1(inc_add_82_44_n_1),
	.A2(inc_add_82_44_n_5),
	.ZN(inc_add_82_44_n_12));
   INVD1BWP7T inc_add_82_44_g525 (.I(inc_add_82_44_n_1),
	.ZN(inc_add_82_44_n_11));
   IND3D1BWP7T inc_add_82_44_g526__2802 (.A1(inc_add_82_44_n_2),
	.B1(error_count[15]),
	.B2(error_count[14]),
	.ZN(inc_add_82_44_n_10));
   ND3D0BWP7T inc_add_82_44_g527__1705 (.A1(inc_add_82_44_n_4),
	.A2(error_count[23]),
	.A3(error_count[22]),
	.ZN(inc_add_82_44_n_9));
   OA21D0BWP7T inc_add_82_44_g528__5122 (.A1(error_count[0]),
	.A2(error_count[1]),
	.B(inc_add_82_44_n_1),
	.Z(n_101));
   AN4D0BWP7T inc_add_82_44_g529__8246 (.A1(error_count[11]),
	.A2(error_count[10]),
	.A3(error_count[9]),
	.A4(error_count[8]),
	.Z(inc_add_82_44_n_7));
   AN4D0BWP7T inc_add_82_44_g530__7098 (.A1(error_count[19]),
	.A2(error_count[18]),
	.A3(error_count[17]),
	.A4(error_count[16]),
	.Z(inc_add_82_44_n_6));
   ND2D1BWP7T inc_add_82_44_g531__6131 (.A1(error_count[3]),
	.A2(error_count[2]),
	.ZN(inc_add_82_44_n_5));
   CKAN2D1BWP7T inc_add_82_44_g532__1881 (.A1(error_count[21]),
	.A2(error_count[20]),
	.Z(inc_add_82_44_n_4));
   ND2D1BWP7T inc_add_82_44_g533__5115 (.A1(error_count[7]),
	.A2(error_count[6]),
	.ZN(inc_add_82_44_n_3));
   ND2D1BWP7T inc_add_82_44_g534__7482 (.A1(error_count[13]),
	.A2(error_count[12]),
	.ZN(inc_add_82_44_n_2));
   ND2D1BWP7T inc_add_82_44_g535__4733 (.A1(error_count[1]),
	.A2(error_count[0]),
	.ZN(inc_add_82_44_n_1));
   TIELBWP7T tie_0_cell (.ZN(logic_0_1_net));
   TIELBWP7T tie_0_cell1 (.ZN(logic_0_2_net));
endmodule

// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Apr 11 2026 11:58:41 PDT (Apr 11 2026 18:58:41 UTC)
// Verification Directory fv/prbs_ber_top 
module CLKGATE_RC_CG_MOD_mapped (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD6BWP7T RC_CGIC_INST (.CP(ck_in),
	.E(enable),
	.Q(ck_out),
	.TE(test));
endmodule

module CLKGATE_RC_CG_MOD_1_mapped (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD4BWP7T RC_CGIC_INST (.CP(ck_in),
	.E(enable),
	.Q(ck_out),
	.TE(test));
endmodule

module CLKGATE_RC_CG_MOD_2_mapped (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1BWP7T RC_CGIC_INST (.CP(ck_in),
	.E(enable),
	.Q(ck_out),
	.TE(test));
endmodule

module prbs_core_LFSR_W7_DEFAULT_SEED1_mapped (
	clk, 
	rst_n, 
	load_req, 
	seed_value, 
	step_en, 
	prbs_out, 
	state_out, 
	p1);
   input clk;
   input rst_n;
   input load_req;
   input [6:0] seed_value;
   input step_en;
   output prbs_out;
   output [6:0] state_out;
   input p1;

   // Internal wires
   wire FE_PHN23_seed_in_2;
   wire FE_PHN22_seed_in_1;
   wire FE_PHN21_seed_in_6;
   wire [6:0] lfsr_q;
   wire CLKGATE_rc_gclk;
   wire UNCONNECTED;
   wire logic_0_1_net;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_10;

   DEL01BWP7T FE_PHC23_seed_in_2 (.I(seed_value[2]),
	.Z(FE_PHN23_seed_in_2));
   DEL01BWP7T FE_PHC22_seed_in_1 (.I(seed_value[1]),
	.Z(FE_PHN22_seed_in_1));
   DEL01BWP7T FE_PHC21_seed_in_6 (.I(seed_value[6]),
	.Z(FE_PHN21_seed_in_6));
   CLKGATE_RC_CG_MOD_2_mapped CLKGATE_RC_CG_HIER_INST2 (.enable(n_10),
	.ck_in(clk),
	.ck_out(CLKGATE_rc_gclk),
	.test(logic_0_1_net));
   DFKCNQD1BWP7T \lfsr_q_reg[4]  (.CN(p1),
	.CP(CLKGATE_rc_gclk),
	.D(n_8),
	.Q(lfsr_q[4]));
   CKMUX2D1BWP7T g161__2398 (.I0(lfsr_q[3]),
	.I1(seed_value[4]),
	.S(load_req),
	.Z(n_8));
   DFKCNQD1BWP7T \lfsr_q_reg[3]  (.CN(p1),
	.CP(CLKGATE_rc_gclk),
	.D(n_7),
	.Q(lfsr_q[3]));
   CKMUX2D1BWP7T g163__5107 (.I0(lfsr_q[2]),
	.I1(seed_value[3]),
	.S(load_req),
	.Z(n_7));
   DFKCNQD1BWP7T \lfsr_q_reg[2]  (.CN(p1),
	.CP(CLKGATE_rc_gclk),
	.D(n_6),
	.Q(lfsr_q[2]));
   CKMUX2D1BWP7T g165__6260 (.I0(lfsr_q[1]),
	.I1(FE_PHN23_seed_in_2),
	.S(load_req),
	.Z(n_6));
   DFKCNQD1BWP7T \lfsr_q_reg[1]  (.CN(p1),
	.CP(CLKGATE_rc_gclk),
	.D(n_5),
	.Q(lfsr_q[1]));
   IND3D0BWP7T g167__4319 (.A1(step_en),
	.B1(rst_n),
	.B2(n_4),
	.ZN(n_10));
   CKMUX2D1BWP7T g168__8428 (.I0(lfsr_q[0]),
	.I1(FE_PHN22_seed_in_1),
	.S(load_req),
	.Z(n_5));
   INVD0BWP7T g169 (.I(load_req),
	.ZN(n_4));
   DFKSND1BWP7T \lfsr_q_reg[0]  (.CP(CLKGATE_rc_gclk),
	.D(n_3),
	.Q(lfsr_q[0]),
	.QN(UNCONNECTED),
	.SN(p1));
   CKMUX2D1BWP7T g135__5526 (.I0(n_2),
	.I1(seed_value[0]),
	.S(load_req),
	.Z(n_3));
   CKXOR2D1BWP7T g136__6783 (.A1(lfsr_q[5]),
	.A2(prbs_out),
	.Z(n_2));
   DFKCNQD1BWP7T \lfsr_q_reg[5]  (.CN(p1),
	.CP(CLKGATE_rc_gclk),
	.D(n_1),
	.Q(lfsr_q[5]));
   DFKCNQD1BWP7T \lfsr_q_reg[6]  (.CN(p1),
	.CP(CLKGATE_rc_gclk),
	.D(n_0),
	.Q(prbs_out));
   CKMUX2D1BWP7T g138__3680 (.I0(lfsr_q[4]),
	.I1(seed_value[5]),
	.S(load_req),
	.Z(n_1));
   CKMUX2D1BWP7T g139__1617 (.I0(lfsr_q[5]),
	.I1(FE_PHN21_seed_in_6),
	.S(load_req),
	.Z(n_0));
   TIELBWP7T tie_0_cell (.ZN(logic_0_1_net));
endmodule

module prbs_ctrl_LFSR_W7_DEFAULT_SEED1_mapped (
	seed_load, 
	seed_in, 
	en, 
	load_req, 
	seed_value, 
	step_en);
   input seed_load;
   input [6:0] seed_in;
   input en;
   output load_req;
   output [6:0] seed_value;
   output step_en;

   // Internal wires
   wire n_1;
   wire n_2;

   AO21D0BWP7T g69__2802 (.A1(n_2),
	.A2(n_1),
	.B(seed_in[0]),
	.Z(seed_value[0]));
   NR4D0BWP7T g70__1705 (.A1(seed_in[6]),
	.A2(seed_in[5]),
	.A3(seed_in[4]),
	.A4(seed_in[3]),
	.ZN(n_2));
   NR2D0BWP7T g71__5122 (.A1(seed_in[2]),
	.A2(seed_in[1]),
	.ZN(n_1));
endmodule

module prbs_top_mapped (
	clk, 
	rst_n, 
	en, 
	seed_load, 
	seed_in, 
	prbs_out, 
	p1, 
	p2, 
	p3, 
	p4);
   input clk;
   input rst_n;
   input en;
   input seed_load;
   input [6:0] seed_in;
   output prbs_out;
   input p1;
   input p2;
   input p3;
   input p4;

   // Internal wires
   wire [6:0] seed_value;
   wire [6:0] prbs_state;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire logic_0_1_net;
   wire logic_0_2_net;

   prbs_core_LFSR_W7_DEFAULT_SEED1_mapped u_prbs_core (.clk(clk),
	.rst_n(rst_n),
	.load_req(seed_load),
	.seed_value({ seed_in[6],
		p2,
		p3,
		p4,
		seed_in[2],
		seed_in[1],
		seed_value[0] }),
	.step_en(en),
	.prbs_out(prbs_out),
	.state_out(prbs_state),
	.p1(p1));
   prbs_ctrl_LFSR_W7_DEFAULT_SEED1_mapped u_prbs_ctrl (.seed_load(logic_0_2_net),
	.seed_in(seed_in),
	.en(logic_0_1_net),
	.load_req(UNCONNECTED0),
	.seed_value({ UNCONNECTED6,
		UNCONNECTED5,
		UNCONNECTED4,
		UNCONNECTED3,
		UNCONNECTED2,
		UNCONNECTED1,
		seed_value[0] }),
	.step_en(UNCONNECTED7));
endmodule

module CLKGATE_RC_CG_MOD_3_mapped (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   CKLNQD1BWP7T RC_CGIC_INST (.CP(ck_in),
	.E(enable),
	.Q(ck_out),
	.TE(test));
endmodule

module prbs15_core_LFSR_W15_DEFAULT_SEED1_mapped (
	clk, 
	rst_n, 
	load_req, 
	seed_value, 
	step_en, 
	prbs_out, 
	state_out, 
	p1);
   input clk;
   input rst_n;
   input load_req;
   input [14:0] seed_value;
   input step_en;
   output prbs_out;
   output [14:0] state_out;
   input p1;

   // Internal wires
   wire FE_PHN24_seed_in_3;
   wire FE_PHN17_seed_in_1;
   wire FE_PHN16_seed_in_6;
   wire FE_PHN15_seed_in_2;
   wire FE_PHN13_seed_in_13;
   wire FE_PHN12_seed_in_14;
   wire FE_PHN11_seed_in_7;
   wire FE_PHN10_seed_in_11;
   wire FE_PHN9_seed_in_10;
   wire FE_PHN8_seed_in_9;
   wire FE_PHN7_seed_in_8;
   wire FE_PHN6_seed_in_12;
   wire CTS_3;
   wire CTS_2;
   wire CTS_1;
   wire [14:0] lfsr_q;
   wire UNCONNECTED8;
   wire logic_0_1_net;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_18;

   DEL015BWP7T FE_PHC24_seed_in_3 (.I(seed_value[3]),
	.Z(FE_PHN24_seed_in_3));
   DEL0BWP7T FE_PHC17_seed_in_1 (.I(seed_value[1]),
	.Z(FE_PHN17_seed_in_1));
   DEL0BWP7T FE_PHC16_seed_in_6 (.I(seed_value[6]),
	.Z(FE_PHN16_seed_in_6));
   DEL0BWP7T FE_PHC15_seed_in_2 (.I(seed_value[2]),
	.Z(FE_PHN15_seed_in_2));
   DEL0BWP7T FE_PHC13_seed_in_13 (.I(seed_value[13]),
	.Z(FE_PHN13_seed_in_13));
   DEL0BWP7T FE_PHC12_seed_in_14 (.I(seed_value[14]),
	.Z(FE_PHN12_seed_in_14));
   DEL0BWP7T FE_PHC11_seed_in_7 (.I(seed_value[7]),
	.Z(FE_PHN11_seed_in_7));
   DEL0BWP7T FE_PHC10_seed_in_11 (.I(seed_value[11]),
	.Z(FE_PHN10_seed_in_11));
   DEL0BWP7T FE_PHC9_seed_in_10 (.I(seed_value[10]),
	.Z(FE_PHN9_seed_in_10));
   DEL0BWP7T FE_PHC8_seed_in_9 (.I(seed_value[9]),
	.Z(FE_PHN8_seed_in_9));
   DEL0BWP7T FE_PHC7_seed_in_8 (.I(seed_value[8]),
	.Z(FE_PHN7_seed_in_8));
   DEL0BWP7T FE_PHC6_seed_in_12 (.I(seed_value[12]),
	.Z(FE_PHN6_seed_in_12));
   CKBD1BWP7T CTS_ccl_a_buf_00002 (.I(CTS_3),
	.Z(CTS_2));
   CKBD2BWP7T CTS_ccl_a_buf_00001 (.I(CTS_3),
	.Z(CTS_1));
   CLKGATE_RC_CG_MOD_3_mapped CLKGATE_RC_CG_HIER_INST3 (.enable(n_18),
	.ck_in(clk),
	.ck_out(CTS_3),
	.test(logic_0_1_net));
   DFKCNQD1BWP7T \lfsr_q_reg[12]  (.CN(p1),
	.CP(CTS_1),
	.D(n_16),
	.Q(lfsr_q[12]));
   CKMUX2D1BWP7T g308__8246 (.I0(lfsr_q[11]),
	.I1(FE_PHN6_seed_in_12),
	.S(load_req),
	.Z(n_16));
   DFKCNQD1BWP7T \lfsr_q_reg[11]  (.CN(p1),
	.CP(CTS_1),
	.D(n_15),
	.Q(lfsr_q[11]));
   CKMUX2D1BWP7T g310__7098 (.I0(lfsr_q[10]),
	.I1(FE_PHN10_seed_in_11),
	.S(load_req),
	.Z(n_15));
   DFKCNQD1BWP7T \lfsr_q_reg[10]  (.CN(p1),
	.CP(CTS_1),
	.D(n_14),
	.Q(lfsr_q[10]));
   CKMUX2D1BWP7T g312__6131 (.I0(lfsr_q[9]),
	.I1(FE_PHN9_seed_in_10),
	.S(load_req),
	.Z(n_14));
   DFKCNQD1BWP7T \lfsr_q_reg[9]  (.CN(p1),
	.CP(CTS_1),
	.D(n_13),
	.Q(lfsr_q[9]));
   CKMUX2D1BWP7T g314__1881 (.I0(lfsr_q[8]),
	.I1(FE_PHN8_seed_in_9),
	.S(load_req),
	.Z(n_13));
   DFKCNQD1BWP7T \lfsr_q_reg[8]  (.CN(p1),
	.CP(CTS_1),
	.D(n_12),
	.Q(lfsr_q[8]));
   CKMUX2D1BWP7T g316__5115 (.I0(lfsr_q[7]),
	.I1(FE_PHN7_seed_in_8),
	.S(load_req),
	.Z(n_12));
   DFKCNQD1BWP7T \lfsr_q_reg[7]  (.CN(p1),
	.CP(CTS_1),
	.D(n_11),
	.Q(lfsr_q[7]));
   CKMUX2D1BWP7T g318__7482 (.I0(lfsr_q[6]),
	.I1(FE_PHN11_seed_in_7),
	.S(load_req),
	.Z(n_11));
   DFKCNQD1BWP7T \lfsr_q_reg[6]  (.CN(p1),
	.CP(CTS_2),
	.D(n_10),
	.Q(lfsr_q[6]));
   CKMUX2D1BWP7T g320__4733 (.I0(lfsr_q[5]),
	.I1(FE_PHN16_seed_in_6),
	.S(load_req),
	.Z(n_10));
   DFKCNQD1BWP7T \lfsr_q_reg[5]  (.CN(p1),
	.CP(CTS_2),
	.D(n_9),
	.Q(lfsr_q[5]));
   CKMUX2D1BWP7T g322__6161 (.I0(lfsr_q[4]),
	.I1(seed_value[5]),
	.S(load_req),
	.Z(n_9));
   DFKCNQD1BWP7T \lfsr_q_reg[4]  (.CN(p1),
	.CP(CTS_2),
	.D(n_8),
	.Q(lfsr_q[4]));
   CKMUX2D1BWP7T g324__9315 (.I0(lfsr_q[3]),
	.I1(seed_value[4]),
	.S(load_req),
	.Z(n_8));
   DFKCNQD1BWP7T \lfsr_q_reg[3]  (.CN(p1),
	.CP(CTS_2),
	.D(n_7),
	.Q(lfsr_q[3]));
   CKMUX2D1BWP7T g326__9945 (.I0(lfsr_q[2]),
	.I1(FE_PHN24_seed_in_3),
	.S(load_req),
	.Z(n_7));
   DFKCNQD1BWP7T \lfsr_q_reg[2]  (.CN(p1),
	.CP(CTS_2),
	.D(n_6),
	.Q(lfsr_q[2]));
   CKMUX2D1BWP7T g328__2883 (.I0(lfsr_q[1]),
	.I1(FE_PHN15_seed_in_2),
	.S(load_req),
	.Z(n_6));
   DFKCNQD1BWP7T \lfsr_q_reg[1]  (.CN(p1),
	.CP(CTS_2),
	.D(n_5),
	.Q(lfsr_q[1]));
   IND3D0BWP7T g330__2346 (.A1(step_en),
	.B1(rst_n),
	.B2(n_4),
	.ZN(n_18));
   CKMUX2D1BWP7T g331__1666 (.I0(lfsr_q[0]),
	.I1(FE_PHN17_seed_in_1),
	.S(load_req),
	.Z(n_5));
   INVD1BWP7T g332 (.I(load_req),
	.ZN(n_4));
   DFKSND1BWP7T \lfsr_q_reg[0]  (.CP(CTS_2),
	.D(n_3),
	.Q(lfsr_q[0]),
	.QN(UNCONNECTED8),
	.SN(p1));
   CKMUX2D1BWP7T g215__7410 (.I0(n_2),
	.I1(seed_value[0]),
	.S(load_req),
	.Z(n_3));
   CKXOR2D1BWP7T g216__6417 (.A1(lfsr_q[13]),
	.A2(prbs_out),
	.Z(n_2));
   DFKCNQD1BWP7T \lfsr_q_reg[13]  (.CN(p1),
	.CP(CTS_1),
	.D(n_1),
	.Q(lfsr_q[13]));
   DFKCNQD1BWP7T \lfsr_q_reg[14]  (.CN(p1),
	.CP(CTS_1),
	.D(n_0),
	.Q(prbs_out));
   CKMUX2D1BWP7T g218__5477 (.I0(lfsr_q[12]),
	.I1(FE_PHN13_seed_in_13),
	.S(load_req),
	.Z(n_1));
   CKMUX2D1BWP7T g219__2398 (.I0(lfsr_q[13]),
	.I1(FE_PHN12_seed_in_14),
	.S(load_req),
	.Z(n_0));
   TIELBWP7T tie_0_cell (.ZN(logic_0_1_net));
endmodule

module prbs15_ctrl_LFSR_W15_DEFAULT_SEED1_mapped (
	seed_load, 
	seed_in, 
	en, 
	load_req, 
	seed_value, 
	step_en);
   input seed_load;
   input [14:0] seed_in;
   input en;
   output load_req;
   output [14:0] seed_value;
   output step_en;

   // Internal wires
   wire FE_PHN18_seed_in_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;

   DEL01BWP7T FE_PHC18_seed_in_0 (.I(seed_in[0]),
	.Z(FE_PHN18_seed_in_0));
   OR2D0BWP7T g261__5107 (.A1(n_5),
	.A2(FE_PHN18_seed_in_0),
	.Z(seed_value[0]));
   NR4D0BWP7T g262__6260 (.A1(n_4),
	.A2(seed_in[7]),
	.A3(seed_in[5]),
	.A4(seed_in[3]),
	.ZN(n_5));
   IND4D0BWP7T g263__4319 (.A1(seed_in[9]),
	.B1(n_1),
	.B2(n_3),
	.B3(n_2),
	.ZN(n_4));
   NR4D0BWP7T g264__8428 (.A1(seed_in[14]),
	.A2(seed_in[10]),
	.A3(seed_in[4]),
	.A4(seed_in[2]),
	.ZN(n_3));
   NR4D0BWP7T g265__5526 (.A1(seed_in[13]),
	.A2(seed_in[11]),
	.A3(seed_in[6]),
	.A4(seed_in[1]),
	.ZN(n_2));
   NR2D0BWP7T g266__6783 (.A1(seed_in[12]),
	.A2(seed_in[8]),
	.ZN(n_1));
endmodule

module prbs15_top_mapped (
	clk, 
	rst_n, 
	en, 
	seed_load, 
	seed_in, 
	prbs_out, 
	p1, 
	p2, 
	p3, 
	p4);
   input clk;
   input rst_n;
   input en;
   input seed_load;
   input [14:0] seed_in;
   output prbs_out;
   input p1;
   input p2;
   input p3;
   input p4;

   // Internal wires
   wire [14:0] seed_value;
   wire [14:0] prbs_state;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED14;
   wire UNCONNECTED15;
   wire UNCONNECTED16;
   wire UNCONNECTED17;
   wire UNCONNECTED18;
   wire UNCONNECTED19;
   wire UNCONNECTED20;
   wire UNCONNECTED21;
   wire UNCONNECTED22;
   wire UNCONNECTED23;
   wire UNCONNECTED24;
   wire logic_0_1_net;
   wire logic_0_2_net;

   prbs15_core_LFSR_W15_DEFAULT_SEED1_mapped u_prbs15_core (.clk(clk),
	.rst_n(rst_n),
	.load_req(seed_load),
	.seed_value({ seed_in[14],
		seed_in[13],
		seed_in[12],
		seed_in[11],
		seed_in[10],
		seed_in[9],
		seed_in[8],
		seed_in[7],
		seed_in[6],
		p2,
		p3,
		p4,
		seed_in[2],
		seed_in[1],
		seed_value[0] }),
	.step_en(en),
	.prbs_out(prbs_out),
	.state_out(prbs_state),
	.p1(p1));
   prbs15_ctrl_LFSR_W15_DEFAULT_SEED1_mapped u_prbs15_ctrl (.seed_load(logic_0_2_net),
	.seed_in(seed_in),
	.en(logic_0_1_net),
	.load_req(UNCONNECTED9),
	.seed_value({ UNCONNECTED23,
		UNCONNECTED22,
		UNCONNECTED21,
		UNCONNECTED20,
		UNCONNECTED19,
		UNCONNECTED18,
		UNCONNECTED17,
		UNCONNECTED16,
		UNCONNECTED15,
		UNCONNECTED14,
		UNCONNECTED13,
		UNCONNECTED12,
		UNCONNECTED11,
		UNCONNECTED10,
		seed_value[0] }),
	.step_en(UNCONNECTED24));
endmodule

module prbs_gen_top_mapped (
	clk, 
	rst_n, 
	en, 
	seed_load, 
	mode_select, 
	seed_in, 
	prbs_out, 
	p1);
   input clk;
   input rst_n;
   input en;
   input seed_load;
   input mode_select;
   input [14:0] seed_in;
   output prbs_out;
   input p1;

   // Internal wires
   wire FE_PHN14_seed_in_3;
   wire FE_PHN5_seed_in_4;
   wire FE_PHN4_seed_in_5;
   wire CTS_2;
   wire n_0;
   wire n_13;
   wire n_14;
   wire n_22;
   wire n_23;
   wire prbs7_out;
   wire prbs15_out;

   CKBD0BWP7T FE_PHC14_seed_in_3 (.I(seed_in[3]),
	.Z(FE_PHN14_seed_in_3));
   DEL02BWP7T FE_PHC5_seed_in_4 (.I(seed_in[4]),
	.Z(FE_PHN5_seed_in_4));
   DEL02BWP7T FE_PHC4_seed_in_5 (.I(seed_in[5]),
	.Z(FE_PHN4_seed_in_5));
   AO22D1BWP7T FE_RC_0_0 (.A1(mode_select),
	.A2(prbs15_out),
	.B1(n_0),
	.B2(prbs7_out),
	.Z(prbs_out));
   CKBD1BWP7T CTS_ccl_a_buf_00011 (.I(clk),
	.Z(CTS_2));
   prbs_top_mapped u_prbs7_top (.clk(CTS_2),
	.rst_n(rst_n),
	.en(n_23),
	.seed_load(n_22),
	.seed_in({ seed_in[6],
		seed_in[5],
		seed_in[4],
		seed_in[3],
		seed_in[2],
		seed_in[1],
		seed_in[0] }),
	.prbs_out(prbs7_out),
	.p1(p1),
	.p2(FE_PHN4_seed_in_5),
	.p3(FE_PHN5_seed_in_4),
	.p4(FE_PHN14_seed_in_3));
   prbs15_top_mapped u_prbs15_top (.clk(CTS_2),
	.rst_n(rst_n),
	.en(n_14),
	.seed_load(n_13),
	.seed_in(seed_in),
	.prbs_out(prbs15_out),
	.p1(p1),
	.p2(FE_PHN4_seed_in_5),
	.p3(FE_PHN5_seed_in_4),
	.p4(FE_PHN14_seed_in_3));
   CKAN2D1BWP7T g91__1617 (.A1(n_0),
	.A2(seed_load),
	.Z(n_22));
   INR2D0BWP7T g92__2802 (.A1(en),
	.B1(mode_select),
	.ZN(n_23));
   INR2D0BWP7T g93__1705 (.A1(en),
	.B1(n_0),
	.ZN(n_14));
   CKAN2D1BWP7T g94__5122 (.A1(seed_load),
	.A2(mode_select),
	.Z(n_13));
   INVD1BWP7T g95 (.I(mode_select),
	.ZN(n_0));
endmodule

