/*
###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID eeapps03.labidm.seas.ucla.edu)
#  Generated on:      Sat Apr 11 12:05:20 2026
#  Design:            prbs_ber_top
#  Command:           write_netlist /w/home.09/home/liyuyao864/ee209/prbs_project/build_prbs_ber/par-rundir/prbs_ber_top.lvs.v -top_module_first -top_module prbs_ber_top -exclude_leaf_cells -phys -flat -exclude_insts_of_cells { TAPCELLBWP7T FILL1BWP7T FILL2BWP7T FILL4BWP7T FILL8BWP7T FILL16BWP7T FILL32BWP7T FILL64BWP7T PCORNER PFILLER20 PFILLER10 PFILLER5 PFILLER1 PFILLER05 PFILLER0005 PAD50LAU_TRL PAD60LAU_TRL PAD60LU_TRL }
###############################################################
*/
module prbs_ber_top (
	clk, 
	rst_n, 
	en, 
	clear_count, 
	seed_load, 
	mode_select, 
	seed_in, 
	input_select, 
	inject_error_enable, 
	ext_serial_in, 
	prbs_out, 
	checker_in, 
	checker_in_final, 
	ref_bit, 
	bit_error, 
	error_count, 
	total_count);
   input clk;
   input rst_n;
   input en;
   input clear_count;
   input seed_load;
   input mode_select;
   input [14:0] seed_in;
   input input_select;
   input inject_error_enable;
   input ext_serial_in;
   output prbs_out;
   output checker_in;
   output checker_in_final;
   output ref_bit;
   output bit_error;
   output [31:0] error_count;
   output [31:0] total_count;

   // Internal wires
   wire FE_PHN25_clear_count;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN24_seed_in_3 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/FE_PHN23_seed_in_2 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/FE_PHN22_seed_in_1 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/FE_PHN21_seed_in_6 ;
   wire FE_PHN20_clear_count;
   wire FE_PHN19_clear_count;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/FE_PHN18_seed_in_0 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN17_seed_in_1 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN16_seed_in_6 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN15_seed_in_2 ;
   wire \u_prbs_gen_top/FE_PHN14_seed_in_3 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN13_seed_in_13 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN12_seed_in_14 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN11_seed_in_7 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN10_seed_in_11 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN9_seed_in_10 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN8_seed_in_9 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN7_seed_in_8 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN6_seed_in_12 ;
   wire \u_prbs_gen_top/FE_PHN5_seed_in_4 ;
   wire \u_prbs_gen_top/FE_PHN4_seed_in_5 ;
   wire FE_PHN3_rst_n;
   wire \u_prbs_gen_top/CTS_2 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_3 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_2 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_1 ;
   wire CTS_7;
   wire CTS_6;
   wire CTS_10;
   wire CTS_9;
   wire CTS_8;
   wire CTS_2;
   wire CTS_1;
   wire CTS_5;
   wire CTS_4;
   wire CTS_3;
   wire FE_OFN19_rst_n;
   wire inc_add_80_40_n_0;
   wire inc_add_80_40_n_1;
   wire inc_add_80_40_n_2;
   wire inc_add_80_40_n_3;
   wire inc_add_80_40_n_4;
   wire inc_add_80_40_n_5;
   wire inc_add_80_40_n_6;
   wire inc_add_80_40_n_7;
   wire inc_add_80_40_n_9;
   wire inc_add_80_40_n_10;
   wire inc_add_80_40_n_11;
   wire inc_add_80_40_n_12;
   wire inc_add_80_40_n_13;
   wire inc_add_80_40_n_14;
   wire inc_add_80_40_n_15;
   wire inc_add_80_40_n_16;
   wire inc_add_80_40_n_18;
   wire inc_add_80_40_n_19;
   wire inc_add_80_40_n_20;
   wire inc_add_80_40_n_23;
   wire inc_add_80_40_n_24;
   wire inc_add_80_40_n_27;
   wire inc_add_80_40_n_28;
   wire inc_add_80_40_n_29;
   wire inc_add_80_40_n_32;
   wire inc_add_80_40_n_33;
   wire inc_add_80_40_n_34;
   wire inc_add_80_40_n_36;
   wire inc_add_80_40_n_37;
   wire inc_add_80_40_n_39;
   wire inc_add_80_40_n_42;
   wire inc_add_80_40_n_43;
   wire inc_add_80_40_n_45;
   wire inc_add_80_40_n_48;
   wire inc_add_80_40_n_49;
   wire inc_add_80_40_n_51;
   wire inc_add_80_40_n_54;
   wire inc_add_80_40_n_56;
   wire inc_add_80_40_n_60;
   wire inc_add_80_40_n_62;
   wire inc_add_80_40_n_65;
   wire inc_add_80_40_n_69;
   wire inc_add_82_44_n_0;
   wire inc_add_82_44_n_1;
   wire inc_add_82_44_n_2;
   wire inc_add_82_44_n_3;
   wire inc_add_82_44_n_4;
   wire inc_add_82_44_n_5;
   wire inc_add_82_44_n_6;
   wire inc_add_82_44_n_7;
   wire inc_add_82_44_n_9;
   wire inc_add_82_44_n_10;
   wire inc_add_82_44_n_11;
   wire inc_add_82_44_n_12;
   wire inc_add_82_44_n_13;
   wire inc_add_82_44_n_14;
   wire inc_add_82_44_n_15;
   wire inc_add_82_44_n_16;
   wire inc_add_82_44_n_18;
   wire inc_add_82_44_n_19;
   wire inc_add_82_44_n_20;
   wire inc_add_82_44_n_23;
   wire inc_add_82_44_n_24;
   wire inc_add_82_44_n_27;
   wire inc_add_82_44_n_28;
   wire inc_add_82_44_n_29;
   wire inc_add_82_44_n_32;
   wire inc_add_82_44_n_33;
   wire inc_add_82_44_n_34;
   wire inc_add_82_44_n_36;
   wire inc_add_82_44_n_37;
   wire inc_add_82_44_n_39;
   wire inc_add_82_44_n_42;
   wire inc_add_82_44_n_43;
   wire inc_add_82_44_n_45;
   wire inc_add_82_44_n_48;
   wire inc_add_82_44_n_49;
   wire inc_add_82_44_n_51;
   wire inc_add_82_44_n_54;
   wire inc_add_82_44_n_56;
   wire inc_add_82_44_n_60;
   wire inc_add_82_44_n_62;
   wire inc_add_82_44_n_65;
   wire inc_add_82_44_n_69;
   wire logic_0_1_net;
   wire logic_0_2_net;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire \u_prbs_gen_top/n_0 ;
   wire \u_prbs_gen_top/n_13 ;
   wire \u_prbs_gen_top/n_14 ;
   wire \u_prbs_gen_top/n_22 ;
   wire \u_prbs_gen_top/n_23 ;
   wire \u_prbs_gen_top/prbs7_out ;
   wire \u_prbs_gen_top/prbs15_out ;
   wire \u_prbs_gen_top/u_prbs7_top/seed_value[6] ;
   wire \u_prbs_gen_top/u_prbs7_top/seed_value[5] ;
   wire \u_prbs_gen_top/u_prbs7_top/seed_value[4] ;
   wire \u_prbs_gen_top/u_prbs7_top/seed_value[3] ;
   wire \u_prbs_gen_top/u_prbs7_top/seed_value[2] ;
   wire \u_prbs_gen_top/u_prbs7_top/seed_value[1] ;
   wire \u_prbs_gen_top/u_prbs7_top/seed_value[0] ;
   wire \u_prbs_gen_top/u_prbs7_top/prbs_state[6] ;
   wire \u_prbs_gen_top/u_prbs7_top/prbs_state[5] ;
   wire \u_prbs_gen_top/u_prbs7_top/prbs_state[4] ;
   wire \u_prbs_gen_top/u_prbs7_top/prbs_state[3] ;
   wire \u_prbs_gen_top/u_prbs7_top/prbs_state[2] ;
   wire \u_prbs_gen_top/u_prbs7_top/prbs_state[1] ;
   wire \u_prbs_gen_top/u_prbs7_top/prbs_state[0] ;
   wire \u_prbs_gen_top/u_prbs7_top/UNCONNECTED0 ;
   wire \u_prbs_gen_top/u_prbs7_top/UNCONNECTED1 ;
   wire \u_prbs_gen_top/u_prbs7_top/UNCONNECTED2 ;
   wire \u_prbs_gen_top/u_prbs7_top/UNCONNECTED3 ;
   wire \u_prbs_gen_top/u_prbs7_top/UNCONNECTED4 ;
   wire \u_prbs_gen_top/u_prbs7_top/UNCONNECTED5 ;
   wire \u_prbs_gen_top/u_prbs7_top/UNCONNECTED6 ;
   wire \u_prbs_gen_top/u_prbs7_top/UNCONNECTED7 ;
   wire \u_prbs_gen_top/u_prbs7_top/logic_0_1_net ;
   wire \u_prbs_gen_top/u_prbs7_top/logic_0_2_net ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[6] ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[5] ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[4] ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[3] ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[2] ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[1] ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[0] ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/CLKGATE_rc_gclk ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/UNCONNECTED ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/logic_0_1_net ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_0 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_1 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_2 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_3 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_4 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_5 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_6 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_7 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_8 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_10 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_ctrl/n_1 ;
   wire \u_prbs_gen_top/u_prbs7_top/u_prbs_ctrl/n_2 ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[14] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[13] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[12] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[11] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[10] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[9] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[8] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[7] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[6] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[5] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[4] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[3] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[2] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[1] ;
   wire \u_prbs_gen_top/u_prbs15_top/seed_value[0] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[14] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[13] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[12] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[11] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[10] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[9] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[8] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[7] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[6] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[5] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[4] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[3] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[2] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[1] ;
   wire \u_prbs_gen_top/u_prbs15_top/prbs_state[0] ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED9 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED10 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED11 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED12 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED13 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED14 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED15 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED16 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED17 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED18 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED19 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED20 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED21 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED22 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED23 ;
   wire \u_prbs_gen_top/u_prbs15_top/UNCONNECTED24 ;
   wire \u_prbs_gen_top/u_prbs15_top/logic_0_1_net ;
   wire \u_prbs_gen_top/u_prbs15_top/logic_0_2_net ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[14] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[13] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[12] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[11] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[10] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[9] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[8] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[7] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[6] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[5] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[4] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[3] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[2] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[1] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[0] ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/UNCONNECTED8 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/logic_0_1_net ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_0 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_1 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_2 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_3 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_4 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_5 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_6 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_7 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_8 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_9 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_10 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_11 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_12 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_13 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_14 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_15 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_16 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_18 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_1 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_2 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_3 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_4 ;
   wire \u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_5 ;
   wire VDD;
   wire VSS;

   assign ref_bit = prbs_out;

   // Module instantiations
   DEL0BWP7T FE_PHC25_clear_count (
	.I(clear_count),
	.Z(FE_PHN25_clear_count), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFFD1P5BWP7T FE_PHC20_clear_count (
	.I(clear_count),
	.Z(FE_PHN20_clear_count), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFFD4BWP7T FE_PHC19_clear_count (
	.I(clear_count),
	.Z(FE_PHN19_clear_count), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFFD1P5BWP7T FE_PHC3_rst_n (
	.I(rst_n),
	.Z(FE_PHN3_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD2BWP7T CTS_ccl_a_buf_00010 (
	.I(CTS_7),
	.Z(CTS_6), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD2BWP7T CTS_ccl_a_buf_00009 (
	.I(CTS_7),
	.Z(CTS_10), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD2BWP7T CTS_ccl_a_buf_00008 (
	.I(CTS_7),
	.Z(CTS_9), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD2BWP7T CTS_ccl_a_buf_00007 (
	.I(CTS_7),
	.Z(CTS_8), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD2BWP7T CTS_ccl_a_buf_00006 (
	.I(CTS_2),
	.Z(CTS_1), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD2BWP7T CTS_ccl_a_buf_00005 (
	.I(CTS_2),
	.Z(CTS_5), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD3BWP7T CTS_ccl_a_buf_00004 (
	.I(CTS_2),
	.Z(CTS_4), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD2BWP7T CTS_ccl_a_buf_00003 (
	.I(CTS_2),
	.Z(CTS_3), 
	.VSS(VSS), 
	.VDD(VDD));
   BUFFD1BWP7T FE_OFC2_rst_n (
	.I(rst_n),
	.Z(FE_OFN19_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CKND1BWP7T FE_OFC1_add_82_44_n_18 (
	.I(inc_add_82_44_n_18),
	.ZN(inc_add_82_44_n_19), 
	.VSS(VSS), 
	.VDD(VDD));
   CKLNQD6BWP7T \CLKGATE_RC_CG_HIER_INST0/RC_CGIC_INST  (
	.CP(clk),
	.E(n_69),
	.Q(CTS_7),
	.TE(logic_0_1_net), 
	.VSS(VSS), 
	.VDD(VDD));
   CKLNQD4BWP7T \CLKGATE_RC_CG_HIER_INST1/RC_CGIC_INST  (
	.CP(clk),
	.E(n_68),
	.Q(CTS_2),
	.TE(logic_0_2_net), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD0BWP7T \u_prbs_gen_top/FE_PHC14_seed_in_3  (
	.I(seed_in[3]),
	.Z(\u_prbs_gen_top/FE_PHN14_seed_in_3 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL02BWP7T \u_prbs_gen_top/FE_PHC5_seed_in_4  (
	.I(seed_in[4]),
	.Z(\u_prbs_gen_top/FE_PHN5_seed_in_4 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL02BWP7T \u_prbs_gen_top/FE_PHC4_seed_in_5  (
	.I(seed_in[5]),
	.Z(\u_prbs_gen_top/FE_PHN4_seed_in_5 ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO22D1BWP7T \u_prbs_gen_top/FE_RC_0_0  (
	.A1(mode_select),
	.A2(\u_prbs_gen_top/prbs15_out ),
	.B1(\u_prbs_gen_top/n_0 ),
	.B2(\u_prbs_gen_top/prbs7_out ),
	.Z(prbs_out), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD1BWP7T \u_prbs_gen_top/CTS_ccl_a_buf_00011  (
	.I(clk),
	.Z(\u_prbs_gen_top/CTS_2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL01BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/FE_PHC23_seed_in_2  (
	.I(seed_in[2]),
	.Z(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/FE_PHN23_seed_in_2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL01BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/FE_PHC22_seed_in_1  (
	.I(seed_in[1]),
	.Z(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/FE_PHN22_seed_in_1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL01BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/FE_PHC21_seed_in_6  (
	.I(seed_in[6]),
	.Z(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/FE_PHN21_seed_in_6 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKLNQD1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/CLKGATE_RC_CG_HIER_INST2/RC_CGIC_INST  (
	.CP(\u_prbs_gen_top/CTS_2 ),
	.E(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_10 ),
	.Q(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/CLKGATE_rc_gclk ),
	.TE(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/logic_0_1_net ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[4]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/CLKGATE_rc_gclk ),
	.D(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_8 ),
	.Q(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[4] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/g161__2398  (
	.I0(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[3] ),
	.I1(\u_prbs_gen_top/FE_PHN5_seed_in_4 ),
	.S(\u_prbs_gen_top/n_22 ),
	.Z(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_8 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[3]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/CLKGATE_rc_gclk ),
	.D(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_7 ),
	.Q(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[3] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/g163__5107  (
	.I0(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[2] ),
	.I1(\u_prbs_gen_top/FE_PHN14_seed_in_3 ),
	.S(\u_prbs_gen_top/n_22 ),
	.Z(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_7 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[2]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/CLKGATE_rc_gclk ),
	.D(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_6 ),
	.Q(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[2] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/g165__6260  (
	.I0(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[1] ),
	.I1(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/FE_PHN23_seed_in_2 ),
	.S(\u_prbs_gen_top/n_22 ),
	.Z(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_6 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[1]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/CLKGATE_rc_gclk ),
	.D(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_5 ),
	.Q(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[1] ), 
	.VSS(VSS), 
	.VDD(VDD));
   IND3D0BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/g167__4319  (
	.A1(\u_prbs_gen_top/n_23 ),
	.B1(rst_n),
	.B2(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_4 ),
	.ZN(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_10 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/g168__8428  (
	.I0(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[0] ),
	.I1(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/FE_PHN22_seed_in_1 ),
	.S(\u_prbs_gen_top/n_22 ),
	.Z(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_5 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD0BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/g169  (
	.I(\u_prbs_gen_top/n_22 ),
	.ZN(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_4 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKSND1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[0]  (
	.CP(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/CLKGATE_rc_gclk ),
	.D(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_3 ),
	.Q(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[0] ),
	.QN(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/UNCONNECTED ),
	.SN(FE_PHN3_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/g135__5526  (
	.I0(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_2 ),
	.I1(\u_prbs_gen_top/u_prbs7_top/seed_value[0] ),
	.S(\u_prbs_gen_top/n_22 ),
	.Z(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_3 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/g136__6783  (
	.A1(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[5] ),
	.A2(\u_prbs_gen_top/prbs7_out ),
	.Z(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[5]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/CLKGATE_rc_gclk ),
	.D(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_1 ),
	.Q(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[5] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[6]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/CLKGATE_rc_gclk ),
	.D(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_0 ),
	.Q(\u_prbs_gen_top/prbs7_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/g138__3680  (
	.I0(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[4] ),
	.I1(\u_prbs_gen_top/FE_PHN4_seed_in_5 ),
	.S(\u_prbs_gen_top/n_22 ),
	.Z(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/g139__1617  (
	.I0(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[5] ),
	.I1(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/FE_PHN21_seed_in_6 ),
	.S(\u_prbs_gen_top/n_22 ),
	.Z(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/n_0 ), 
	.VSS(VSS), 
	.VDD(VDD));
   TIELBWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_core/tie_0_cell  (
	.ZN(\u_prbs_gen_top/u_prbs7_top/u_prbs_core/logic_0_1_net ), 
	.VSS(VSS), 
	.VDD(VDD));
   AO21D0BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_ctrl/g69__2802  (
	.A1(\u_prbs_gen_top/u_prbs7_top/u_prbs_ctrl/n_2 ),
	.A2(\u_prbs_gen_top/u_prbs7_top/u_prbs_ctrl/n_1 ),
	.B(seed_in[0]),
	.Z(\u_prbs_gen_top/u_prbs7_top/seed_value[0] ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR4D0BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_ctrl/g70__1705  (
	.A1(seed_in[6]),
	.A2(seed_in[5]),
	.A3(seed_in[4]),
	.A4(seed_in[3]),
	.ZN(\u_prbs_gen_top/u_prbs7_top/u_prbs_ctrl/n_2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0BWP7T \u_prbs_gen_top/u_prbs7_top/u_prbs_ctrl/g71__5122  (
	.A1(seed_in[2]),
	.A2(seed_in[1]),
	.ZN(\u_prbs_gen_top/u_prbs7_top/u_prbs_ctrl/n_1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL015BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHC24_seed_in_3  (
	.I(\u_prbs_gen_top/FE_PHN14_seed_in_3 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN24_seed_in_3 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHC17_seed_in_1  (
	.I(seed_in[1]),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN17_seed_in_1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHC16_seed_in_6  (
	.I(seed_in[6]),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN16_seed_in_6 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHC15_seed_in_2  (
	.I(seed_in[2]),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN15_seed_in_2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHC13_seed_in_13  (
	.I(seed_in[13]),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN13_seed_in_13 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHC12_seed_in_14  (
	.I(seed_in[14]),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN12_seed_in_14 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHC11_seed_in_7  (
	.I(seed_in[7]),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN11_seed_in_7 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHC10_seed_in_11  (
	.I(seed_in[11]),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN10_seed_in_11 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHC9_seed_in_10  (
	.I(seed_in[10]),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN9_seed_in_10 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHC8_seed_in_9  (
	.I(seed_in[9]),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN8_seed_in_9 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHC7_seed_in_8  (
	.I(seed_in[8]),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN7_seed_in_8 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHC6_seed_in_12  (
	.I(seed_in[12]),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN6_seed_in_12 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_ccl_a_buf_00002  (
	.I(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_3 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKBD2BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_ccl_a_buf_00001  (
	.I(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_3 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKLNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CLKGATE_RC_CG_HIER_INST3/RC_CGIC_INST  (
	.CP(\u_prbs_gen_top/CTS_2 ),
	.E(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_18 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_3 ),
	.TE(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/logic_0_1_net ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[12]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_1 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_16 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[12] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g308__8246  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[11] ),
	.I1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN6_seed_in_12 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_16 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[11]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_1 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_15 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[11] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g310__7098  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[10] ),
	.I1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN10_seed_in_11 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_15 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[10]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_1 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_14 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[10] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g312__6131  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[9] ),
	.I1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN9_seed_in_10 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_14 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[9]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_1 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_13 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[9] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g314__1881  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[8] ),
	.I1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN8_seed_in_9 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_13 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[8]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_1 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_12 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[8] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g316__5115  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[7] ),
	.I1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN7_seed_in_8 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_12 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[7]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_1 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_11 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[7] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g318__7482  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[6] ),
	.I1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN11_seed_in_7 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_11 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[6]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_2 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_10 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[6] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g320__4733  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[5] ),
	.I1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN16_seed_in_6 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_10 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[5]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_2 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_9 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[5] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g322__6161  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[4] ),
	.I1(\u_prbs_gen_top/FE_PHN4_seed_in_5 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_9 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[4]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_2 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_8 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[4] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g324__9315  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[3] ),
	.I1(\u_prbs_gen_top/FE_PHN5_seed_in_4 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_8 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[3]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_2 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_7 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[3] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g326__9945  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[2] ),
	.I1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN24_seed_in_3 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_7 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[2]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_2 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_6 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[2] ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g328__2883  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[1] ),
	.I1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN15_seed_in_2 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_6 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[1]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_2 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_5 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[1] ), 
	.VSS(VSS), 
	.VDD(VDD));
   IND3D0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g330__2346  (
	.A1(\u_prbs_gen_top/n_14 ),
	.B1(rst_n),
	.B2(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_4 ),
	.ZN(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_18 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g331__1666  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[0] ),
	.I1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN17_seed_in_1 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_5 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g332  (
	.I(\u_prbs_gen_top/n_13 ),
	.ZN(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_4 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKSND1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[0]  (
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_2 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_3 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[0] ),
	.QN(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/UNCONNECTED8 ),
	.SN(FE_PHN3_rst_n), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g215__7410  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_2 ),
	.I1(\u_prbs_gen_top/u_prbs15_top/seed_value[0] ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_3 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g216__6417  (
	.A1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[13] ),
	.A2(\u_prbs_gen_top/prbs15_out ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[13]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_1 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_1 ),
	.Q(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[13] ), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[14]  (
	.CN(FE_PHN3_rst_n),
	.CP(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/CTS_1 ),
	.D(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_0 ),
	.Q(\u_prbs_gen_top/prbs15_out ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g218__5477  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[12] ),
	.I1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN13_seed_in_13 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/g219__2398  (
	.I0(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[13] ),
	.I1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/FE_PHN12_seed_in_14 ),
	.S(\u_prbs_gen_top/n_13 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/n_0 ), 
	.VSS(VSS), 
	.VDD(VDD));
   TIELBWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_core/tie_0_cell  (
	.ZN(\u_prbs_gen_top/u_prbs15_top/u_prbs15_core/logic_0_1_net ), 
	.VSS(VSS), 
	.VDD(VDD));
   DEL01BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/FE_PHC18_seed_in_0  (
	.I(seed_in[0]),
	.Z(\u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/FE_PHN18_seed_in_0 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/g261__5107  (
	.A1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_5 ),
	.A2(\u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/FE_PHN18_seed_in_0 ),
	.Z(\u_prbs_gen_top/u_prbs15_top/seed_value[0] ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR4D0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/g262__6260  (
	.A1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_4 ),
	.A2(seed_in[7]),
	.A3(seed_in[5]),
	.A4(seed_in[3]),
	.ZN(\u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_5 ), 
	.VSS(VSS), 
	.VDD(VDD));
   IND4D0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/g263__4319  (
	.A1(seed_in[9]),
	.B1(\u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_1 ),
	.B2(\u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_3 ),
	.B3(\u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_2 ),
	.ZN(\u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_4 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR4D0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/g264__8428  (
	.A1(seed_in[14]),
	.A2(seed_in[10]),
	.A3(seed_in[4]),
	.A4(seed_in[2]),
	.ZN(\u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_3 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR4D0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/g265__5526  (
	.A1(seed_in[13]),
	.A2(seed_in[11]),
	.A3(seed_in[6]),
	.A4(seed_in[1]),
	.ZN(\u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_2 ), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D0BWP7T \u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/g266__6783  (
	.A1(seed_in[12]),
	.A2(seed_in[8]),
	.ZN(\u_prbs_gen_top/u_prbs15_top/u_prbs15_ctrl/n_1 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D1BWP7T \u_prbs_gen_top/g91__1617  (
	.A1(\u_prbs_gen_top/n_0 ),
	.A2(seed_load),
	.Z(\u_prbs_gen_top/n_22 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D0BWP7T \u_prbs_gen_top/g92__2802  (
	.A1(en),
	.B1(mode_select),
	.ZN(\u_prbs_gen_top/n_23 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D0BWP7T \u_prbs_gen_top/g93__1705  (
	.A1(en),
	.B1(\u_prbs_gen_top/n_0 ),
	.ZN(\u_prbs_gen_top/n_14 ), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D1BWP7T \u_prbs_gen_top/g94__5122  (
	.A1(seed_load),
	.A2(mode_select),
	.Z(\u_prbs_gen_top/n_13 ), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1BWP7T \u_prbs_gen_top/g95  (
	.I(mode_select),
	.ZN(\u_prbs_gen_top/n_0 ), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D1BWP7T g646__8246 (
	.A1(bit_error),
	.A2(n_64),
	.Z(n_69), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D1BWP7T g647__7098 (
	.A1(n_65),
	.A2(en),
	.Z(bit_error), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T g648__6131 (
	.A1(checker_in_final),
	.A2(prbs_out),
	.Z(n_65), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T g649__1881 (
	.A1(checker_in),
	.A2(inject_error_enable),
	.Z(checker_in_final), 
	.VSS(VSS), 
	.VDD(VDD));
   OR2D0BWP7T g650__5115 (
	.A1(n_64),
	.A2(en),
	.Z(n_68), 
	.VSS(VSS), 
	.VDD(VDD));
   CKMUX2D1BWP7T g651__7482 (
	.I0(prbs_out),
	.I1(ext_serial_in),
	.S(input_select),
	.Z(checker_in), 
	.VSS(VSS), 
	.VDD(VDD));
   IND2D0BWP7T g652__4733 (
	.A1(clear_count),
	.B1(rst_n),
	.ZN(n_64), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[0]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_9),
	.D(n_53),
	.Q(error_count[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[1]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_9),
	.D(n_51),
	.Q(error_count[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[2]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_9),
	.D(n_13),
	.Q(error_count[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[3]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_9),
	.D(n_25),
	.Q(error_count[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[4]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_63),
	.Q(error_count[4]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[5]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_54),
	.Q(error_count[5]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[6]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_40),
	.Q(error_count[6]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[7]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_36),
	.Q(error_count[7]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[8]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_41),
	.Q(error_count[8]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[9]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_37),
	.Q(error_count[9]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[10]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_38),
	.Q(error_count[10]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[11]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_35),
	.Q(error_count[11]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[12]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_34),
	.Q(error_count[12]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[13]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_33),
	.Q(error_count[13]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[14]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_42),
	.Q(error_count[14]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[15]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_6),
	.D(n_30),
	.Q(error_count[15]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[16]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_29),
	.Q(error_count[16]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[17]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_27),
	.Q(error_count[17]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[18]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_26),
	.Q(error_count[18]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[19]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_24),
	.Q(error_count[19]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[20]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_22),
	.Q(error_count[20]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[21]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_23),
	.Q(error_count[21]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[22]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_21),
	.Q(error_count[22]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[23]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_10),
	.D(n_18),
	.Q(error_count[23]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[24]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_9),
	.D(n_17),
	.Q(error_count[24]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[25]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_9),
	.D(n_16),
	.Q(error_count[25]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[26]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_9),
	.D(n_31),
	.Q(error_count[26]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[27]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_9),
	.D(n_20),
	.Q(error_count[27]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[28]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_12),
	.Q(error_count[28]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[29]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_11),
	.Q(error_count[29]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[30]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_15),
	.Q(error_count[30]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \error_count_reg[31]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_8),
	.D(n_9),
	.Q(error_count[31]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[0]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_8),
	.Q(total_count[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[1]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_7),
	.Q(total_count[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[2]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_6),
	.Q(total_count[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[3]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_5),
	.Q(total_count[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[4]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_4),
	.Q(total_count[4]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[5]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_3),
	.Q(total_count[5]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[6]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_2),
	.Q(total_count[6]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[7]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_1),
	.Q(total_count[7]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[8]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_0),
	.Q(total_count[8]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[9]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_1),
	.D(n_62),
	.Q(total_count[9]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[10]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_1),
	.D(n_61),
	.Q(total_count[10]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[11]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_1),
	.D(n_58),
	.Q(total_count[11]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[12]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_1),
	.D(n_57),
	.Q(total_count[12]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[13]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_1),
	.D(n_56),
	.Q(total_count[13]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[14]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_55),
	.Q(total_count[14]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[15]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_52),
	.Q(total_count[15]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[16]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_10),
	.Q(total_count[16]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[17]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_19),
	.Q(total_count[17]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[18]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_47),
	.Q(total_count[18]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[19]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_28),
	.Q(total_count[19]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[20]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_49),
	.Q(total_count[20]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[21]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_32),
	.Q(total_count[21]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[22]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_46),
	.Q(total_count[22]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[23]  (
	.CN(FE_PHN3_rst_n),
	.CP(CTS_5),
	.D(n_44),
	.Q(total_count[23]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[24]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_39),
	.Q(total_count[24]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[25]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_43),
	.Q(total_count[25]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[26]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_48),
	.Q(total_count[26]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[27]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_4),
	.D(n_45),
	.Q(total_count[27]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[28]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_60),
	.Q(total_count[28]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[29]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_50),
	.Q(total_count[29]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[30]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_14),
	.Q(total_count[30]), 
	.VSS(VSS), 
	.VDD(VDD));
   DFKCNQD1BWP7T \total_count_reg[31]  (
	.CN(FE_OFN19_rst_n),
	.CP(CTS_3),
	.D(n_59),
	.Q(total_count[31]), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1110__6161 (
	.A1(n_104),
	.B1(FE_PHN19_clear_count),
	.ZN(n_63), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1111__9315 (
	.A1(n_78),
	.B1(FE_PHN19_clear_count),
	.ZN(n_62), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1112__9945 (
	.A1(n_79),
	.B1(FE_PHN19_clear_count),
	.ZN(n_61), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1113__2883 (
	.A1(n_97),
	.B1(FE_PHN20_clear_count),
	.ZN(n_60), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1114__2346 (
	.A1(n_100),
	.B1(FE_PHN20_clear_count),
	.ZN(n_59), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1115__1666 (
	.A1(n_80),
	.B1(FE_PHN19_clear_count),
	.ZN(n_58), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1116__7410 (
	.A1(n_81),
	.B1(FE_PHN19_clear_count),
	.ZN(n_57), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1117__6417 (
	.A1(n_82),
	.B1(FE_PHN19_clear_count),
	.ZN(n_56), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1118__5477 (
	.A1(n_83),
	.B1(FE_PHN19_clear_count),
	.ZN(n_55), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1119__2398 (
	.A1(n_105),
	.B1(FE_PHN19_clear_count),
	.ZN(n_54), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2XD0BWP7T g1120__5107 (
	.A1(error_count[0]),
	.A2(FE_PHN20_clear_count),
	.ZN(n_53), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1121__6260 (
	.A1(n_84),
	.B1(FE_PHN19_clear_count),
	.ZN(n_52), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1122__4319 (
	.A1(n_101),
	.B1(FE_PHN20_clear_count),
	.ZN(n_51), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1123__8428 (
	.A1(n_98),
	.B1(FE_PHN20_clear_count),
	.ZN(n_50), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1124__5526 (
	.A1(n_89),
	.B1(FE_PHN19_clear_count),
	.ZN(n_49), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1125__6783 (
	.A1(n_95),
	.B1(FE_PHN20_clear_count),
	.ZN(n_48), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1126__3680 (
	.A1(n_87),
	.B1(FE_PHN19_clear_count),
	.ZN(n_47), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1127__1617 (
	.A1(n_91),
	.B1(FE_PHN19_clear_count),
	.ZN(n_46), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1128__2802 (
	.A1(n_96),
	.B1(FE_PHN20_clear_count),
	.ZN(n_45), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1129__1705 (
	.A1(n_92),
	.B1(FE_PHN19_clear_count),
	.ZN(n_44), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1130__5122 (
	.A1(n_94),
	.B1(FE_PHN20_clear_count),
	.ZN(n_43), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1131__8246 (
	.A1(n_114),
	.B1(FE_PHN19_clear_count),
	.ZN(n_42), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1132__7098 (
	.A1(n_108),
	.B1(FE_PHN19_clear_count),
	.ZN(n_41), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1133__6131 (
	.A1(n_106),
	.B1(FE_PHN19_clear_count),
	.ZN(n_40), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1134__1881 (
	.A1(n_93),
	.B1(FE_PHN20_clear_count),
	.ZN(n_39), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1135__5115 (
	.A1(n_110),
	.B1(FE_PHN19_clear_count),
	.ZN(n_38), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1136__7482 (
	.A1(n_109),
	.B1(FE_PHN19_clear_count),
	.ZN(n_37), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1137__4733 (
	.A1(n_107),
	.B1(FE_PHN19_clear_count),
	.ZN(n_36), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1138__6161 (
	.A1(n_111),
	.B1(FE_PHN19_clear_count),
	.ZN(n_35), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1139__9315 (
	.A1(n_112),
	.B1(FE_PHN19_clear_count),
	.ZN(n_34), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1140__9945 (
	.A1(n_113),
	.B1(FE_PHN19_clear_count),
	.ZN(n_33), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1141__2883 (
	.A1(n_90),
	.B1(FE_PHN19_clear_count),
	.ZN(n_32), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1142__2346 (
	.A1(n_126),
	.B1(FE_PHN20_clear_count),
	.ZN(n_31), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1143__1666 (
	.A1(n_115),
	.B1(FE_PHN19_clear_count),
	.ZN(n_30), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1144__7410 (
	.A1(n_116),
	.B1(FE_PHN20_clear_count),
	.ZN(n_29), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1145__6417 (
	.A1(n_88),
	.B1(FE_PHN19_clear_count),
	.ZN(n_28), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1146__5477 (
	.A1(n_117),
	.B1(FE_PHN20_clear_count),
	.ZN(n_27), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1147__2398 (
	.A1(n_118),
	.B1(FE_PHN20_clear_count),
	.ZN(n_26), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1148__5107 (
	.A1(n_103),
	.B1(FE_PHN20_clear_count),
	.ZN(n_25), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1149__6260 (
	.A1(n_119),
	.B1(FE_PHN20_clear_count),
	.ZN(n_24), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1150__4319 (
	.A1(n_121),
	.B1(FE_PHN20_clear_count),
	.ZN(n_23), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1151__8428 (
	.A1(n_120),
	.B1(FE_PHN20_clear_count),
	.ZN(n_22), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1152__5526 (
	.A1(n_122),
	.B1(FE_PHN20_clear_count),
	.ZN(n_21), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1153__6783 (
	.A1(n_127),
	.B1(FE_PHN25_clear_count),
	.ZN(n_20), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1154__3680 (
	.A1(n_86),
	.B1(FE_PHN19_clear_count),
	.ZN(n_19), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1155__1617 (
	.A1(n_123),
	.B1(FE_PHN20_clear_count),
	.ZN(n_18), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1156__2802 (
	.A1(n_124),
	.B1(FE_PHN20_clear_count),
	.ZN(n_17), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1157__1705 (
	.A1(n_125),
	.B1(FE_PHN20_clear_count),
	.ZN(n_16), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1158__5122 (
	.A1(n_130),
	.B1(FE_PHN19_clear_count),
	.ZN(n_15), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1159__8246 (
	.A1(n_99),
	.B1(FE_PHN20_clear_count),
	.ZN(n_14), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1160__7098 (
	.A1(n_102),
	.B1(FE_PHN20_clear_count),
	.ZN(n_13), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1161__6131 (
	.A1(n_128),
	.B1(FE_PHN19_clear_count),
	.ZN(n_12), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1162__1881 (
	.A1(n_129),
	.B1(FE_PHN19_clear_count),
	.ZN(n_11), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1163__5115 (
	.A1(n_85),
	.B1(FE_PHN19_clear_count),
	.ZN(n_10), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1164__7482 (
	.A1(n_131),
	.B1(FE_PHN19_clear_count),
	.ZN(n_9), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2XD0BWP7T g1165__4733 (
	.A1(total_count[0]),
	.A2(FE_PHN20_clear_count),
	.ZN(n_8), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1166__6161 (
	.A1(n_70),
	.B1(FE_PHN20_clear_count),
	.ZN(n_7), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1167__9315 (
	.A1(n_71),
	.B1(FE_PHN20_clear_count),
	.ZN(n_6), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1168__9945 (
	.A1(n_72),
	.B1(FE_PHN20_clear_count),
	.ZN(n_5), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1169__2883 (
	.A1(n_73),
	.B1(FE_PHN20_clear_count),
	.ZN(n_4), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1170__2346 (
	.A1(n_74),
	.B1(FE_PHN20_clear_count),
	.ZN(n_3), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1171__1666 (
	.A1(n_75),
	.B1(FE_PHN20_clear_count),
	.ZN(n_2), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1172__7410 (
	.A1(n_76),
	.B1(FE_PHN20_clear_count),
	.ZN(n_1), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2D1BWP7T g1173__6417 (
	.A1(n_77),
	.B1(FE_PHN19_clear_count),
	.ZN(n_0), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_80_40_g479__5477 (
	.A1(inc_add_80_40_n_69),
	.A2(total_count[19]),
	.Z(n_88), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2D1BWP7T inc_add_80_40_g480__2398 (
	.A1(inc_add_80_40_n_65),
	.A2(total_count[31]),
	.Z(n_100), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g481__5107 (
	.A(total_count[18]),
	.B(inc_add_80_40_n_56),
	.CO(inc_add_80_40_n_69),
	.S(n_87), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_80_40_g482__6260 (
	.A1(inc_add_80_40_n_62),
	.A2(total_count[29]),
	.Z(n_98), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_80_40_g483__4319 (
	.A1(inc_add_80_40_n_60),
	.A2(total_count[11]),
	.Z(n_80), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D1BWP7T inc_add_80_40_g484__8428 (
	.A(total_count[30]),
	.B(inc_add_80_40_n_48),
	.CO(inc_add_80_40_n_65),
	.S(n_99), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_80_40_g485__5526 (
	.A1(inc_add_80_40_n_54),
	.A2(total_count[27]),
	.Z(n_96), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g486__6783 (
	.A(total_count[28]),
	.B(inc_add_80_40_n_42),
	.CO(inc_add_80_40_n_62),
	.S(n_97), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g487__3680 (
	.A(total_count[10]),
	.B(inc_add_80_40_n_43),
	.CO(inc_add_80_40_n_60),
	.S(n_79), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_80_40_g488__1617 (
	.A1(inc_add_80_40_n_51),
	.A2(total_count[25]),
	.Z(n_94), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_80_40_g489__2802 (
	.A1(inc_add_80_40_n_49),
	.A2(total_count[23]),
	.Z(n_92), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g490__1705 (
	.A(total_count[17]),
	.B(inc_add_80_40_n_39),
	.CO(inc_add_80_40_n_56),
	.S(n_86), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g491__5122 (
	.A(total_count[26]),
	.B(inc_add_80_40_n_36),
	.CO(inc_add_80_40_n_54),
	.S(n_95), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_80_40_g492__8246 (
	.A1(inc_add_80_40_n_45),
	.A2(total_count[21]),
	.Z(n_90), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g493__7098 (
	.A(total_count[24]),
	.B(inc_add_80_40_n_32),
	.CO(inc_add_80_40_n_51),
	.S(n_93), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g494__6131 (
	.A(total_count[22]),
	.B(inc_add_80_40_n_33),
	.CO(inc_add_80_40_n_49),
	.S(n_91), 
	.VSS(VSS), 
	.VDD(VDD));
   AN3XD1BWP7T inc_add_80_40_g495__1881 (
	.A1(inc_add_80_40_n_42),
	.A2(total_count[29]),
	.A3(total_count[28]),
	.Z(inc_add_80_40_n_48), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_80_40_g496__5115 (
	.A1(inc_add_80_40_n_37),
	.A2(total_count[15]),
	.Z(n_84), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g497__7482 (
	.A(total_count[20]),
	.B(inc_add_80_40_n_28),
	.CO(inc_add_80_40_n_45),
	.S(n_89), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g498__4733 (
	.A(total_count[9]),
	.B(inc_add_80_40_n_29),
	.CO(inc_add_80_40_n_43),
	.S(n_78), 
	.VSS(VSS), 
	.VDD(VDD));
   AN3D2BWP7T inc_add_80_40_g499__6161 (
	.A1(inc_add_80_40_n_36),
	.A2(total_count[27]),
	.A3(total_count[26]),
	.Z(inc_add_80_40_n_42), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_80_40_g500__9315 (
	.A1(inc_add_80_40_n_34),
	.A2(total_count[13]),
	.Z(n_82), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g501__9945 (
	.A(total_count[16]),
	.B(inc_add_80_40_n_0),
	.CO(inc_add_80_40_n_39),
	.S(n_85), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g502__2883 (
	.A(total_count[14]),
	.B(inc_add_80_40_n_23),
	.CO(inc_add_80_40_n_37),
	.S(n_83), 
	.VSS(VSS), 
	.VDD(VDD));
   AN3D1BWP7T inc_add_80_40_g503__2346 (
	.A1(inc_add_80_40_n_32),
	.A2(total_count[25]),
	.A3(total_count[24]),
	.Z(inc_add_80_40_n_36), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g504__1666 (
	.A(total_count[12]),
	.B(inc_add_80_40_n_19),
	.CO(inc_add_80_40_n_34),
	.S(n_81), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D1BWP7T inc_add_80_40_g505__7410 (
	.A1(inc_add_80_40_n_28),
	.A2(inc_add_80_40_n_4),
	.Z(inc_add_80_40_n_33), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2XD3BWP7T inc_add_80_40_g506__6417 (
	.A1(inc_add_80_40_n_27),
	.A2(inc_add_80_40_n_9),
	.ZN(inc_add_80_40_n_32), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_80_40_g507__5477 (
	.A1(inc_add_80_40_n_24),
	.A2(total_count[7]),
	.Z(n_76), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g508__2398 (
	.A(total_count[8]),
	.B(inc_add_80_40_n_15),
	.CO(inc_add_80_40_n_29),
	.S(n_77), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1BWP7T inc_add_80_40_g509 (
	.I(inc_add_80_40_n_27),
	.ZN(inc_add_80_40_n_28), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D1BWP7T inc_add_80_40_g510__5107 (
	.A1(inc_add_80_40_n_0),
	.A2(inc_add_80_40_n_6),
	.ZN(inc_add_80_40_n_27), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_80_40_g511__6260 (
	.A1(inc_add_80_40_n_20),
	.A2(total_count[5]),
	.Z(n_74), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g512__4319 (
	.A(total_count[6]),
	.B(inc_add_80_40_n_14),
	.CO(inc_add_80_40_n_24),
	.S(n_75), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2XD0BWP7T inc_add_80_40_g513__8428 (
	.A1(inc_add_80_40_n_19),
	.B1(inc_add_80_40_n_2),
	.ZN(inc_add_80_40_n_23), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2XD1BWP7T inc_add_80_40_g515__5526 (
	.A1(inc_add_80_40_n_18),
	.A2(inc_add_80_40_n_10),
	.ZN(inc_add_80_40_n_0), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_80_40_g516__6783 (
	.A1(inc_add_80_40_n_16),
	.A2(total_count[3]),
	.Z(n_72), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g517__3680 (
	.A(total_count[4]),
	.B(inc_add_80_40_n_12),
	.CO(inc_add_80_40_n_20),
	.S(n_73), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1BWP7T inc_add_80_40_g518 (
	.I(inc_add_80_40_n_18),
	.ZN(inc_add_80_40_n_19), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D2BWP7T inc_add_80_40_g519__1617 (
	.A1(inc_add_80_40_n_15),
	.A2(inc_add_80_40_n_7),
	.ZN(inc_add_80_40_n_18), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_80_40_g520__2802 (
	.A(total_count[2]),
	.B(inc_add_80_40_n_11),
	.CO(inc_add_80_40_n_16),
	.S(n_71), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D3BWP7T inc_add_80_40_g521__1705 (
	.A1(inc_add_80_40_n_13),
	.A2(inc_add_80_40_n_3),
	.ZN(inc_add_80_40_n_15), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1BWP7T inc_add_80_40_g522 (
	.I(inc_add_80_40_n_13),
	.ZN(inc_add_80_40_n_14), 
	.VSS(VSS), 
	.VDD(VDD));
   ND3D2BWP7T inc_add_80_40_g523__5122 (
	.A1(inc_add_80_40_n_12),
	.A2(total_count[5]),
	.A3(total_count[4]),
	.ZN(inc_add_80_40_n_13), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D1BWP7T inc_add_80_40_g524__8246 (
	.A1(inc_add_80_40_n_1),
	.A2(inc_add_80_40_n_5),
	.ZN(inc_add_80_40_n_12), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1BWP7T inc_add_80_40_g525 (
	.I(inc_add_80_40_n_1),
	.ZN(inc_add_80_40_n_11), 
	.VSS(VSS), 
	.VDD(VDD));
   IND3D1BWP7T inc_add_80_40_g526__7098 (
	.A1(inc_add_80_40_n_2),
	.B1(total_count[15]),
	.B2(total_count[14]),
	.ZN(inc_add_80_40_n_10), 
	.VSS(VSS), 
	.VDD(VDD));
   ND3D0BWP7T inc_add_80_40_g527__6131 (
	.A1(inc_add_80_40_n_4),
	.A2(total_count[23]),
	.A3(total_count[22]),
	.ZN(inc_add_80_40_n_9), 
	.VSS(VSS), 
	.VDD(VDD));
   OA21D0BWP7T inc_add_80_40_g528__1881 (
	.A1(total_count[0]),
	.A2(total_count[1]),
	.B(inc_add_80_40_n_1),
	.Z(n_70), 
	.VSS(VSS), 
	.VDD(VDD));
   AN4D0BWP7T inc_add_80_40_g529__5115 (
	.A1(total_count[11]),
	.A2(total_count[10]),
	.A3(total_count[9]),
	.A4(total_count[8]),
	.Z(inc_add_80_40_n_7), 
	.VSS(VSS), 
	.VDD(VDD));
   AN4D0BWP7T inc_add_80_40_g530__7482 (
	.A1(total_count[19]),
	.A2(total_count[18]),
	.A3(total_count[17]),
	.A4(total_count[16]),
	.Z(inc_add_80_40_n_6), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D1BWP7T inc_add_80_40_g531__4733 (
	.A1(total_count[3]),
	.A2(total_count[2]),
	.ZN(inc_add_80_40_n_5), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D1BWP7T inc_add_80_40_g532__6161 (
	.A1(total_count[21]),
	.A2(total_count[20]),
	.Z(inc_add_80_40_n_4), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D1BWP7T inc_add_80_40_g533__9315 (
	.A1(total_count[7]),
	.A2(total_count[6]),
	.ZN(inc_add_80_40_n_3), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D1BWP7T inc_add_80_40_g534__9945 (
	.A1(total_count[13]),
	.A2(total_count[12]),
	.ZN(inc_add_80_40_n_2), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D1BWP7T inc_add_80_40_g535__2883 (
	.A1(total_count[1]),
	.A2(total_count[0]),
	.ZN(inc_add_80_40_n_1), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_82_44_g479__2346 (
	.A1(inc_add_82_44_n_69),
	.A2(error_count[19]),
	.Z(n_119), 
	.VSS(VSS), 
	.VDD(VDD));
   XOR2D1BWP7T inc_add_82_44_g480__1666 (
	.A1(inc_add_82_44_n_65),
	.A2(error_count[31]),
	.Z(n_131), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g481__7410 (
	.A(error_count[18]),
	.B(inc_add_82_44_n_56),
	.CO(inc_add_82_44_n_69),
	.S(n_118), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_82_44_g482__6417 (
	.A1(inc_add_82_44_n_62),
	.A2(error_count[29]),
	.Z(n_129), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_82_44_g483__5477 (
	.A1(inc_add_82_44_n_60),
	.A2(error_count[11]),
	.Z(n_111), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D1BWP7T inc_add_82_44_g484__2398 (
	.A(error_count[30]),
	.B(inc_add_82_44_n_48),
	.CO(inc_add_82_44_n_65),
	.S(n_130), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_82_44_g485__5107 (
	.A1(inc_add_82_44_n_54),
	.A2(error_count[27]),
	.Z(n_127), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g486__6260 (
	.A(error_count[28]),
	.B(inc_add_82_44_n_42),
	.CO(inc_add_82_44_n_62),
	.S(n_128), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g487__4319 (
	.A(error_count[10]),
	.B(inc_add_82_44_n_43),
	.CO(inc_add_82_44_n_60),
	.S(n_110), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_82_44_g488__8428 (
	.A1(inc_add_82_44_n_51),
	.A2(error_count[25]),
	.Z(n_125), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_82_44_g489__5526 (
	.A1(inc_add_82_44_n_49),
	.A2(error_count[23]),
	.Z(n_123), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g490__6783 (
	.A(error_count[17]),
	.B(inc_add_82_44_n_39),
	.CO(inc_add_82_44_n_56),
	.S(n_117), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g491__3680 (
	.A(error_count[26]),
	.B(inc_add_82_44_n_36),
	.CO(inc_add_82_44_n_54),
	.S(n_126), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_82_44_g492__1617 (
	.A1(inc_add_82_44_n_45),
	.A2(error_count[21]),
	.Z(n_121), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g493__2802 (
	.A(error_count[24]),
	.B(inc_add_82_44_n_32),
	.CO(inc_add_82_44_n_51),
	.S(n_124), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g494__1705 (
	.A(error_count[22]),
	.B(inc_add_82_44_n_33),
	.CO(inc_add_82_44_n_49),
	.S(n_122), 
	.VSS(VSS), 
	.VDD(VDD));
   AN3XD1BWP7T inc_add_82_44_g495__5122 (
	.A1(inc_add_82_44_n_42),
	.A2(error_count[29]),
	.A3(error_count[28]),
	.Z(inc_add_82_44_n_48), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_82_44_g496__8246 (
	.A1(inc_add_82_44_n_37),
	.A2(error_count[15]),
	.Z(n_115), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g497__7098 (
	.A(error_count[20]),
	.B(inc_add_82_44_n_28),
	.CO(inc_add_82_44_n_45),
	.S(n_120), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g498__6131 (
	.A(error_count[9]),
	.B(inc_add_82_44_n_29),
	.CO(inc_add_82_44_n_43),
	.S(n_109), 
	.VSS(VSS), 
	.VDD(VDD));
   AN3D2BWP7T inc_add_82_44_g499__1881 (
	.A1(inc_add_82_44_n_36),
	.A2(error_count[27]),
	.A3(error_count[26]),
	.Z(inc_add_82_44_n_42), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_82_44_g500__5115 (
	.A1(inc_add_82_44_n_34),
	.A2(error_count[13]),
	.Z(n_113), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g501__7482 (
	.A(error_count[16]),
	.B(inc_add_82_44_n_0),
	.CO(inc_add_82_44_n_39),
	.S(n_116), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g502__4733 (
	.A(error_count[14]),
	.B(inc_add_82_44_n_23),
	.CO(inc_add_82_44_n_37),
	.S(n_114), 
	.VSS(VSS), 
	.VDD(VDD));
   AN3D1BWP7T inc_add_82_44_g503__6161 (
	.A1(inc_add_82_44_n_32),
	.A2(error_count[25]),
	.A3(error_count[24]),
	.Z(inc_add_82_44_n_36), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g504__9315 (
	.A(error_count[12]),
	.B(inc_add_82_44_n_19),
	.CO(inc_add_82_44_n_34),
	.S(n_112), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D1BWP7T inc_add_82_44_g505__9945 (
	.A1(inc_add_82_44_n_28),
	.A2(inc_add_82_44_n_4),
	.Z(inc_add_82_44_n_33), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2XD2BWP7T inc_add_82_44_g506__2883 (
	.A1(inc_add_82_44_n_27),
	.A2(inc_add_82_44_n_9),
	.ZN(inc_add_82_44_n_32), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_82_44_g507__2346 (
	.A1(inc_add_82_44_n_24),
	.A2(error_count[7]),
	.Z(n_107), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g508__1666 (
	.A(error_count[8]),
	.B(inc_add_82_44_n_15),
	.CO(inc_add_82_44_n_29),
	.S(n_108), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1BWP7T inc_add_82_44_g509 (
	.I(inc_add_82_44_n_27),
	.ZN(inc_add_82_44_n_28), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D1BWP7T inc_add_82_44_g510__7410 (
	.A1(inc_add_82_44_n_0),
	.A2(inc_add_82_44_n_6),
	.ZN(inc_add_82_44_n_27), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_82_44_g511__6417 (
	.A1(inc_add_82_44_n_20),
	.A2(error_count[5]),
	.Z(n_105), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g512__5477 (
	.A(error_count[6]),
	.B(inc_add_82_44_n_14),
	.CO(inc_add_82_44_n_24),
	.S(n_106), 
	.VSS(VSS), 
	.VDD(VDD));
   INR2XD0BWP7T inc_add_82_44_g513__2398 (
	.A1(inc_add_82_44_n_19),
	.B1(inc_add_82_44_n_2),
	.ZN(inc_add_82_44_n_23), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2XD2BWP7T inc_add_82_44_g515__5107 (
	.A1(inc_add_82_44_n_18),
	.A2(inc_add_82_44_n_10),
	.ZN(inc_add_82_44_n_0), 
	.VSS(VSS), 
	.VDD(VDD));
   CKXOR2D1BWP7T inc_add_82_44_g516__6260 (
	.A1(inc_add_82_44_n_16),
	.A2(error_count[3]),
	.Z(n_103), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g517__4319 (
	.A(error_count[4]),
	.B(inc_add_82_44_n_12),
	.CO(inc_add_82_44_n_20),
	.S(n_104), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D1BWP7T inc_add_82_44_g519__8428 (
	.A1(inc_add_82_44_n_15),
	.A2(inc_add_82_44_n_7),
	.ZN(inc_add_82_44_n_18), 
	.VSS(VSS), 
	.VDD(VDD));
   HA1D0BWP7T inc_add_82_44_g520__5526 (
	.A(error_count[2]),
	.B(inc_add_82_44_n_11),
	.CO(inc_add_82_44_n_16),
	.S(n_102), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2XD1BWP7T inc_add_82_44_g521__6783 (
	.A1(inc_add_82_44_n_13),
	.A2(inc_add_82_44_n_3),
	.ZN(inc_add_82_44_n_15), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1BWP7T inc_add_82_44_g522 (
	.I(inc_add_82_44_n_13),
	.ZN(inc_add_82_44_n_14), 
	.VSS(VSS), 
	.VDD(VDD));
   ND3D1BWP7T inc_add_82_44_g523__3680 (
	.A1(inc_add_82_44_n_12),
	.A2(error_count[5]),
	.A3(error_count[4]),
	.ZN(inc_add_82_44_n_13), 
	.VSS(VSS), 
	.VDD(VDD));
   NR2D2BWP7T inc_add_82_44_g524__1617 (
	.A1(inc_add_82_44_n_1),
	.A2(inc_add_82_44_n_5),
	.ZN(inc_add_82_44_n_12), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1BWP7T inc_add_82_44_g525 (
	.I(inc_add_82_44_n_1),
	.ZN(inc_add_82_44_n_11), 
	.VSS(VSS), 
	.VDD(VDD));
   IND3D1BWP7T inc_add_82_44_g526__2802 (
	.A1(inc_add_82_44_n_2),
	.B1(error_count[15]),
	.B2(error_count[14]),
	.ZN(inc_add_82_44_n_10), 
	.VSS(VSS), 
	.VDD(VDD));
   ND3D0BWP7T inc_add_82_44_g527__1705 (
	.A1(inc_add_82_44_n_4),
	.A2(error_count[23]),
	.A3(error_count[22]),
	.ZN(inc_add_82_44_n_9), 
	.VSS(VSS), 
	.VDD(VDD));
   OA21D0BWP7T inc_add_82_44_g528__5122 (
	.A1(error_count[0]),
	.A2(error_count[1]),
	.B(inc_add_82_44_n_1),
	.Z(n_101), 
	.VSS(VSS), 
	.VDD(VDD));
   AN4D0BWP7T inc_add_82_44_g529__8246 (
	.A1(error_count[11]),
	.A2(error_count[10]),
	.A3(error_count[9]),
	.A4(error_count[8]),
	.Z(inc_add_82_44_n_7), 
	.VSS(VSS), 
	.VDD(VDD));
   AN4D0BWP7T inc_add_82_44_g530__7098 (
	.A1(error_count[19]),
	.A2(error_count[18]),
	.A3(error_count[17]),
	.A4(error_count[16]),
	.Z(inc_add_82_44_n_6), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D1BWP7T inc_add_82_44_g531__6131 (
	.A1(error_count[3]),
	.A2(error_count[2]),
	.ZN(inc_add_82_44_n_5), 
	.VSS(VSS), 
	.VDD(VDD));
   CKAN2D1BWP7T inc_add_82_44_g532__1881 (
	.A1(error_count[21]),
	.A2(error_count[20]),
	.Z(inc_add_82_44_n_4), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D1BWP7T inc_add_82_44_g533__5115 (
	.A1(error_count[7]),
	.A2(error_count[6]),
	.ZN(inc_add_82_44_n_3), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D1BWP7T inc_add_82_44_g534__7482 (
	.A1(error_count[13]),
	.A2(error_count[12]),
	.ZN(inc_add_82_44_n_2), 
	.VSS(VSS), 
	.VDD(VDD));
   ND2D1BWP7T inc_add_82_44_g535__4733 (
	.A1(error_count[1]),
	.A2(error_count[0]),
	.ZN(inc_add_82_44_n_1), 
	.VSS(VSS), 
	.VDD(VDD));
   TIELBWP7T tie_0_cell (
	.ZN(logic_0_1_net), 
	.VSS(VSS), 
	.VDD(VDD));
   TIELBWP7T tie_0_cell1 (
	.ZN(logic_0_2_net), 
	.VSS(VSS), 
	.VDD(VDD));
endmodule

