
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Apr  8 2026 17:12:55 PDT (Apr  9 2026 00:12:55 UTC)

// Verification Directory fv/ber_checker_top 

module CLKGATE_RC_CG_MOD_mapped(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP7T RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module CLKGATE_RC_CG_MOD_1_mapped(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP7T RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module CLKGATE_RC_CG_MOD_2_mapped(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP7T RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module prbs_core_LFSR_W7_DEFAULT_SEED1_mapped(clk, rst_n, load_req,
     seed_value, step_en, prbs_out, state_out);
  input clk, rst_n, load_req, step_en;
  input [6:0] seed_value;
  output prbs_out;
  output [6:0] state_out;
  wire clk, rst_n, load_req, step_en;
  wire [6:0] seed_value;
  wire prbs_out;
  wire [6:0] state_out;
  wire [6:0] lfsr_q;
  wire CLKGATE_rc_gclk, UNCONNECTED, logic_0_1_net, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_10;
  CLKGATE_RC_CG_MOD_2_mapped CLKGATE_RC_CG_HIER_INST2(.enable (n_10),
       .ck_in (clk), .ck_out (CLKGATE_rc_gclk), .test (logic_0_1_net));
  DFKCNQD1BWP7T \lfsr_q_reg[4] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_8), .Q (lfsr_q[4]));
  CKMUX2D1BWP7T g161__2398(.I0 (lfsr_q[3]), .I1 (seed_value[4]), .S
       (load_req), .Z (n_8));
  DFKCNQD1BWP7T \lfsr_q_reg[3] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_7), .Q (lfsr_q[3]));
  CKMUX2D1BWP7T g163__5107(.I0 (lfsr_q[2]), .I1 (seed_value[3]), .S
       (load_req), .Z (n_7));
  DFKCNQD1BWP7T \lfsr_q_reg[2] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_6), .Q (lfsr_q[2]));
  CKMUX2D1BWP7T g165__6260(.I0 (lfsr_q[1]), .I1 (seed_value[2]), .S
       (load_req), .Z (n_6));
  DFKCNQD1BWP7T \lfsr_q_reg[1] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_5), .Q (lfsr_q[1]));
  IND3D0BWP7T g167__4319(.A1 (step_en), .B1 (rst_n), .B2 (n_4), .ZN
       (n_10));
  CKMUX2D1BWP7T g168__8428(.I0 (lfsr_q[0]), .I1 (seed_value[1]), .S
       (load_req), .Z (n_5));
  INVD0BWP7T g169(.I (load_req), .ZN (n_4));
  DFKSND1BWP7T \lfsr_q_reg[0] (.CP (CLKGATE_rc_gclk), .D (n_3), .SN
       (rst_n), .Q (lfsr_q[0]), .QN (UNCONNECTED));
  CKMUX2D1BWP7T g135__5526(.I0 (n_2), .I1 (seed_value[0]), .S
       (load_req), .Z (n_3));
  CKXOR2D1BWP7T g136__6783(.A1 (lfsr_q[5]), .A2 (prbs_out), .Z (n_2));
  DFKCNQD1BWP7T \lfsr_q_reg[5] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_1), .Q (lfsr_q[5]));
  DFKCNQD1BWP7T \lfsr_q_reg[6] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_0), .Q (prbs_out));
  CKMUX2D1BWP7T g138__3680(.I0 (lfsr_q[4]), .I1 (seed_value[5]), .S
       (load_req), .Z (n_1));
  CKMUX2D1BWP7T g139__1617(.I0 (lfsr_q[5]), .I1 (seed_value[6]), .S
       (load_req), .Z (n_0));
  TIELBWP7T tie_0_cell(.ZN (logic_0_1_net));
  TIELBWP7T tie_0_cell1(.ZN (state_out[0]));
  TIELBWP7T tie_0_cell2(.ZN (state_out[1]));
  TIELBWP7T tie_0_cell3(.ZN (state_out[2]));
  TIELBWP7T tie_0_cell4(.ZN (state_out[3]));
  TIELBWP7T tie_0_cell5(.ZN (state_out[4]));
  TIELBWP7T tie_0_cell6(.ZN (state_out[5]));
  TIELBWP7T tie_0_cell7(.ZN (state_out[6]));
endmodule

module prbs_ctrl_LFSR_W7_DEFAULT_SEED1_mapped(seed_load, seed_in, en,
     load_req, seed_value, step_en);
  input seed_load, en;
  input [6:0] seed_in;
  output load_req, step_en;
  output [6:0] seed_value;
  wire seed_load, en;
  wire [6:0] seed_in;
  wire load_req, step_en;
  wire [6:0] seed_value;
  wire n_1, n_2;
  AO21D0BWP7T g69__2802(.A1 (n_2), .A2 (n_1), .B (seed_in[0]), .Z
       (seed_value[0]));
  NR4D0BWP7T g70__1705(.A1 (seed_in[6]), .A2 (seed_in[5]), .A3
       (seed_in[4]), .A4 (seed_in[3]), .ZN (n_2));
  NR2D0BWP7T g71__5122(.A1 (seed_in[2]), .A2 (seed_in[1]), .ZN (n_1));
  TIELBWP7T tie_0_cell(.ZN (load_req));
  TIELBWP7T tie_0_cell1(.ZN (seed_value[1]));
  TIELBWP7T tie_0_cell2(.ZN (seed_value[2]));
  TIELBWP7T tie_0_cell3(.ZN (seed_value[3]));
  TIELBWP7T tie_0_cell4(.ZN (seed_value[4]));
  TIELBWP7T tie_0_cell5(.ZN (seed_value[5]));
  TIELBWP7T tie_0_cell6(.ZN (seed_value[6]));
  TIELBWP7T tie_0_cell7(.ZN (step_en));
endmodule

module prbs_top_mapped(clk, rst_n, en, seed_load, seed_in, prbs_out);
  input clk, rst_n, en, seed_load;
  input [6:0] seed_in;
  output prbs_out;
  wire clk, rst_n, en, seed_load;
  wire [6:0] seed_in;
  wire prbs_out;
  wire [6:0] seed_value;
  wire [6:0] prbs_state;
  wire UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, UNCONNECTED3,
       UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7;
  wire logic_0_1_net, logic_0_2_net;
  prbs_core_LFSR_W7_DEFAULT_SEED1_mapped u_prbs_core(.clk (clk), .rst_n
       (rst_n), .load_req (seed_load), .seed_value ({seed_in[6:1],
       seed_value[0]}), .step_en (en), .prbs_out (prbs_out), .state_out
       (prbs_state));
  prbs_ctrl_LFSR_W7_DEFAULT_SEED1_mapped u_prbs_ctrl(.seed_load
       (logic_0_2_net), .seed_in (seed_in), .en (logic_0_1_net),
       .load_req (UNCONNECTED0), .seed_value ({UNCONNECTED6,
       UNCONNECTED5, UNCONNECTED4, UNCONNECTED3, UNCONNECTED2,
       UNCONNECTED1, seed_value[0]}), .step_en (UNCONNECTED7));
  TIELBWP7T tie_0_cell(.ZN (logic_0_1_net));
  TIELBWP7T tie_0_cell1(.ZN (logic_0_2_net));
endmodule

module CLKGATE_RC_CG_MOD_3_mapped(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP7T RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module prbs15_core_LFSR_W15_DEFAULT_SEED1_mapped(clk, rst_n, load_req,
     seed_value, step_en, prbs_out, state_out);
  input clk, rst_n, load_req, step_en;
  input [14:0] seed_value;
  output prbs_out;
  output [14:0] state_out;
  wire clk, rst_n, load_req, step_en;
  wire [14:0] seed_value;
  wire prbs_out;
  wire [14:0] state_out;
  wire [14:0] lfsr_q;
  wire CLKGATE_rc_gclk, UNCONNECTED8, logic_0_1_net, n_0, n_1, n_2,
       n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_18;
  CLKGATE_RC_CG_MOD_3_mapped CLKGATE_RC_CG_HIER_INST3(.enable (n_18),
       .ck_in (clk), .ck_out (CLKGATE_rc_gclk), .test (logic_0_1_net));
  DFKCNQD1BWP7T \lfsr_q_reg[12] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_16), .Q (lfsr_q[12]));
  CKMUX2D1BWP7T g308__8246(.I0 (lfsr_q[11]), .I1 (seed_value[12]), .S
       (load_req), .Z (n_16));
  DFKCNQD1BWP7T \lfsr_q_reg[11] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_15), .Q (lfsr_q[11]));
  CKMUX2D1BWP7T g310__7098(.I0 (lfsr_q[10]), .I1 (seed_value[11]), .S
       (load_req), .Z (n_15));
  DFKCNQD1BWP7T \lfsr_q_reg[10] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_14), .Q (lfsr_q[10]));
  CKMUX2D1BWP7T g312__6131(.I0 (lfsr_q[9]), .I1 (seed_value[10]), .S
       (load_req), .Z (n_14));
  DFKCNQD1BWP7T \lfsr_q_reg[9] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_13), .Q (lfsr_q[9]));
  CKMUX2D1BWP7T g314__1881(.I0 (lfsr_q[8]), .I1 (seed_value[9]), .S
       (load_req), .Z (n_13));
  DFKCNQD1BWP7T \lfsr_q_reg[8] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_12), .Q (lfsr_q[8]));
  CKMUX2D1BWP7T g316__5115(.I0 (lfsr_q[7]), .I1 (seed_value[8]), .S
       (load_req), .Z (n_12));
  DFKCNQD1BWP7T \lfsr_q_reg[7] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_11), .Q (lfsr_q[7]));
  CKMUX2D1BWP7T g318__7482(.I0 (lfsr_q[6]), .I1 (seed_value[7]), .S
       (load_req), .Z (n_11));
  DFKCNQD1BWP7T \lfsr_q_reg[6] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_10), .Q (lfsr_q[6]));
  CKMUX2D1BWP7T g320__4733(.I0 (lfsr_q[5]), .I1 (seed_value[6]), .S
       (load_req), .Z (n_10));
  DFKCNQD1BWP7T \lfsr_q_reg[5] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_9), .Q (lfsr_q[5]));
  CKMUX2D1BWP7T g322__6161(.I0 (lfsr_q[4]), .I1 (seed_value[5]), .S
       (load_req), .Z (n_9));
  DFKCNQD1BWP7T \lfsr_q_reg[4] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_8), .Q (lfsr_q[4]));
  CKMUX2D1BWP7T g324__9315(.I0 (lfsr_q[3]), .I1 (seed_value[4]), .S
       (load_req), .Z (n_8));
  DFKCNQD1BWP7T \lfsr_q_reg[3] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_7), .Q (lfsr_q[3]));
  CKMUX2D1BWP7T g326__9945(.I0 (lfsr_q[2]), .I1 (seed_value[3]), .S
       (load_req), .Z (n_7));
  DFKCNQD1BWP7T \lfsr_q_reg[2] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_6), .Q (lfsr_q[2]));
  CKMUX2D1BWP7T g328__2883(.I0 (lfsr_q[1]), .I1 (seed_value[2]), .S
       (load_req), .Z (n_6));
  DFKCNQD1BWP7T \lfsr_q_reg[1] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_5), .Q (lfsr_q[1]));
  IND3D0BWP7T g330__2346(.A1 (step_en), .B1 (rst_n), .B2 (n_4), .ZN
       (n_18));
  CKMUX2D1BWP7T g331__1666(.I0 (lfsr_q[0]), .I1 (seed_value[1]), .S
       (load_req), .Z (n_5));
  INVD2BWP7T g332(.I (load_req), .ZN (n_4));
  DFKSND1BWP7T \lfsr_q_reg[0] (.CP (CLKGATE_rc_gclk), .D (n_3), .SN
       (rst_n), .Q (lfsr_q[0]), .QN (UNCONNECTED8));
  CKMUX2D1BWP7T g215__7410(.I0 (n_2), .I1 (seed_value[0]), .S
       (load_req), .Z (n_3));
  CKXOR2D1BWP7T g216__6417(.A1 (lfsr_q[13]), .A2 (prbs_out), .Z (n_2));
  DFKCNQD1BWP7T \lfsr_q_reg[13] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_1), .Q (lfsr_q[13]));
  DFKCNQD1BWP7T \lfsr_q_reg[14] (.CP (CLKGATE_rc_gclk), .CN (rst_n), .D
       (n_0), .Q (prbs_out));
  CKMUX2D1BWP7T g218__5477(.I0 (lfsr_q[12]), .I1 (seed_value[13]), .S
       (load_req), .Z (n_1));
  CKMUX2D1BWP7T g219__2398(.I0 (lfsr_q[13]), .I1 (seed_value[14]), .S
       (load_req), .Z (n_0));
  TIELBWP7T tie_0_cell(.ZN (logic_0_1_net));
  TIELBWP7T tie_0_cell1(.ZN (state_out[0]));
  TIELBWP7T tie_0_cell2(.ZN (state_out[10]));
  TIELBWP7T tie_0_cell3(.ZN (state_out[11]));
  TIELBWP7T tie_0_cell4(.ZN (state_out[12]));
  TIELBWP7T tie_0_cell5(.ZN (state_out[13]));
  TIELBWP7T tie_0_cell6(.ZN (state_out[14]));
  TIELBWP7T tie_0_cell7(.ZN (state_out[1]));
  TIELBWP7T tie_0_cell8(.ZN (state_out[2]));
  TIELBWP7T tie_0_cell9(.ZN (state_out[3]));
  TIELBWP7T tie_0_cell10(.ZN (state_out[4]));
  TIELBWP7T tie_0_cell11(.ZN (state_out[5]));
  TIELBWP7T tie_0_cell12(.ZN (state_out[6]));
  TIELBWP7T tie_0_cell13(.ZN (state_out[7]));
  TIELBWP7T tie_0_cell14(.ZN (state_out[8]));
  TIELBWP7T tie_0_cell15(.ZN (state_out[9]));
endmodule

module prbs15_ctrl_LFSR_W15_DEFAULT_SEED1_mapped(seed_load, seed_in,
     en, load_req, seed_value, step_en);
  input seed_load, en;
  input [14:0] seed_in;
  output load_req, step_en;
  output [14:0] seed_value;
  wire seed_load, en;
  wire [14:0] seed_in;
  wire load_req, step_en;
  wire [14:0] seed_value;
  wire n_1, n_2, n_3, n_4, n_5;
  OR2D0BWP7T g261__5107(.A1 (n_5), .A2 (seed_in[0]), .Z
       (seed_value[0]));
  NR4D0BWP7T g262__6260(.A1 (n_4), .A2 (seed_in[7]), .A3 (seed_in[5]),
       .A4 (seed_in[3]), .ZN (n_5));
  IND4D0BWP7T g263__4319(.A1 (seed_in[9]), .B1 (n_1), .B2 (n_3), .B3
       (n_2), .ZN (n_4));
  NR4D0BWP7T g264__8428(.A1 (seed_in[14]), .A2 (seed_in[10]), .A3
       (seed_in[4]), .A4 (seed_in[2]), .ZN (n_3));
  NR4D0BWP7T g265__5526(.A1 (seed_in[13]), .A2 (seed_in[11]), .A3
       (seed_in[6]), .A4 (seed_in[1]), .ZN (n_2));
  NR2D0BWP7T g266__6783(.A1 (seed_in[12]), .A2 (seed_in[8]), .ZN (n_1));
  TIELBWP7T tie_0_cell(.ZN (load_req));
  TIELBWP7T tie_0_cell1(.ZN (seed_value[10]));
  TIELBWP7T tie_0_cell2(.ZN (seed_value[11]));
  TIELBWP7T tie_0_cell3(.ZN (seed_value[12]));
  TIELBWP7T tie_0_cell4(.ZN (seed_value[13]));
  TIELBWP7T tie_0_cell5(.ZN (seed_value[14]));
  TIELBWP7T tie_0_cell6(.ZN (seed_value[1]));
  TIELBWP7T tie_0_cell7(.ZN (seed_value[2]));
  TIELBWP7T tie_0_cell8(.ZN (seed_value[3]));
  TIELBWP7T tie_0_cell9(.ZN (seed_value[4]));
  TIELBWP7T tie_0_cell10(.ZN (seed_value[5]));
  TIELBWP7T tie_0_cell11(.ZN (seed_value[6]));
  TIELBWP7T tie_0_cell12(.ZN (seed_value[7]));
  TIELBWP7T tie_0_cell13(.ZN (seed_value[8]));
  TIELBWP7T tie_0_cell14(.ZN (seed_value[9]));
  TIELBWP7T tie_0_cell15(.ZN (step_en));
endmodule

module prbs15_top_mapped(clk, rst_n, en, seed_load, seed_in, prbs_out);
  input clk, rst_n, en, seed_load;
  input [14:0] seed_in;
  output prbs_out;
  wire clk, rst_n, en, seed_load;
  wire [14:0] seed_in;
  wire prbs_out;
  wire [14:0] seed_value;
  wire [14:0] prbs_state;
  wire UNCONNECTED9, UNCONNECTED10, UNCONNECTED11, UNCONNECTED12,
       UNCONNECTED13, UNCONNECTED14, UNCONNECTED15, UNCONNECTED16;
  wire UNCONNECTED17, UNCONNECTED18, UNCONNECTED19, UNCONNECTED20,
       UNCONNECTED21, UNCONNECTED22, UNCONNECTED23, UNCONNECTED24;
  wire logic_0_1_net, logic_0_2_net;
  prbs15_core_LFSR_W15_DEFAULT_SEED1_mapped u_prbs15_core(.clk (clk),
       .rst_n (rst_n), .load_req (seed_load), .seed_value
       ({seed_in[14:1], seed_value[0]}), .step_en (en), .prbs_out
       (prbs_out), .state_out (prbs_state));
  prbs15_ctrl_LFSR_W15_DEFAULT_SEED1_mapped u_prbs15_ctrl(.seed_load
       (logic_0_2_net), .seed_in (seed_in), .en (logic_0_1_net),
       .load_req (UNCONNECTED9), .seed_value ({UNCONNECTED23,
       UNCONNECTED22, UNCONNECTED21, UNCONNECTED20, UNCONNECTED19,
       UNCONNECTED18, UNCONNECTED17, UNCONNECTED16, UNCONNECTED15,
       UNCONNECTED14, UNCONNECTED13, UNCONNECTED12, UNCONNECTED11,
       UNCONNECTED10, seed_value[0]}), .step_en (UNCONNECTED24));
  TIELBWP7T tie_0_cell(.ZN (logic_0_1_net));
  TIELBWP7T tie_0_cell1(.ZN (logic_0_2_net));
endmodule

module prbs_gen_top_mapped(clk, rst_n, en, seed_load, mode_select,
     seed_in, prbs_out);
  input clk, rst_n, en, seed_load, mode_select;
  input [14:0] seed_in;
  output prbs_out;
  wire clk, rst_n, en, seed_load, mode_select;
  wire [14:0] seed_in;
  wire prbs_out;
  wire n_0, n_13, n_14, n_22, n_23, prbs7_out, prbs15_out;
  prbs_top_mapped u_prbs7_top(.clk (clk), .rst_n (rst_n), .en (n_23),
       .seed_load (n_22), .seed_in (seed_in[6:0]), .prbs_out
       (prbs7_out));
  prbs15_top_mapped u_prbs15_top(.clk (clk), .rst_n (rst_n), .en
       (n_14), .seed_load (n_13), .seed_in (seed_in), .prbs_out
       (prbs15_out));
  MUX2D1BWP7T g90__3680(.I0 (prbs7_out), .I1 (prbs15_out), .S
       (mode_select), .Z (prbs_out));
  CKAN2D1BWP7T g91__1617(.A1 (n_0), .A2 (seed_load), .Z (n_22));
  INR2D0BWP7T g92__2802(.A1 (en), .B1 (mode_select), .ZN (n_23));
  INR2D0BWP7T g93__1705(.A1 (en), .B1 (n_0), .ZN (n_14));
  CKAN2D1BWP7T g94__5122(.A1 (seed_load), .A2 (mode_select), .Z (n_13));
  INVD1BWP7T g95(.I (mode_select), .ZN (n_0));
endmodule

module ber_checker_top(clk, rst_n, en, clear_count, seed_load,
     mode_select, seed_in, serial_in, ref_bit, bit_error, error_count,
     total_count);
  input clk, rst_n, en, clear_count, seed_load, mode_select, serial_in;
  input [14:0] seed_in;
  output ref_bit, bit_error;
  output [31:0] error_count, total_count;
  wire clk, rst_n, en, clear_count, seed_load, mode_select, serial_in;
  wire [14:0] seed_in;
  wire ref_bit, bit_error;
  wire [31:0] error_count, total_count;
  wire CLKGATE_rc_gclk, CLKGATE_rc_gclk_827, inc_add_41_40_n_0,
       inc_add_41_40_n_1, inc_add_41_40_n_2, inc_add_41_40_n_3,
       inc_add_41_40_n_4, inc_add_41_40_n_5;
  wire inc_add_41_40_n_6, inc_add_41_40_n_7, inc_add_41_40_n_9,
       inc_add_41_40_n_10, inc_add_41_40_n_11, inc_add_41_40_n_12,
       inc_add_41_40_n_13, inc_add_41_40_n_14;
  wire inc_add_41_40_n_15, inc_add_41_40_n_16, inc_add_41_40_n_18,
       inc_add_41_40_n_19, inc_add_41_40_n_20, inc_add_41_40_n_23,
       inc_add_41_40_n_24, inc_add_41_40_n_27;
  wire inc_add_41_40_n_28, inc_add_41_40_n_29, inc_add_41_40_n_32,
       inc_add_41_40_n_33, inc_add_41_40_n_34, inc_add_41_40_n_36,
       inc_add_41_40_n_37, inc_add_41_40_n_39;
  wire inc_add_41_40_n_42, inc_add_41_40_n_43, inc_add_41_40_n_45,
       inc_add_41_40_n_48, inc_add_41_40_n_49, inc_add_41_40_n_51,
       inc_add_41_40_n_54, inc_add_41_40_n_56;
  wire inc_add_41_40_n_60, inc_add_41_40_n_62, inc_add_41_40_n_65,
       inc_add_41_40_n_69, inc_add_43_44_n_0, inc_add_43_44_n_1,
       inc_add_43_44_n_2, inc_add_43_44_n_3;
  wire inc_add_43_44_n_4, inc_add_43_44_n_5, inc_add_43_44_n_6,
       inc_add_43_44_n_7, inc_add_43_44_n_9, inc_add_43_44_n_10,
       inc_add_43_44_n_11, inc_add_43_44_n_12;
  wire inc_add_43_44_n_13, inc_add_43_44_n_14, inc_add_43_44_n_15,
       inc_add_43_44_n_16, inc_add_43_44_n_18, inc_add_43_44_n_19,
       inc_add_43_44_n_20, inc_add_43_44_n_23;
  wire inc_add_43_44_n_24, inc_add_43_44_n_27, inc_add_43_44_n_28,
       inc_add_43_44_n_29, inc_add_43_44_n_32, inc_add_43_44_n_33,
       inc_add_43_44_n_34, inc_add_43_44_n_36;
  wire inc_add_43_44_n_37, inc_add_43_44_n_39, inc_add_43_44_n_42,
       inc_add_43_44_n_43, inc_add_43_44_n_45, inc_add_43_44_n_48,
       inc_add_43_44_n_49, inc_add_43_44_n_51;
  wire inc_add_43_44_n_54, inc_add_43_44_n_56, inc_add_43_44_n_60,
       inc_add_43_44_n_62, inc_add_43_44_n_65, inc_add_43_44_n_69,
       logic_0_1_net, logic_0_2_net;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131;
  CLKGATE_RC_CG_MOD_mapped CLKGATE_RC_CG_HIER_INST0(.enable (n_69),
       .ck_in (clk), .ck_out (CLKGATE_rc_gclk), .test (logic_0_1_net));
  CLKGATE_RC_CG_MOD_1_mapped CLKGATE_RC_CG_HIER_INST1(.enable (n_68),
       .ck_in (clk), .ck_out (CLKGATE_rc_gclk_827), .test
       (logic_0_2_net));
  prbs_gen_top_mapped u_prbs_gen_top(.clk (clk), .rst_n (rst_n), .en
       (en), .seed_load (seed_load), .mode_select (mode_select),
       .seed_in (seed_in), .prbs_out (ref_bit));
  OR2D1BWP7T g605__8246(.A1 (bit_error), .A2 (n_64), .Z (n_69));
  CKAN2D1BWP7T g606__7098(.A1 (n_65), .A2 (en), .Z (bit_error));
  OR2D0BWP7T g607__6131(.A1 (n_64), .A2 (en), .Z (n_68));
  CKXOR2D1BWP7T g608__1881(.A1 (ref_bit), .A2 (serial_in), .Z (n_65));
  IND2D0BWP7T g609__5115(.A1 (clear_count), .B1 (rst_n), .ZN (n_64));
  DFKCNQD1BWP7T \error_count_reg[0] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_53), .Q (error_count[0]));
  DFKCNQD1BWP7T \error_count_reg[1] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_51), .Q (error_count[1]));
  DFKCNQD1BWP7T \error_count_reg[2] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_13), .Q (error_count[2]));
  DFKCNQD1BWP7T \error_count_reg[3] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_25), .Q (error_count[3]));
  DFKCNQD1BWP7T \error_count_reg[4] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_63), .Q (error_count[4]));
  DFKCNQD1BWP7T \error_count_reg[5] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_54), .Q (error_count[5]));
  DFKCNQD1BWP7T \error_count_reg[6] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_40), .Q (error_count[6]));
  DFKCNQD1BWP7T \error_count_reg[7] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_36), .Q (error_count[7]));
  DFKCNQD1BWP7T \error_count_reg[8] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_41), .Q (error_count[8]));
  DFKCNQD1BWP7T \error_count_reg[9] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_37), .Q (error_count[9]));
  DFKCNQD1BWP7T \error_count_reg[10] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_38), .Q (error_count[10]));
  DFKCNQD1BWP7T \error_count_reg[11] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_35), .Q (error_count[11]));
  DFKCNQD1BWP7T \error_count_reg[12] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_34), .Q (error_count[12]));
  DFKCNQD1BWP7T \error_count_reg[13] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_33), .Q (error_count[13]));
  DFKCNQD1BWP7T \error_count_reg[14] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_42), .Q (error_count[14]));
  DFKCNQD1BWP7T \error_count_reg[15] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_30), .Q (error_count[15]));
  DFKCNQD1BWP7T \error_count_reg[16] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_29), .Q (error_count[16]));
  DFKCNQD1BWP7T \error_count_reg[17] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_27), .Q (error_count[17]));
  DFKCNQD1BWP7T \error_count_reg[18] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_26), .Q (error_count[18]));
  DFKCNQD1BWP7T \error_count_reg[19] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_24), .Q (error_count[19]));
  DFKCNQD1BWP7T \error_count_reg[20] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_22), .Q (error_count[20]));
  DFKCNQD1BWP7T \error_count_reg[21] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_23), .Q (error_count[21]));
  DFKCNQD1BWP7T \error_count_reg[22] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_21), .Q (error_count[22]));
  DFKCNQD1BWP7T \error_count_reg[23] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_18), .Q (error_count[23]));
  DFKCNQD1BWP7T \error_count_reg[24] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_17), .Q (error_count[24]));
  DFKCNQD1BWP7T \error_count_reg[25] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_16), .Q (error_count[25]));
  DFKCNQD1BWP7T \error_count_reg[26] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_31), .Q (error_count[26]));
  DFKCNQD1BWP7T \error_count_reg[27] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_20), .Q (error_count[27]));
  DFKCNQD1BWP7T \error_count_reg[28] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_12), .Q (error_count[28]));
  DFKCNQD1BWP7T \error_count_reg[29] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_11), .Q (error_count[29]));
  DFKCNQD1BWP7T \error_count_reg[30] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_15), .Q (error_count[30]));
  DFKCNQD1BWP7T \error_count_reg[31] (.CP (CLKGATE_rc_gclk), .CN
       (rst_n), .D (n_9), .Q (error_count[31]));
  DFKCNQD1BWP7T \total_count_reg[0] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_8), .Q (total_count[0]));
  DFKCNQD1BWP7T \total_count_reg[1] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_7), .Q (total_count[1]));
  DFKCNQD1BWP7T \total_count_reg[2] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_6), .Q (total_count[2]));
  DFKCNQD1BWP7T \total_count_reg[3] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_5), .Q (total_count[3]));
  DFKCNQD1BWP7T \total_count_reg[4] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_4), .Q (total_count[4]));
  DFKCNQD1BWP7T \total_count_reg[5] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_3), .Q (total_count[5]));
  DFKCNQD1BWP7T \total_count_reg[6] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_2), .Q (total_count[6]));
  DFKCNQD1BWP7T \total_count_reg[7] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_1), .Q (total_count[7]));
  DFKCNQD1BWP7T \total_count_reg[8] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_0), .Q (total_count[8]));
  DFKCNQD1BWP7T \total_count_reg[9] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_62), .Q (total_count[9]));
  DFKCNQD1BWP7T \total_count_reg[10] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_61), .Q (total_count[10]));
  DFKCNQD1BWP7T \total_count_reg[11] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_58), .Q (total_count[11]));
  DFKCNQD1BWP7T \total_count_reg[12] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_57), .Q (total_count[12]));
  DFKCNQD1BWP7T \total_count_reg[13] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_56), .Q (total_count[13]));
  DFKCNQD1BWP7T \total_count_reg[14] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_55), .Q (total_count[14]));
  DFKCNQD1BWP7T \total_count_reg[15] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_52), .Q (total_count[15]));
  DFKCNQD1BWP7T \total_count_reg[16] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_10), .Q (total_count[16]));
  DFKCNQD1BWP7T \total_count_reg[17] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_19), .Q (total_count[17]));
  DFKCNQD1BWP7T \total_count_reg[18] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_47), .Q (total_count[18]));
  DFKCNQD1BWP7T \total_count_reg[19] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_28), .Q (total_count[19]));
  DFKCNQD1BWP7T \total_count_reg[20] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_49), .Q (total_count[20]));
  DFKCNQD1BWP7T \total_count_reg[21] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_32), .Q (total_count[21]));
  DFKCNQD1BWP7T \total_count_reg[22] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_46), .Q (total_count[22]));
  DFKCNQD1BWP7T \total_count_reg[23] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_44), .Q (total_count[23]));
  DFKCNQD1BWP7T \total_count_reg[24] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_39), .Q (total_count[24]));
  DFKCNQD1BWP7T \total_count_reg[25] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_43), .Q (total_count[25]));
  DFKCNQD1BWP7T \total_count_reg[26] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_48), .Q (total_count[26]));
  DFKCNQD1BWP7T \total_count_reg[27] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_45), .Q (total_count[27]));
  DFKCNQD1BWP7T \total_count_reg[28] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_60), .Q (total_count[28]));
  DFKCNQD1BWP7T \total_count_reg[29] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_50), .Q (total_count[29]));
  DFKCNQD1BWP7T \total_count_reg[30] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_14), .Q (total_count[30]));
  DFKCNQD1BWP7T \total_count_reg[31] (.CP (CLKGATE_rc_gclk_827), .CN
       (rst_n), .D (n_59), .Q (total_count[31]));
  INR2D1BWP7T g1084__7482(.A1 (n_104), .B1 (clear_count), .ZN (n_63));
  INR2D1BWP7T g1085__4733(.A1 (n_78), .B1 (clear_count), .ZN (n_62));
  INR2D1BWP7T g1086__6161(.A1 (n_79), .B1 (clear_count), .ZN (n_61));
  INR2D1BWP7T g1087__9315(.A1 (n_97), .B1 (clear_count), .ZN (n_60));
  INR2D1BWP7T g1088__9945(.A1 (n_100), .B1 (clear_count), .ZN (n_59));
  INR2D1BWP7T g1089__2883(.A1 (n_80), .B1 (clear_count), .ZN (n_58));
  INR2D1BWP7T g1090__2346(.A1 (n_81), .B1 (clear_count), .ZN (n_57));
  INR2D1BWP7T g1091__1666(.A1 (n_82), .B1 (clear_count), .ZN (n_56));
  INR2D1BWP7T g1092__7410(.A1 (n_83), .B1 (clear_count), .ZN (n_55));
  INR2D1BWP7T g1093__6417(.A1 (n_105), .B1 (clear_count), .ZN (n_54));
  NR2XD0BWP7T g1094__5477(.A1 (error_count[0]), .A2 (clear_count), .ZN
       (n_53));
  INR2D1BWP7T g1095__2398(.A1 (n_84), .B1 (clear_count), .ZN (n_52));
  INR2D1BWP7T g1096__5107(.A1 (n_101), .B1 (clear_count), .ZN (n_51));
  INR2D1BWP7T g1097__6260(.A1 (n_98), .B1 (clear_count), .ZN (n_50));
  INR2D1BWP7T g1098__4319(.A1 (n_89), .B1 (clear_count), .ZN (n_49));
  INR2D1BWP7T g1099__8428(.A1 (n_95), .B1 (clear_count), .ZN (n_48));
  INR2D1BWP7T g1100__5526(.A1 (n_87), .B1 (clear_count), .ZN (n_47));
  INR2D1BWP7T g1101__6783(.A1 (n_91), .B1 (clear_count), .ZN (n_46));
  INR2D1BWP7T g1102__3680(.A1 (n_96), .B1 (clear_count), .ZN (n_45));
  INR2D1BWP7T g1103__1617(.A1 (n_92), .B1 (clear_count), .ZN (n_44));
  INR2D1BWP7T g1104__2802(.A1 (n_94), .B1 (clear_count), .ZN (n_43));
  INR2D1BWP7T g1105__1705(.A1 (n_114), .B1 (clear_count), .ZN (n_42));
  INR2D1BWP7T g1106__5122(.A1 (n_108), .B1 (clear_count), .ZN (n_41));
  INR2D1BWP7T g1107__8246(.A1 (n_106), .B1 (clear_count), .ZN (n_40));
  INR2D1BWP7T g1108__7098(.A1 (n_93), .B1 (clear_count), .ZN (n_39));
  INR2D1BWP7T g1109__6131(.A1 (n_110), .B1 (clear_count), .ZN (n_38));
  INR2D1BWP7T g1110__1881(.A1 (n_109), .B1 (clear_count), .ZN (n_37));
  INR2D1BWP7T g1111__5115(.A1 (n_107), .B1 (clear_count), .ZN (n_36));
  INR2D1BWP7T g1112__7482(.A1 (n_111), .B1 (clear_count), .ZN (n_35));
  INR2D1BWP7T g1113__4733(.A1 (n_112), .B1 (clear_count), .ZN (n_34));
  INR2D1BWP7T g1114__6161(.A1 (n_113), .B1 (clear_count), .ZN (n_33));
  INR2D1BWP7T g1115__9315(.A1 (n_90), .B1 (clear_count), .ZN (n_32));
  INR2D1BWP7T g1116__9945(.A1 (n_126), .B1 (clear_count), .ZN (n_31));
  INR2D1BWP7T g1117__2883(.A1 (n_115), .B1 (clear_count), .ZN (n_30));
  INR2D1BWP7T g1118__2346(.A1 (n_116), .B1 (clear_count), .ZN (n_29));
  INR2D1BWP7T g1119__1666(.A1 (n_88), .B1 (clear_count), .ZN (n_28));
  INR2D1BWP7T g1120__7410(.A1 (n_117), .B1 (clear_count), .ZN (n_27));
  INR2D1BWP7T g1121__6417(.A1 (n_118), .B1 (clear_count), .ZN (n_26));
  INR2D1BWP7T g1122__5477(.A1 (n_103), .B1 (clear_count), .ZN (n_25));
  INR2D1BWP7T g1123__2398(.A1 (n_119), .B1 (clear_count), .ZN (n_24));
  INR2D1BWP7T g1124__5107(.A1 (n_121), .B1 (clear_count), .ZN (n_23));
  INR2D1BWP7T g1125__6260(.A1 (n_120), .B1 (clear_count), .ZN (n_22));
  INR2D1BWP7T g1126__4319(.A1 (n_122), .B1 (clear_count), .ZN (n_21));
  INR2D1BWP7T g1127__8428(.A1 (n_127), .B1 (clear_count), .ZN (n_20));
  INR2D1BWP7T g1128__5526(.A1 (n_86), .B1 (clear_count), .ZN (n_19));
  INR2D1BWP7T g1129__6783(.A1 (n_123), .B1 (clear_count), .ZN (n_18));
  INR2D1BWP7T g1130__3680(.A1 (n_124), .B1 (clear_count), .ZN (n_17));
  INR2D1BWP7T g1131__1617(.A1 (n_125), .B1 (clear_count), .ZN (n_16));
  INR2D1BWP7T g1132__2802(.A1 (n_130), .B1 (clear_count), .ZN (n_15));
  INR2D1BWP7T g1133__1705(.A1 (n_99), .B1 (clear_count), .ZN (n_14));
  INR2D1BWP7T g1134__5122(.A1 (n_102), .B1 (clear_count), .ZN (n_13));
  INR2D1BWP7T g1135__8246(.A1 (n_128), .B1 (clear_count), .ZN (n_12));
  INR2D1BWP7T g1136__7098(.A1 (n_129), .B1 (clear_count), .ZN (n_11));
  INR2D1BWP7T g1137__6131(.A1 (n_85), .B1 (clear_count), .ZN (n_10));
  INR2D1BWP7T g1138__1881(.A1 (n_131), .B1 (clear_count), .ZN (n_9));
  NR2XD0BWP7T g1139__5115(.A1 (total_count[0]), .A2 (clear_count), .ZN
       (n_8));
  INR2D1BWP7T g1140__7482(.A1 (n_70), .B1 (clear_count), .ZN (n_7));
  INR2D1BWP7T g1141__4733(.A1 (n_71), .B1 (clear_count), .ZN (n_6));
  INR2D1BWP7T g1142__6161(.A1 (n_72), .B1 (clear_count), .ZN (n_5));
  INR2D1BWP7T g1143__9315(.A1 (n_73), .B1 (clear_count), .ZN (n_4));
  INR2D1BWP7T g1144__9945(.A1 (n_74), .B1 (clear_count), .ZN (n_3));
  INR2D1BWP7T g1145__2883(.A1 (n_75), .B1 (clear_count), .ZN (n_2));
  INR2D1BWP7T g1146__2346(.A1 (n_76), .B1 (clear_count), .ZN (n_1));
  INR2D1BWP7T g1147__1666(.A1 (n_77), .B1 (clear_count), .ZN (n_0));
  CKXOR2D1BWP7T inc_add_41_40_g479__7410(.A1 (inc_add_41_40_n_69), .A2
       (total_count[19]), .Z (n_88));
  XOR2D1BWP7T inc_add_41_40_g480__6417(.A1 (inc_add_41_40_n_65), .A2
       (total_count[31]), .Z (n_100));
  HA1D0BWP7T inc_add_41_40_g481__5477(.A (total_count[18]), .B
       (inc_add_41_40_n_56), .CO (inc_add_41_40_n_69), .S (n_87));
  CKXOR2D1BWP7T inc_add_41_40_g482__2398(.A1 (inc_add_41_40_n_62), .A2
       (total_count[29]), .Z (n_98));
  CKXOR2D1BWP7T inc_add_41_40_g483__5107(.A1 (inc_add_41_40_n_60), .A2
       (total_count[11]), .Z (n_80));
  HA1D1BWP7T inc_add_41_40_g484__6260(.A (total_count[30]), .B
       (inc_add_41_40_n_48), .CO (inc_add_41_40_n_65), .S (n_99));
  CKXOR2D1BWP7T inc_add_41_40_g485__4319(.A1 (inc_add_41_40_n_54), .A2
       (total_count[27]), .Z (n_96));
  HA1D0BWP7T inc_add_41_40_g486__8428(.A (total_count[28]), .B
       (inc_add_41_40_n_42), .CO (inc_add_41_40_n_62), .S (n_97));
  HA1D0BWP7T inc_add_41_40_g487__5526(.A (total_count[10]), .B
       (inc_add_41_40_n_43), .CO (inc_add_41_40_n_60), .S (n_79));
  CKXOR2D1BWP7T inc_add_41_40_g488__6783(.A1 (inc_add_41_40_n_51), .A2
       (total_count[25]), .Z (n_94));
  CKXOR2D1BWP7T inc_add_41_40_g489__3680(.A1 (inc_add_41_40_n_49), .A2
       (total_count[23]), .Z (n_92));
  HA1D0BWP7T inc_add_41_40_g490__1617(.A (total_count[17]), .B
       (inc_add_41_40_n_39), .CO (inc_add_41_40_n_56), .S (n_86));
  HA1D0BWP7T inc_add_41_40_g491__2802(.A (total_count[26]), .B
       (inc_add_41_40_n_36), .CO (inc_add_41_40_n_54), .S (n_95));
  CKXOR2D1BWP7T inc_add_41_40_g492__1705(.A1 (inc_add_41_40_n_45), .A2
       (total_count[21]), .Z (n_90));
  HA1D0BWP7T inc_add_41_40_g493__5122(.A (total_count[24]), .B
       (inc_add_41_40_n_32), .CO (inc_add_41_40_n_51), .S (n_93));
  HA1D0BWP7T inc_add_41_40_g494__8246(.A (total_count[22]), .B
       (inc_add_41_40_n_33), .CO (inc_add_41_40_n_49), .S (n_91));
  AN3XD1BWP7T inc_add_41_40_g495__7098(.A1 (inc_add_41_40_n_42), .A2
       (total_count[29]), .A3 (total_count[28]), .Z
       (inc_add_41_40_n_48));
  CKXOR2D1BWP7T inc_add_41_40_g496__6131(.A1 (inc_add_41_40_n_37), .A2
       (total_count[15]), .Z (n_84));
  HA1D0BWP7T inc_add_41_40_g497__1881(.A (total_count[20]), .B
       (inc_add_41_40_n_28), .CO (inc_add_41_40_n_45), .S (n_89));
  HA1D0BWP7T inc_add_41_40_g498__5115(.A (total_count[9]), .B
       (inc_add_41_40_n_29), .CO (inc_add_41_40_n_43), .S (n_78));
  AN3D1BWP7T inc_add_41_40_g499__7482(.A1 (inc_add_41_40_n_36), .A2
       (total_count[27]), .A3 (total_count[26]), .Z
       (inc_add_41_40_n_42));
  CKXOR2D1BWP7T inc_add_41_40_g500__4733(.A1 (inc_add_41_40_n_34), .A2
       (total_count[13]), .Z (n_82));
  HA1D0BWP7T inc_add_41_40_g501__6161(.A (total_count[16]), .B
       (inc_add_41_40_n_0), .CO (inc_add_41_40_n_39), .S (n_85));
  HA1D0BWP7T inc_add_41_40_g502__9315(.A (total_count[14]), .B
       (inc_add_41_40_n_23), .CO (inc_add_41_40_n_37), .S (n_83));
  AN3D1BWP7T inc_add_41_40_g503__9945(.A1 (inc_add_41_40_n_32), .A2
       (total_count[25]), .A3 (total_count[24]), .Z
       (inc_add_41_40_n_36));
  HA1D0BWP7T inc_add_41_40_g504__2883(.A (total_count[12]), .B
       (inc_add_41_40_n_19), .CO (inc_add_41_40_n_34), .S (n_81));
  CKAN2D1BWP7T inc_add_41_40_g505__2346(.A1 (inc_add_41_40_n_28), .A2
       (inc_add_41_40_n_4), .Z (inc_add_41_40_n_33));
  NR2D1BWP7T inc_add_41_40_g506__1666(.A1 (inc_add_41_40_n_27), .A2
       (inc_add_41_40_n_9), .ZN (inc_add_41_40_n_32));
  CKXOR2D1BWP7T inc_add_41_40_g507__7410(.A1 (inc_add_41_40_n_24), .A2
       (total_count[7]), .Z (n_76));
  HA1D0BWP7T inc_add_41_40_g508__6417(.A (total_count[8]), .B
       (inc_add_41_40_n_15), .CO (inc_add_41_40_n_29), .S (n_77));
  INVD1BWP7T inc_add_41_40_g509(.I (inc_add_41_40_n_27), .ZN
       (inc_add_41_40_n_28));
  ND2D1BWP7T inc_add_41_40_g510__5477(.A1 (inc_add_41_40_n_0), .A2
       (inc_add_41_40_n_6), .ZN (inc_add_41_40_n_27));
  CKXOR2D1BWP7T inc_add_41_40_g511__2398(.A1 (inc_add_41_40_n_20), .A2
       (total_count[5]), .Z (n_74));
  HA1D0BWP7T inc_add_41_40_g512__5107(.A (total_count[6]), .B
       (inc_add_41_40_n_14), .CO (inc_add_41_40_n_24), .S (n_75));
  INR2XD0BWP7T inc_add_41_40_g513__6260(.A1 (inc_add_41_40_n_19), .B1
       (inc_add_41_40_n_2), .ZN (inc_add_41_40_n_23));
  NR2D3BWP7T inc_add_41_40_g515__4319(.A1 (inc_add_41_40_n_18), .A2
       (inc_add_41_40_n_10), .ZN (inc_add_41_40_n_0));
  CKXOR2D1BWP7T inc_add_41_40_g516__8428(.A1 (inc_add_41_40_n_16), .A2
       (total_count[3]), .Z (n_72));
  HA1D0BWP7T inc_add_41_40_g517__5526(.A (total_count[4]), .B
       (inc_add_41_40_n_12), .CO (inc_add_41_40_n_20), .S (n_73));
  INVD1BWP7T inc_add_41_40_g518(.I (inc_add_41_40_n_18), .ZN
       (inc_add_41_40_n_19));
  ND2D2BWP7T inc_add_41_40_g519__6783(.A1 (inc_add_41_40_n_15), .A2
       (inc_add_41_40_n_7), .ZN (inc_add_41_40_n_18));
  HA1D0BWP7T inc_add_41_40_g520__3680(.A (total_count[2]), .B
       (inc_add_41_40_n_11), .CO (inc_add_41_40_n_16), .S (n_71));
  NR2D3BWP7T inc_add_41_40_g521__1617(.A1 (inc_add_41_40_n_13), .A2
       (inc_add_41_40_n_3), .ZN (inc_add_41_40_n_15));
  INVD1BWP7T inc_add_41_40_g522(.I (inc_add_41_40_n_13), .ZN
       (inc_add_41_40_n_14));
  ND3D2BWP7T inc_add_41_40_g523__2802(.A1 (inc_add_41_40_n_12), .A2
       (total_count[5]), .A3 (total_count[4]), .ZN
       (inc_add_41_40_n_13));
  NR2XD1BWP7T inc_add_41_40_g524__1705(.A1 (inc_add_41_40_n_1), .A2
       (inc_add_41_40_n_5), .ZN (inc_add_41_40_n_12));
  INVD1BWP7T inc_add_41_40_g525(.I (inc_add_41_40_n_1), .ZN
       (inc_add_41_40_n_11));
  IND3D1BWP7T inc_add_41_40_g526__5122(.A1 (inc_add_41_40_n_2), .B1
       (total_count[15]), .B2 (total_count[14]), .ZN
       (inc_add_41_40_n_10));
  ND3D0BWP7T inc_add_41_40_g527__8246(.A1 (inc_add_41_40_n_4), .A2
       (total_count[23]), .A3 (total_count[22]), .ZN
       (inc_add_41_40_n_9));
  OA21D0BWP7T inc_add_41_40_g528__7098(.A1 (total_count[0]), .A2
       (total_count[1]), .B (inc_add_41_40_n_1), .Z (n_70));
  AN4D0BWP7T inc_add_41_40_g529__6131(.A1 (total_count[11]), .A2
       (total_count[10]), .A3 (total_count[9]), .A4 (total_count[8]),
       .Z (inc_add_41_40_n_7));
  AN4D0BWP7T inc_add_41_40_g530__1881(.A1 (total_count[19]), .A2
       (total_count[18]), .A3 (total_count[17]), .A4 (total_count[16]),
       .Z (inc_add_41_40_n_6));
  ND2D1BWP7T inc_add_41_40_g531__5115(.A1 (total_count[3]), .A2
       (total_count[2]), .ZN (inc_add_41_40_n_5));
  CKAN2D1BWP7T inc_add_41_40_g532__7482(.A1 (total_count[21]), .A2
       (total_count[20]), .Z (inc_add_41_40_n_4));
  ND2D1BWP7T inc_add_41_40_g533__4733(.A1 (total_count[7]), .A2
       (total_count[6]), .ZN (inc_add_41_40_n_3));
  ND2D1BWP7T inc_add_41_40_g534__6161(.A1 (total_count[13]), .A2
       (total_count[12]), .ZN (inc_add_41_40_n_2));
  ND2D1BWP7T inc_add_41_40_g535__9315(.A1 (total_count[1]), .A2
       (total_count[0]), .ZN (inc_add_41_40_n_1));
  CKXOR2D1BWP7T inc_add_43_44_g479__9945(.A1 (inc_add_43_44_n_69), .A2
       (error_count[19]), .Z (n_119));
  XOR2D1BWP7T inc_add_43_44_g480__2883(.A1 (inc_add_43_44_n_65), .A2
       (error_count[31]), .Z (n_131));
  HA1D0BWP7T inc_add_43_44_g481__2346(.A (error_count[18]), .B
       (inc_add_43_44_n_56), .CO (inc_add_43_44_n_69), .S (n_118));
  CKXOR2D1BWP7T inc_add_43_44_g482__1666(.A1 (inc_add_43_44_n_62), .A2
       (error_count[29]), .Z (n_129));
  CKXOR2D1BWP7T inc_add_43_44_g483__7410(.A1 (inc_add_43_44_n_60), .A2
       (error_count[11]), .Z (n_111));
  HA1D1BWP7T inc_add_43_44_g484__6417(.A (error_count[30]), .B
       (inc_add_43_44_n_48), .CO (inc_add_43_44_n_65), .S (n_130));
  CKXOR2D1BWP7T inc_add_43_44_g485__5477(.A1 (inc_add_43_44_n_54), .A2
       (error_count[27]), .Z (n_127));
  HA1D0BWP7T inc_add_43_44_g486__2398(.A (error_count[28]), .B
       (inc_add_43_44_n_42), .CO (inc_add_43_44_n_62), .S (n_128));
  HA1D0BWP7T inc_add_43_44_g487__5107(.A (error_count[10]), .B
       (inc_add_43_44_n_43), .CO (inc_add_43_44_n_60), .S (n_110));
  CKXOR2D1BWP7T inc_add_43_44_g488__6260(.A1 (inc_add_43_44_n_51), .A2
       (error_count[25]), .Z (n_125));
  CKXOR2D1BWP7T inc_add_43_44_g489__4319(.A1 (inc_add_43_44_n_49), .A2
       (error_count[23]), .Z (n_123));
  HA1D0BWP7T inc_add_43_44_g490__8428(.A (error_count[17]), .B
       (inc_add_43_44_n_39), .CO (inc_add_43_44_n_56), .S (n_117));
  HA1D0BWP7T inc_add_43_44_g491__5526(.A (error_count[26]), .B
       (inc_add_43_44_n_36), .CO (inc_add_43_44_n_54), .S (n_126));
  CKXOR2D1BWP7T inc_add_43_44_g492__6783(.A1 (inc_add_43_44_n_45), .A2
       (error_count[21]), .Z (n_121));
  HA1D0BWP7T inc_add_43_44_g493__3680(.A (error_count[24]), .B
       (inc_add_43_44_n_32), .CO (inc_add_43_44_n_51), .S (n_124));
  HA1D0BWP7T inc_add_43_44_g494__1617(.A (error_count[22]), .B
       (inc_add_43_44_n_33), .CO (inc_add_43_44_n_49), .S (n_122));
  AN3XD1BWP7T inc_add_43_44_g495__2802(.A1 (inc_add_43_44_n_42), .A2
       (error_count[29]), .A3 (error_count[28]), .Z
       (inc_add_43_44_n_48));
  CKXOR2D1BWP7T inc_add_43_44_g496__1705(.A1 (inc_add_43_44_n_37), .A2
       (error_count[15]), .Z (n_115));
  HA1D0BWP7T inc_add_43_44_g497__5122(.A (error_count[20]), .B
       (inc_add_43_44_n_28), .CO (inc_add_43_44_n_45), .S (n_120));
  HA1D0BWP7T inc_add_43_44_g498__8246(.A (error_count[9]), .B
       (inc_add_43_44_n_29), .CO (inc_add_43_44_n_43), .S (n_109));
  AN3D1BWP7T inc_add_43_44_g499__7098(.A1 (inc_add_43_44_n_36), .A2
       (error_count[27]), .A3 (error_count[26]), .Z
       (inc_add_43_44_n_42));
  CKXOR2D1BWP7T inc_add_43_44_g500__6131(.A1 (inc_add_43_44_n_34), .A2
       (error_count[13]), .Z (n_113));
  HA1D0BWP7T inc_add_43_44_g501__1881(.A (error_count[16]), .B
       (inc_add_43_44_n_0), .CO (inc_add_43_44_n_39), .S (n_116));
  HA1D0BWP7T inc_add_43_44_g502__5115(.A (error_count[14]), .B
       (inc_add_43_44_n_23), .CO (inc_add_43_44_n_37), .S (n_114));
  AN3D1BWP7T inc_add_43_44_g503__7482(.A1 (inc_add_43_44_n_32), .A2
       (error_count[25]), .A3 (error_count[24]), .Z
       (inc_add_43_44_n_36));
  HA1D0BWP7T inc_add_43_44_g504__4733(.A (error_count[12]), .B
       (inc_add_43_44_n_19), .CO (inc_add_43_44_n_34), .S (n_112));
  CKAN2D1BWP7T inc_add_43_44_g505__6161(.A1 (inc_add_43_44_n_28), .A2
       (inc_add_43_44_n_4), .Z (inc_add_43_44_n_33));
  NR2D1BWP7T inc_add_43_44_g506__9315(.A1 (inc_add_43_44_n_27), .A2
       (inc_add_43_44_n_9), .ZN (inc_add_43_44_n_32));
  CKXOR2D1BWP7T inc_add_43_44_g507__9945(.A1 (inc_add_43_44_n_24), .A2
       (error_count[7]), .Z (n_107));
  HA1D0BWP7T inc_add_43_44_g508__2883(.A (error_count[8]), .B
       (inc_add_43_44_n_15), .CO (inc_add_43_44_n_29), .S (n_108));
  INVD1BWP7T inc_add_43_44_g509(.I (inc_add_43_44_n_27), .ZN
       (inc_add_43_44_n_28));
  ND2D1BWP7T inc_add_43_44_g510__2346(.A1 (inc_add_43_44_n_0), .A2
       (inc_add_43_44_n_6), .ZN (inc_add_43_44_n_27));
  CKXOR2D1BWP7T inc_add_43_44_g511__1666(.A1 (inc_add_43_44_n_20), .A2
       (error_count[5]), .Z (n_105));
  HA1D0BWP7T inc_add_43_44_g512__7410(.A (error_count[6]), .B
       (inc_add_43_44_n_14), .CO (inc_add_43_44_n_24), .S (n_106));
  INR2XD0BWP7T inc_add_43_44_g513__6417(.A1 (inc_add_43_44_n_19), .B1
       (inc_add_43_44_n_2), .ZN (inc_add_43_44_n_23));
  NR2D3BWP7T inc_add_43_44_g515__5477(.A1 (inc_add_43_44_n_18), .A2
       (inc_add_43_44_n_10), .ZN (inc_add_43_44_n_0));
  CKXOR2D1BWP7T inc_add_43_44_g516__2398(.A1 (inc_add_43_44_n_16), .A2
       (error_count[3]), .Z (n_103));
  HA1D0BWP7T inc_add_43_44_g517__5107(.A (error_count[4]), .B
       (inc_add_43_44_n_12), .CO (inc_add_43_44_n_20), .S (n_104));
  INVD1BWP7T inc_add_43_44_g518(.I (inc_add_43_44_n_18), .ZN
       (inc_add_43_44_n_19));
  ND2D2BWP7T inc_add_43_44_g519__6260(.A1 (inc_add_43_44_n_15), .A2
       (inc_add_43_44_n_7), .ZN (inc_add_43_44_n_18));
  HA1D0BWP7T inc_add_43_44_g520__4319(.A (error_count[2]), .B
       (inc_add_43_44_n_11), .CO (inc_add_43_44_n_16), .S (n_102));
  NR2D3BWP7T inc_add_43_44_g521__8428(.A1 (inc_add_43_44_n_13), .A2
       (inc_add_43_44_n_3), .ZN (inc_add_43_44_n_15));
  INVD1BWP7T inc_add_43_44_g522(.I (inc_add_43_44_n_13), .ZN
       (inc_add_43_44_n_14));
  ND3D2BWP7T inc_add_43_44_g523__5526(.A1 (inc_add_43_44_n_12), .A2
       (error_count[5]), .A3 (error_count[4]), .ZN
       (inc_add_43_44_n_13));
  NR2XD1BWP7T inc_add_43_44_g524__6783(.A1 (inc_add_43_44_n_1), .A2
       (inc_add_43_44_n_5), .ZN (inc_add_43_44_n_12));
  INVD1BWP7T inc_add_43_44_g525(.I (inc_add_43_44_n_1), .ZN
       (inc_add_43_44_n_11));
  IND3D1BWP7T inc_add_43_44_g526__3680(.A1 (inc_add_43_44_n_2), .B1
       (error_count[15]), .B2 (error_count[14]), .ZN
       (inc_add_43_44_n_10));
  ND3D0BWP7T inc_add_43_44_g527__1617(.A1 (inc_add_43_44_n_4), .A2
       (error_count[23]), .A3 (error_count[22]), .ZN
       (inc_add_43_44_n_9));
  OA21D0BWP7T inc_add_43_44_g528__2802(.A1 (error_count[0]), .A2
       (error_count[1]), .B (inc_add_43_44_n_1), .Z (n_101));
  AN4D0BWP7T inc_add_43_44_g529__1705(.A1 (error_count[11]), .A2
       (error_count[10]), .A3 (error_count[9]), .A4 (error_count[8]),
       .Z (inc_add_43_44_n_7));
  AN4D0BWP7T inc_add_43_44_g530__5122(.A1 (error_count[19]), .A2
       (error_count[18]), .A3 (error_count[17]), .A4 (error_count[16]),
       .Z (inc_add_43_44_n_6));
  ND2D1BWP7T inc_add_43_44_g531__8246(.A1 (error_count[3]), .A2
       (error_count[2]), .ZN (inc_add_43_44_n_5));
  CKAN2D1BWP7T inc_add_43_44_g532__7098(.A1 (error_count[21]), .A2
       (error_count[20]), .Z (inc_add_43_44_n_4));
  ND2D1BWP7T inc_add_43_44_g533__6131(.A1 (error_count[7]), .A2
       (error_count[6]), .ZN (inc_add_43_44_n_3));
  ND2D1BWP7T inc_add_43_44_g534__1881(.A1 (error_count[13]), .A2
       (error_count[12]), .ZN (inc_add_43_44_n_2));
  ND2D1BWP7T inc_add_43_44_g535__5115(.A1 (error_count[1]), .A2
       (error_count[0]), .ZN (inc_add_43_44_n_1));
  TIELBWP7T tie_0_cell(.ZN (logic_0_1_net));
  TIELBWP7T tie_0_cell1(.ZN (logic_0_2_net));
endmodule

