
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point ext_serial_in ext_serial_in -type PI PI
add mapped point cfg_we cfg_we -type PI PI
add mapped point cfg_re cfg_re -type PI PI
add mapped point cfg_addr[4] cfg_addr[4] -type PI PI
add mapped point cfg_addr[3] cfg_addr[3] -type PI PI
add mapped point cfg_addr[2] cfg_addr[2] -type PI PI
add mapped point cfg_addr[1] cfg_addr[1] -type PI PI
add mapped point cfg_addr[0] cfg_addr[0] -type PI PI
add mapped point cfg_wdata[31] cfg_wdata[31] -type PI PI
add mapped point cfg_wdata[30] cfg_wdata[30] -type PI PI
add mapped point cfg_wdata[29] cfg_wdata[29] -type PI PI
add mapped point cfg_wdata[28] cfg_wdata[28] -type PI PI
add mapped point cfg_wdata[27] cfg_wdata[27] -type PI PI
add mapped point cfg_wdata[26] cfg_wdata[26] -type PI PI
add mapped point cfg_wdata[25] cfg_wdata[25] -type PI PI
add mapped point cfg_wdata[24] cfg_wdata[24] -type PI PI
add mapped point cfg_wdata[23] cfg_wdata[23] -type PI PI
add mapped point cfg_wdata[22] cfg_wdata[22] -type PI PI
add mapped point cfg_wdata[21] cfg_wdata[21] -type PI PI
add mapped point cfg_wdata[20] cfg_wdata[20] -type PI PI
add mapped point cfg_wdata[19] cfg_wdata[19] -type PI PI
add mapped point cfg_wdata[18] cfg_wdata[18] -type PI PI
add mapped point cfg_wdata[17] cfg_wdata[17] -type PI PI
add mapped point cfg_wdata[16] cfg_wdata[16] -type PI PI
add mapped point cfg_wdata[15] cfg_wdata[15] -type PI PI
add mapped point cfg_wdata[14] cfg_wdata[14] -type PI PI
add mapped point cfg_wdata[13] cfg_wdata[13] -type PI PI
add mapped point cfg_wdata[12] cfg_wdata[12] -type PI PI
add mapped point cfg_wdata[11] cfg_wdata[11] -type PI PI
add mapped point cfg_wdata[10] cfg_wdata[10] -type PI PI
add mapped point cfg_wdata[9] cfg_wdata[9] -type PI PI
add mapped point cfg_wdata[8] cfg_wdata[8] -type PI PI
add mapped point cfg_wdata[7] cfg_wdata[7] -type PI PI
add mapped point cfg_wdata[6] cfg_wdata[6] -type PI PI
add mapped point cfg_wdata[5] cfg_wdata[5] -type PI PI
add mapped point cfg_wdata[4] cfg_wdata[4] -type PI PI
add mapped point cfg_wdata[3] cfg_wdata[3] -type PI PI
add mapped point cfg_wdata[2] cfg_wdata[2] -type PI PI
add mapped point cfg_wdata[1] cfg_wdata[1] -type PI PI
add mapped point cfg_wdata[0] cfg_wdata[0] -type PI PI

//output ports
add mapped point cfg_rdata[31] cfg_rdata[31] -type PO PO
add mapped point cfg_rdata[30] cfg_rdata[30] -type PO PO
add mapped point cfg_rdata[29] cfg_rdata[29] -type PO PO
add mapped point cfg_rdata[28] cfg_rdata[28] -type PO PO
add mapped point cfg_rdata[27] cfg_rdata[27] -type PO PO
add mapped point cfg_rdata[26] cfg_rdata[26] -type PO PO
add mapped point cfg_rdata[25] cfg_rdata[25] -type PO PO
add mapped point cfg_rdata[24] cfg_rdata[24] -type PO PO
add mapped point cfg_rdata[23] cfg_rdata[23] -type PO PO
add mapped point cfg_rdata[22] cfg_rdata[22] -type PO PO
add mapped point cfg_rdata[21] cfg_rdata[21] -type PO PO
add mapped point cfg_rdata[20] cfg_rdata[20] -type PO PO
add mapped point cfg_rdata[19] cfg_rdata[19] -type PO PO
add mapped point cfg_rdata[18] cfg_rdata[18] -type PO PO
add mapped point cfg_rdata[17] cfg_rdata[17] -type PO PO
add mapped point cfg_rdata[16] cfg_rdata[16] -type PO PO
add mapped point cfg_rdata[15] cfg_rdata[15] -type PO PO
add mapped point cfg_rdata[14] cfg_rdata[14] -type PO PO
add mapped point cfg_rdata[13] cfg_rdata[13] -type PO PO
add mapped point cfg_rdata[12] cfg_rdata[12] -type PO PO
add mapped point cfg_rdata[11] cfg_rdata[11] -type PO PO
add mapped point cfg_rdata[10] cfg_rdata[10] -type PO PO
add mapped point cfg_rdata[9] cfg_rdata[9] -type PO PO
add mapped point cfg_rdata[8] cfg_rdata[8] -type PO PO
add mapped point cfg_rdata[7] cfg_rdata[7] -type PO PO
add mapped point cfg_rdata[6] cfg_rdata[6] -type PO PO
add mapped point cfg_rdata[5] cfg_rdata[5] -type PO PO
add mapped point cfg_rdata[4] cfg_rdata[4] -type PO PO
add mapped point cfg_rdata[3] cfg_rdata[3] -type PO PO
add mapped point cfg_rdata[2] cfg_rdata[2] -type PO PO
add mapped point cfg_rdata[1] cfg_rdata[1] -type PO PO
add mapped point cfg_rdata[0] cfg_rdata[0] -type PO PO
add mapped point busy busy -type PO PO
add mapped point done done -type PO PO
add mapped point prbs_out prbs_out -type PO PO
add mapped point bit_error bit_error -type PO PO

//inout ports




//Sequential Pins
add mapped point u_csr_regbank/ctrl_reg[5]/q u_csr_regbank/ctrl_reg_reg[5]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[6]/q u_csr_regbank/ctrl_reg_reg[6]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[7]/q u_csr_regbank/ctrl_reg_reg[7]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[8]/q u_csr_regbank/ctrl_reg_reg[8]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[9]/q u_csr_regbank/ctrl_reg_reg[9]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[10]/q u_csr_regbank/ctrl_reg_reg[10]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[11]/q u_csr_regbank/ctrl_reg_reg[11]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[12]/q u_csr_regbank/ctrl_reg_reg[12]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[13]/q u_csr_regbank/ctrl_reg_reg[13]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[14]/q u_csr_regbank/ctrl_reg_reg[14]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[15]/q u_csr_regbank/ctrl_reg_reg[15]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[16]/q u_csr_regbank/ctrl_reg_reg[16]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[17]/q u_csr_regbank/ctrl_reg_reg[17]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[18]/q u_csr_regbank/ctrl_reg_reg[18]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[19]/q u_csr_regbank/ctrl_reg_reg[19]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[20]/q u_csr_regbank/ctrl_reg_reg[20]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[21]/q u_csr_regbank/ctrl_reg_reg[21]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[22]/q u_csr_regbank/ctrl_reg_reg[22]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[23]/q u_csr_regbank/ctrl_reg_reg[23]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[24]/q u_csr_regbank/ctrl_reg_reg[24]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[25]/q u_csr_regbank/ctrl_reg_reg[25]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[26]/q u_csr_regbank/ctrl_reg_reg[26]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[27]/q u_csr_regbank/ctrl_reg_reg[27]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[28]/q u_csr_regbank/ctrl_reg_reg[28]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[29]/q u_csr_regbank/ctrl_reg_reg[29]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[30]/q u_csr_regbank/ctrl_reg_reg[30]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[31]/q u_csr_regbank/ctrl_reg_reg[31]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[15]/q u_csr_regbank/seed_reg_reg[15]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[16]/q u_csr_regbank/seed_reg_reg[16]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[17]/q u_csr_regbank/seed_reg_reg[17]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[18]/q u_csr_regbank/seed_reg_reg[18]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[19]/q u_csr_regbank/seed_reg_reg[19]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[20]/q u_csr_regbank/seed_reg_reg[20]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[21]/q u_csr_regbank/seed_reg_reg[21]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[22]/q u_csr_regbank/seed_reg_reg[22]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[23]/q u_csr_regbank/seed_reg_reg[23]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[24]/q u_csr_regbank/seed_reg_reg[24]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[25]/q u_csr_regbank/seed_reg_reg[25]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[26]/q u_csr_regbank/seed_reg_reg[26]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[27]/q u_csr_regbank/seed_reg_reg[27]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[28]/q u_csr_regbank/seed_reg_reg[28]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[29]/q u_csr_regbank/seed_reg_reg[29]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[30]/q u_csr_regbank/seed_reg_reg[30]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[31]/q u_csr_regbank/seed_reg_reg[31]/Q -type DFF DFF
add mapped point u_csr_regbank/manual_clear_pulse/q u_csr_regbank/manual_clear_pulse_reg/Q -type DFF DFF
add mapped point u_csr_regbank/start_pulse/q u_csr_regbank/start_pulse_reg/Q -type DFF DFF
add mapped point u_csr_regbank/stop_pulse/q u_csr_regbank/stop_pulse_reg/Q -type DFF DFF
add mapped point u_csr_regbank/seed_load_pulse/q u_csr_regbank/seed_load_pulse_reg/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[18]/q u_csr_regbank/window_reg_reg[18]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[4]/q u_csr_regbank/window_reg_reg[4]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[0]/q u_csr_regbank/seed_reg_reg[0]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[9]/q u_csr_regbank/seed_reg_reg[9]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[10]/q u_csr_regbank/seed_reg_reg[10]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[11]/q u_csr_regbank/seed_reg_reg[11]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[12]/q u_csr_regbank/seed_reg_reg[12]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[13]/q u_csr_regbank/seed_reg_reg[13]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[14]/q u_csr_regbank/seed_reg_reg[14]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[8]/q u_csr_regbank/seed_reg_reg[8]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[7]/q u_csr_regbank/seed_reg_reg[7]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[0]/q u_csr_regbank/window_reg_reg[0]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[1]/q u_csr_regbank/window_reg_reg[1]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[3]/q u_csr_regbank/window_reg_reg[3]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[5]/q u_csr_regbank/window_reg_reg[5]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[6]/q u_csr_regbank/window_reg_reg[6]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[7]/q u_csr_regbank/window_reg_reg[7]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[8]/q u_csr_regbank/window_reg_reg[8]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[9]/q u_csr_regbank/window_reg_reg[9]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[10]/q u_csr_regbank/window_reg_reg[10]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[11]/q u_csr_regbank/window_reg_reg[11]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[12]/q u_csr_regbank/window_reg_reg[12]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[13]/q u_csr_regbank/window_reg_reg[13]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[14]/q u_csr_regbank/window_reg_reg[14]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[15]/q u_csr_regbank/window_reg_reg[15]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[16]/q u_csr_regbank/window_reg_reg[16]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[17]/q u_csr_regbank/window_reg_reg[17]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[2]/q u_csr_regbank/window_reg_reg[2]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[20]/q u_csr_regbank/window_reg_reg[20]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[21]/q u_csr_regbank/window_reg_reg[21]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[22]/q u_csr_regbank/window_reg_reg[22]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[23]/q u_csr_regbank/window_reg_reg[23]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[24]/q u_csr_regbank/window_reg_reg[24]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[25]/q u_csr_regbank/window_reg_reg[25]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[26]/q u_csr_regbank/window_reg_reg[26]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[27]/q u_csr_regbank/window_reg_reg[27]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[28]/q u_csr_regbank/window_reg_reg[28]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[0]/q u_csr_regbank/ctrl_reg_reg[0]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[3]/q u_csr_regbank/ctrl_reg_reg[3]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[29]/q u_csr_regbank/window_reg_reg[29]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[30]/q u_csr_regbank/window_reg_reg[30]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[4]/q u_csr_regbank/ctrl_reg_reg[4]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[31]/q u_csr_regbank/window_reg_reg[31]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[1]/q u_csr_regbank/ctrl_reg_reg[1]/Q -type DFF DFF
add mapped point u_csr_regbank/ctrl_reg[2]/q u_csr_regbank/ctrl_reg_reg[2]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[1]/q u_csr_regbank/seed_reg_reg[1]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[2]/q u_csr_regbank/seed_reg_reg[2]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[3]/q u_csr_regbank/seed_reg_reg[3]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[4]/q u_csr_regbank/seed_reg_reg[4]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[5]/q u_csr_regbank/seed_reg_reg[5]/Q -type DFF DFF
add mapped point u_csr_regbank/seed_reg[6]/q u_csr_regbank/seed_reg_reg[6]/Q -type DFF DFF
add mapped point u_csr_regbank/window_reg[19]/q u_csr_regbank/window_reg_reg[19]/Q -type DFF DFF
add mapped point u_measure_ctrl/clear_count_pulse/q u_measure_ctrl/clear_count_pulse_reg/Q -type DFF DFF
add mapped point u_measure_ctrl/busy_q/q u_measure_ctrl/busy_q_reg/Q -type DFF DFF
add mapped point u_measure_ctrl/done_q/q u_measure_ctrl/done_q_reg/Q -type DFF DFF
add mapped point u_measure_ctrl/overflow_q/q u_measure_ctrl/overflow_q_reg/Q -type DFF DFF
add mapped point u_measure_ctrl/skip_window_check_q/q u_measure_ctrl/skip_window_check_q_reg/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[4]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[3]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[2]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[1]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[0]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[5]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[6]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[12]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[11]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[10]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[9]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[8]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[7]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[6]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[5]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[4]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[3]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[2]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[1]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[0]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[13]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[14]/q u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_top/ref_bit_q/q u_prbs_ber_top/ref_bit_q_reg/Q -type DFF DFF
add mapped point u_prbs_ber_top/ext_serial_in_q/q u_prbs_ber_top/ext_serial_in_q_reg/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[0]/q u_prbs_ber_top/error_count_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[1]/q u_prbs_ber_top/error_count_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[2]/q u_prbs_ber_top/error_count_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[3]/q u_prbs_ber_top/error_count_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[4]/q u_prbs_ber_top/error_count_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[5]/q u_prbs_ber_top/error_count_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[6]/q u_prbs_ber_top/error_count_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[7]/q u_prbs_ber_top/error_count_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[8]/q u_prbs_ber_top/error_count_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[9]/q u_prbs_ber_top/error_count_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[10]/q u_prbs_ber_top/error_count_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[11]/q u_prbs_ber_top/error_count_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[12]/q u_prbs_ber_top/error_count_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[13]/q u_prbs_ber_top/error_count_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[14]/q u_prbs_ber_top/error_count_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[15]/q u_prbs_ber_top/error_count_reg[15]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[16]/q u_prbs_ber_top/error_count_reg[16]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[17]/q u_prbs_ber_top/error_count_reg[17]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[18]/q u_prbs_ber_top/error_count_reg[18]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[19]/q u_prbs_ber_top/error_count_reg[19]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[20]/q u_prbs_ber_top/error_count_reg[20]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[21]/q u_prbs_ber_top/error_count_reg[21]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[22]/q u_prbs_ber_top/error_count_reg[22]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[23]/q u_prbs_ber_top/error_count_reg[23]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[24]/q u_prbs_ber_top/error_count_reg[24]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[25]/q u_prbs_ber_top/error_count_reg[25]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[26]/q u_prbs_ber_top/error_count_reg[26]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[27]/q u_prbs_ber_top/error_count_reg[27]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[28]/q u_prbs_ber_top/error_count_reg[28]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[29]/q u_prbs_ber_top/error_count_reg[29]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[30]/q u_prbs_ber_top/error_count_reg[30]/Q -type DFF DFF
add mapped point u_prbs_ber_top/error_count[31]/q u_prbs_ber_top/error_count_reg[31]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[0]/q u_prbs_ber_top/total_count_reg[0]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[1]/q u_prbs_ber_top/total_count_reg[1]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[2]/q u_prbs_ber_top/total_count_reg[2]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[3]/q u_prbs_ber_top/total_count_reg[3]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[4]/q u_prbs_ber_top/total_count_reg[4]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[5]/q u_prbs_ber_top/total_count_reg[5]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[6]/q u_prbs_ber_top/total_count_reg[6]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[7]/q u_prbs_ber_top/total_count_reg[7]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[8]/q u_prbs_ber_top/total_count_reg[8]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[9]/q u_prbs_ber_top/total_count_reg[9]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[10]/q u_prbs_ber_top/total_count_reg[10]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[11]/q u_prbs_ber_top/total_count_reg[11]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[12]/q u_prbs_ber_top/total_count_reg[12]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[13]/q u_prbs_ber_top/total_count_reg[13]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[14]/q u_prbs_ber_top/total_count_reg[14]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[15]/q u_prbs_ber_top/total_count_reg[15]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[16]/q u_prbs_ber_top/total_count_reg[16]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[17]/q u_prbs_ber_top/total_count_reg[17]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[18]/q u_prbs_ber_top/total_count_reg[18]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[19]/q u_prbs_ber_top/total_count_reg[19]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[20]/q u_prbs_ber_top/total_count_reg[20]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[21]/q u_prbs_ber_top/total_count_reg[21]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[22]/q u_prbs_ber_top/total_count_reg[22]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[23]/q u_prbs_ber_top/total_count_reg[23]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[24]/q u_prbs_ber_top/total_count_reg[24]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[25]/q u_prbs_ber_top/total_count_reg[25]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[26]/q u_prbs_ber_top/total_count_reg[26]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[27]/q u_prbs_ber_top/total_count_reg[27]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[28]/q u_prbs_ber_top/total_count_reg[28]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[29]/q u_prbs_ber_top/total_count_reg[29]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[30]/q u_prbs_ber_top/total_count_reg[30]/Q -type DFF DFF
add mapped point u_prbs_ber_top/total_count[31]/q u_prbs_ber_top/total_count_reg[31]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
