catch {set_db port:prbs_ber_chip_top/clk .original_name clk}
catch {set_db port:prbs_ber_chip_top/rst_n .original_name rst_n}
catch {set_db port:prbs_ber_chip_top/ext_serial_in .original_name ext_serial_in}
catch {set_db port:prbs_ber_chip_top/cfg_we .original_name cfg_we}
catch {set_db port:prbs_ber_chip_top/cfg_re .original_name cfg_re}
catch {set_db {port:prbs_ber_chip_top/cfg_addr[4]} .original_name {cfg_addr[4]}}
catch {set_db {port:prbs_ber_chip_top/cfg_addr[3]} .original_name {cfg_addr[3]}}
catch {set_db {port:prbs_ber_chip_top/cfg_addr[2]} .original_name {cfg_addr[2]}}
catch {set_db {port:prbs_ber_chip_top/cfg_addr[1]} .original_name {cfg_addr[1]}}
catch {set_db {port:prbs_ber_chip_top/cfg_addr[0]} .original_name {cfg_addr[0]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[31]} .original_name {cfg_wdata[31]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[30]} .original_name {cfg_wdata[30]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[29]} .original_name {cfg_wdata[29]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[28]} .original_name {cfg_wdata[28]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[27]} .original_name {cfg_wdata[27]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[26]} .original_name {cfg_wdata[26]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[25]} .original_name {cfg_wdata[25]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[24]} .original_name {cfg_wdata[24]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[23]} .original_name {cfg_wdata[23]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[22]} .original_name {cfg_wdata[22]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[21]} .original_name {cfg_wdata[21]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[20]} .original_name {cfg_wdata[20]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[19]} .original_name {cfg_wdata[19]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[18]} .original_name {cfg_wdata[18]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[17]} .original_name {cfg_wdata[17]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[16]} .original_name {cfg_wdata[16]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[15]} .original_name {cfg_wdata[15]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[14]} .original_name {cfg_wdata[14]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[13]} .original_name {cfg_wdata[13]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[12]} .original_name {cfg_wdata[12]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[11]} .original_name {cfg_wdata[11]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[10]} .original_name {cfg_wdata[10]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[9]} .original_name {cfg_wdata[9]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[8]} .original_name {cfg_wdata[8]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[7]} .original_name {cfg_wdata[7]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[6]} .original_name {cfg_wdata[6]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[5]} .original_name {cfg_wdata[5]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[4]} .original_name {cfg_wdata[4]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[3]} .original_name {cfg_wdata[3]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[2]} .original_name {cfg_wdata[2]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[1]} .original_name {cfg_wdata[1]}}
catch {set_db {port:prbs_ber_chip_top/cfg_wdata[0]} .original_name {cfg_wdata[0]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[31]} .original_name {cfg_rdata[31]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[30]} .original_name {cfg_rdata[30]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[29]} .original_name {cfg_rdata[29]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[28]} .original_name {cfg_rdata[28]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[27]} .original_name {cfg_rdata[27]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[26]} .original_name {cfg_rdata[26]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[25]} .original_name {cfg_rdata[25]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[24]} .original_name {cfg_rdata[24]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[23]} .original_name {cfg_rdata[23]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[22]} .original_name {cfg_rdata[22]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[21]} .original_name {cfg_rdata[21]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[20]} .original_name {cfg_rdata[20]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[19]} .original_name {cfg_rdata[19]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[18]} .original_name {cfg_rdata[18]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[17]} .original_name {cfg_rdata[17]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[16]} .original_name {cfg_rdata[16]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[15]} .original_name {cfg_rdata[15]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[14]} .original_name {cfg_rdata[14]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[13]} .original_name {cfg_rdata[13]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[12]} .original_name {cfg_rdata[12]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[11]} .original_name {cfg_rdata[11]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[10]} .original_name {cfg_rdata[10]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[9]} .original_name {cfg_rdata[9]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[8]} .original_name {cfg_rdata[8]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[7]} .original_name {cfg_rdata[7]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[6]} .original_name {cfg_rdata[6]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[5]} .original_name {cfg_rdata[5]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[4]} .original_name {cfg_rdata[4]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[3]} .original_name {cfg_rdata[3]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[2]} .original_name {cfg_rdata[2]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[1]} .original_name {cfg_rdata[1]}}
catch {set_db {port:prbs_ber_chip_top/cfg_rdata[0]} .original_name {cfg_rdata[0]}}
catch {set_db port:prbs_ber_chip_top/busy .original_name busy}
catch {set_db port:prbs_ber_chip_top/done .original_name done}
catch {set_db port:prbs_ber_chip_top/prbs_out .original_name prbs_out}
catch {set_db port:prbs_ber_chip_top/bit_error .original_name bit_error}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[5]/Q} .original_name {u_csr_regbank/ctrl_reg[5]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[6]/Q} .original_name {u_csr_regbank/ctrl_reg[6]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[7]/Q} .original_name {u_csr_regbank/ctrl_reg[7]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[8]/Q} .original_name {u_csr_regbank/ctrl_reg[8]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[9]/Q} .original_name {u_csr_regbank/ctrl_reg[9]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[10]/Q} .original_name {u_csr_regbank/ctrl_reg[10]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[11]/Q} .original_name {u_csr_regbank/ctrl_reg[11]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[12]/Q} .original_name {u_csr_regbank/ctrl_reg[12]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[13]/Q} .original_name {u_csr_regbank/ctrl_reg[13]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[14]/Q} .original_name {u_csr_regbank/ctrl_reg[14]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[15]/Q} .original_name {u_csr_regbank/ctrl_reg[15]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[16]/Q} .original_name {u_csr_regbank/ctrl_reg[16]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[17]/Q} .original_name {u_csr_regbank/ctrl_reg[17]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[18]/Q} .original_name {u_csr_regbank/ctrl_reg[18]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[19]/Q} .original_name {u_csr_regbank/ctrl_reg[19]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[20]/Q} .original_name {u_csr_regbank/ctrl_reg[20]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[21]/Q} .original_name {u_csr_regbank/ctrl_reg[21]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[22]/Q} .original_name {u_csr_regbank/ctrl_reg[22]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[23]/Q} .original_name {u_csr_regbank/ctrl_reg[23]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[24]/Q} .original_name {u_csr_regbank/ctrl_reg[24]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[25]/Q} .original_name {u_csr_regbank/ctrl_reg[25]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[26]/Q} .original_name {u_csr_regbank/ctrl_reg[26]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[27]/Q} .original_name {u_csr_regbank/ctrl_reg[27]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[28]/Q} .original_name {u_csr_regbank/ctrl_reg[28]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[29]/Q} .original_name {u_csr_regbank/ctrl_reg[29]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[30]/Q} .original_name {u_csr_regbank/ctrl_reg[30]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[31]/Q} .original_name {u_csr_regbank/ctrl_reg[31]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[15]/Q} .original_name {u_csr_regbank/seed_reg[15]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[16]/Q} .original_name {u_csr_regbank/seed_reg[16]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[17]/Q} .original_name {u_csr_regbank/seed_reg[17]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[18]/Q} .original_name {u_csr_regbank/seed_reg[18]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[19]/Q} .original_name {u_csr_regbank/seed_reg[19]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[20]/Q} .original_name {u_csr_regbank/seed_reg[20]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[21]/Q} .original_name {u_csr_regbank/seed_reg[21]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[22]/Q} .original_name {u_csr_regbank/seed_reg[22]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[23]/Q} .original_name {u_csr_regbank/seed_reg[23]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[24]/Q} .original_name {u_csr_regbank/seed_reg[24]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[25]/Q} .original_name {u_csr_regbank/seed_reg[25]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[26]/Q} .original_name {u_csr_regbank/seed_reg[26]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[27]/Q} .original_name {u_csr_regbank/seed_reg[27]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[28]/Q} .original_name {u_csr_regbank/seed_reg[28]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[29]/Q} .original_name {u_csr_regbank/seed_reg[29]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[30]/Q} .original_name {u_csr_regbank/seed_reg[30]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[31]/Q} .original_name {u_csr_regbank/seed_reg[31]/q}}
catch {set_db pin:prbs_ber_chip_top/u_csr_regbank/manual_clear_pulse_reg/Q .original_name u_csr_regbank/manual_clear_pulse/q}
catch {set_db pin:prbs_ber_chip_top/u_csr_regbank/start_pulse_reg/Q .original_name u_csr_regbank/start_pulse/q}
catch {set_db pin:prbs_ber_chip_top/u_csr_regbank/stop_pulse_reg/Q .original_name u_csr_regbank/stop_pulse/q}
catch {set_db pin:prbs_ber_chip_top/u_csr_regbank/seed_load_pulse_reg/Q .original_name u_csr_regbank/seed_load_pulse/q}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[18]/Q} .original_name {u_csr_regbank/window_reg[18]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[4]/Q} .original_name {u_csr_regbank/window_reg[4]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[4]/QN} .original_name {u_csr_regbank/window_reg[4]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[0]/Q} .original_name {u_csr_regbank/seed_reg[0]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[0]/QN} .original_name {u_csr_regbank/seed_reg[0]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[9]/Q} .original_name {u_csr_regbank/seed_reg[9]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[10]/Q} .original_name {u_csr_regbank/seed_reg[10]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[11]/Q} .original_name {u_csr_regbank/seed_reg[11]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[12]/Q} .original_name {u_csr_regbank/seed_reg[12]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[13]/Q} .original_name {u_csr_regbank/seed_reg[13]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[14]/Q} .original_name {u_csr_regbank/seed_reg[14]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[8]/Q} .original_name {u_csr_regbank/seed_reg[8]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[7]/Q} .original_name {u_csr_regbank/seed_reg[7]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[0]/Q} .original_name {u_csr_regbank/window_reg[0]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[1]/Q} .original_name {u_csr_regbank/window_reg[1]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[3]/Q} .original_name {u_csr_regbank/window_reg[3]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[5]/Q} .original_name {u_csr_regbank/window_reg[5]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[6]/Q} .original_name {u_csr_regbank/window_reg[6]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[7]/Q} .original_name {u_csr_regbank/window_reg[7]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[8]/Q} .original_name {u_csr_regbank/window_reg[8]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[9]/Q} .original_name {u_csr_regbank/window_reg[9]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[10]/Q} .original_name {u_csr_regbank/window_reg[10]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[11]/Q} .original_name {u_csr_regbank/window_reg[11]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[12]/Q} .original_name {u_csr_regbank/window_reg[12]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[13]/Q} .original_name {u_csr_regbank/window_reg[13]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[14]/Q} .original_name {u_csr_regbank/window_reg[14]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[15]/Q} .original_name {u_csr_regbank/window_reg[15]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[16]/Q} .original_name {u_csr_regbank/window_reg[16]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[17]/Q} .original_name {u_csr_regbank/window_reg[17]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[2]/Q} .original_name {u_csr_regbank/window_reg[2]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[2]/QN} .original_name {u_csr_regbank/window_reg[2]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[20]/Q} .original_name {u_csr_regbank/window_reg[20]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[21]/Q} .original_name {u_csr_regbank/window_reg[21]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[22]/Q} .original_name {u_csr_regbank/window_reg[22]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[23]/Q} .original_name {u_csr_regbank/window_reg[23]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[24]/Q} .original_name {u_csr_regbank/window_reg[24]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[25]/Q} .original_name {u_csr_regbank/window_reg[25]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[26]/Q} .original_name {u_csr_regbank/window_reg[26]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[27]/Q} .original_name {u_csr_regbank/window_reg[27]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[28]/Q} .original_name {u_csr_regbank/window_reg[28]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[0]/Q} .original_name {u_csr_regbank/ctrl_reg[0]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[3]/Q} .original_name {u_csr_regbank/ctrl_reg[3]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[29]/Q} .original_name {u_csr_regbank/window_reg[29]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[30]/Q} .original_name {u_csr_regbank/window_reg[30]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[4]/Q} .original_name {u_csr_regbank/ctrl_reg[4]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[31]/Q} .original_name {u_csr_regbank/window_reg[31]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[1]/Q} .original_name {u_csr_regbank/ctrl_reg[1]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[2]/Q} .original_name {u_csr_regbank/ctrl_reg[2]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[1]/Q} .original_name {u_csr_regbank/seed_reg[1]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[2]/Q} .original_name {u_csr_regbank/seed_reg[2]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[3]/Q} .original_name {u_csr_regbank/seed_reg[3]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[4]/Q} .original_name {u_csr_regbank/seed_reg[4]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[5]/Q} .original_name {u_csr_regbank/seed_reg[5]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[6]/Q} .original_name {u_csr_regbank/seed_reg[6]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[19]/Q} .original_name {u_csr_regbank/window_reg[19]/q}}
catch {set_db pin:prbs_ber_chip_top/u_measure_ctrl/clear_count_pulse_reg/Q .original_name u_measure_ctrl/clear_count_pulse/q}
catch {set_db pin:prbs_ber_chip_top/u_measure_ctrl/busy_q_reg/Q .original_name u_measure_ctrl/busy_q/q}
catch {set_db pin:prbs_ber_chip_top/u_measure_ctrl/busy_q_reg/QN .original_name u_measure_ctrl/busy_q/q}
catch {set_db pin:prbs_ber_chip_top/u_measure_ctrl/done_q_reg/Q .original_name u_measure_ctrl/done_q/q}
catch {set_db pin:prbs_ber_chip_top/u_measure_ctrl/overflow_q_reg/Q .original_name u_measure_ctrl/overflow_q/q}
catch {set_db pin:prbs_ber_chip_top/u_measure_ctrl/skip_window_check_q_reg/Q .original_name u_measure_ctrl/skip_window_check_q/q}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[4]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[4]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[3]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[3]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[2]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[2]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[1]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[1]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[0]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[0]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[0]/QN} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[0]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[5]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[5]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[6]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[6]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[12]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[12]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[11]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[11]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[10]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[10]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[9]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[9]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[8]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[8]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[7]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[7]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[6]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[6]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[5]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[5]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[4]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[4]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[3]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[3]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[2]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[2]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[1]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[1]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[0]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[0]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[0]/QN} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[0]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[13]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[13]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[14]/Q} .original_name {u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[14]/q}}
catch {set_db pin:prbs_ber_chip_top/u_prbs_ber_top/ref_bit_q_reg/Q .original_name u_prbs_ber_top/ref_bit_q/q}
catch {set_db pin:prbs_ber_chip_top/u_prbs_ber_top/ext_serial_in_q_reg/Q .original_name u_prbs_ber_top/ext_serial_in_q/q}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[0]/Q} .original_name {u_prbs_ber_top/error_count[0]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[1]/Q} .original_name {u_prbs_ber_top/error_count[1]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[2]/Q} .original_name {u_prbs_ber_top/error_count[2]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[3]/Q} .original_name {u_prbs_ber_top/error_count[3]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[4]/Q} .original_name {u_prbs_ber_top/error_count[4]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[5]/Q} .original_name {u_prbs_ber_top/error_count[5]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[6]/Q} .original_name {u_prbs_ber_top/error_count[6]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[7]/Q} .original_name {u_prbs_ber_top/error_count[7]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[8]/Q} .original_name {u_prbs_ber_top/error_count[8]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[9]/Q} .original_name {u_prbs_ber_top/error_count[9]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[10]/Q} .original_name {u_prbs_ber_top/error_count[10]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[11]/Q} .original_name {u_prbs_ber_top/error_count[11]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[12]/Q} .original_name {u_prbs_ber_top/error_count[12]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[13]/Q} .original_name {u_prbs_ber_top/error_count[13]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[14]/Q} .original_name {u_prbs_ber_top/error_count[14]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[15]/Q} .original_name {u_prbs_ber_top/error_count[15]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[16]/Q} .original_name {u_prbs_ber_top/error_count[16]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[17]/Q} .original_name {u_prbs_ber_top/error_count[17]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[18]/Q} .original_name {u_prbs_ber_top/error_count[18]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[19]/Q} .original_name {u_prbs_ber_top/error_count[19]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[20]/Q} .original_name {u_prbs_ber_top/error_count[20]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[21]/Q} .original_name {u_prbs_ber_top/error_count[21]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[22]/Q} .original_name {u_prbs_ber_top/error_count[22]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[23]/Q} .original_name {u_prbs_ber_top/error_count[23]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[24]/Q} .original_name {u_prbs_ber_top/error_count[24]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[25]/Q} .original_name {u_prbs_ber_top/error_count[25]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[26]/Q} .original_name {u_prbs_ber_top/error_count[26]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[27]/Q} .original_name {u_prbs_ber_top/error_count[27]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[28]/Q} .original_name {u_prbs_ber_top/error_count[28]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[29]/Q} .original_name {u_prbs_ber_top/error_count[29]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[30]/Q} .original_name {u_prbs_ber_top/error_count[30]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[31]/Q} .original_name {u_prbs_ber_top/error_count[31]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[0]/Q} .original_name {u_prbs_ber_top/total_count[0]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[1]/Q} .original_name {u_prbs_ber_top/total_count[1]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[2]/Q} .original_name {u_prbs_ber_top/total_count[2]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[3]/Q} .original_name {u_prbs_ber_top/total_count[3]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[4]/Q} .original_name {u_prbs_ber_top/total_count[4]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[5]/Q} .original_name {u_prbs_ber_top/total_count[5]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[6]/Q} .original_name {u_prbs_ber_top/total_count[6]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[7]/Q} .original_name {u_prbs_ber_top/total_count[7]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[8]/Q} .original_name {u_prbs_ber_top/total_count[8]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[9]/Q} .original_name {u_prbs_ber_top/total_count[9]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[10]/Q} .original_name {u_prbs_ber_top/total_count[10]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[11]/Q} .original_name {u_prbs_ber_top/total_count[11]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[12]/Q} .original_name {u_prbs_ber_top/total_count[12]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[13]/Q} .original_name {u_prbs_ber_top/total_count[13]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[14]/Q} .original_name {u_prbs_ber_top/total_count[14]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[15]/Q} .original_name {u_prbs_ber_top/total_count[15]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[16]/Q} .original_name {u_prbs_ber_top/total_count[16]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[17]/Q} .original_name {u_prbs_ber_top/total_count[17]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[18]/Q} .original_name {u_prbs_ber_top/total_count[18]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[19]/Q} .original_name {u_prbs_ber_top/total_count[19]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[20]/Q} .original_name {u_prbs_ber_top/total_count[20]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[21]/Q} .original_name {u_prbs_ber_top/total_count[21]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[22]/Q} .original_name {u_prbs_ber_top/total_count[22]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[23]/Q} .original_name {u_prbs_ber_top/total_count[23]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[24]/Q} .original_name {u_prbs_ber_top/total_count[24]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[25]/Q} .original_name {u_prbs_ber_top/total_count[25]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[26]/Q} .original_name {u_prbs_ber_top/total_count[26]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[27]/Q} .original_name {u_prbs_ber_top/total_count[27]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[28]/Q} .original_name {u_prbs_ber_top/total_count[28]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[29]/Q} .original_name {u_prbs_ber_top/total_count[29]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[30]/Q} .original_name {u_prbs_ber_top/total_count[30]/q}}
catch {set_db {pin:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[31]/Q} .original_name {u_prbs_ber_top/total_count[31]/q}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[5]} .original_name {{u_csr_regbank/ctrl_reg[5]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[6]} .original_name {{u_csr_regbank/ctrl_reg[6]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[7]} .original_name {{u_csr_regbank/ctrl_reg[7]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[8]} .original_name {{u_csr_regbank/ctrl_reg[8]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[9]} .original_name {{u_csr_regbank/ctrl_reg[9]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[10]} .original_name {{u_csr_regbank/ctrl_reg[10]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[11]} .original_name {{u_csr_regbank/ctrl_reg[11]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[12]} .original_name {{u_csr_regbank/ctrl_reg[12]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[13]} .original_name {{u_csr_regbank/ctrl_reg[13]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[14]} .original_name {{u_csr_regbank/ctrl_reg[14]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[15]} .original_name {{u_csr_regbank/ctrl_reg[15]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[16]} .original_name {{u_csr_regbank/ctrl_reg[16]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[17]} .original_name {{u_csr_regbank/ctrl_reg[17]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[18]} .original_name {{u_csr_regbank/ctrl_reg[18]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[19]} .original_name {{u_csr_regbank/ctrl_reg[19]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[20]} .original_name {{u_csr_regbank/ctrl_reg[20]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[21]} .original_name {{u_csr_regbank/ctrl_reg[21]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[22]} .original_name {{u_csr_regbank/ctrl_reg[22]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[23]} .original_name {{u_csr_regbank/ctrl_reg[23]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[24]} .original_name {{u_csr_regbank/ctrl_reg[24]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[25]} .original_name {{u_csr_regbank/ctrl_reg[25]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[26]} .original_name {{u_csr_regbank/ctrl_reg[26]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[27]} .original_name {{u_csr_regbank/ctrl_reg[27]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[28]} .original_name {{u_csr_regbank/ctrl_reg[28]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[29]} .original_name {{u_csr_regbank/ctrl_reg[29]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[30]} .original_name {{u_csr_regbank/ctrl_reg[30]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[31]} .original_name {{u_csr_regbank/ctrl_reg[31]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[15]} .original_name {{u_csr_regbank/seed_reg[15]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[16]} .original_name {{u_csr_regbank/seed_reg[16]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[17]} .original_name {{u_csr_regbank/seed_reg[17]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[18]} .original_name {{u_csr_regbank/seed_reg[18]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[19]} .original_name {{u_csr_regbank/seed_reg[19]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[20]} .original_name {{u_csr_regbank/seed_reg[20]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[21]} .original_name {{u_csr_regbank/seed_reg[21]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[22]} .original_name {{u_csr_regbank/seed_reg[22]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[23]} .original_name {{u_csr_regbank/seed_reg[23]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[24]} .original_name {{u_csr_regbank/seed_reg[24]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[25]} .original_name {{u_csr_regbank/seed_reg[25]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[26]} .original_name {{u_csr_regbank/seed_reg[26]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[27]} .original_name {{u_csr_regbank/seed_reg[27]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[28]} .original_name {{u_csr_regbank/seed_reg[28]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[29]} .original_name {{u_csr_regbank/seed_reg[29]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[30]} .original_name {{u_csr_regbank/seed_reg[30]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[31]} .original_name {{u_csr_regbank/seed_reg[31]}}}
catch {set_db inst:prbs_ber_chip_top/u_csr_regbank/manual_clear_pulse_reg .original_name u_csr_regbank/manual_clear_pulse}
catch {set_db inst:prbs_ber_chip_top/u_csr_regbank/start_pulse_reg .original_name u_csr_regbank/start_pulse}
catch {set_db inst:prbs_ber_chip_top/u_csr_regbank/stop_pulse_reg .original_name u_csr_regbank/stop_pulse}
catch {set_db inst:prbs_ber_chip_top/u_csr_regbank/seed_load_pulse_reg .original_name u_csr_regbank/seed_load_pulse}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[18]} .original_name {{u_csr_regbank/window_reg[18]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[4]} .original_name {{u_csr_regbank/window_reg[4]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[0]} .original_name {{u_csr_regbank/seed_reg[0]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[9]} .original_name {{u_csr_regbank/seed_reg[9]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[10]} .original_name {{u_csr_regbank/seed_reg[10]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[11]} .original_name {{u_csr_regbank/seed_reg[11]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[12]} .original_name {{u_csr_regbank/seed_reg[12]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[13]} .original_name {{u_csr_regbank/seed_reg[13]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[14]} .original_name {{u_csr_regbank/seed_reg[14]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[8]} .original_name {{u_csr_regbank/seed_reg[8]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[7]} .original_name {{u_csr_regbank/seed_reg[7]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[0]} .original_name {{u_csr_regbank/window_reg[0]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[1]} .original_name {{u_csr_regbank/window_reg[1]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[3]} .original_name {{u_csr_regbank/window_reg[3]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[5]} .original_name {{u_csr_regbank/window_reg[5]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[6]} .original_name {{u_csr_regbank/window_reg[6]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[7]} .original_name {{u_csr_regbank/window_reg[7]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[8]} .original_name {{u_csr_regbank/window_reg[8]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[9]} .original_name {{u_csr_regbank/window_reg[9]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[10]} .original_name {{u_csr_regbank/window_reg[10]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[11]} .original_name {{u_csr_regbank/window_reg[11]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[12]} .original_name {{u_csr_regbank/window_reg[12]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[13]} .original_name {{u_csr_regbank/window_reg[13]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[14]} .original_name {{u_csr_regbank/window_reg[14]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[15]} .original_name {{u_csr_regbank/window_reg[15]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[16]} .original_name {{u_csr_regbank/window_reg[16]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[17]} .original_name {{u_csr_regbank/window_reg[17]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[2]} .original_name {{u_csr_regbank/window_reg[2]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[20]} .original_name {{u_csr_regbank/window_reg[20]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[21]} .original_name {{u_csr_regbank/window_reg[21]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[22]} .original_name {{u_csr_regbank/window_reg[22]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[23]} .original_name {{u_csr_regbank/window_reg[23]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[24]} .original_name {{u_csr_regbank/window_reg[24]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[25]} .original_name {{u_csr_regbank/window_reg[25]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[26]} .original_name {{u_csr_regbank/window_reg[26]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[27]} .original_name {{u_csr_regbank/window_reg[27]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[28]} .original_name {{u_csr_regbank/window_reg[28]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[0]} .original_name {{u_csr_regbank/ctrl_reg[0]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[3]} .original_name {{u_csr_regbank/ctrl_reg[3]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[29]} .original_name {{u_csr_regbank/window_reg[29]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[30]} .original_name {{u_csr_regbank/window_reg[30]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[4]} .original_name {{u_csr_regbank/ctrl_reg[4]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[31]} .original_name {{u_csr_regbank/window_reg[31]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[1]} .original_name {{u_csr_regbank/ctrl_reg[1]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/ctrl_reg_reg[2]} .original_name {{u_csr_regbank/ctrl_reg[2]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[1]} .original_name {{u_csr_regbank/seed_reg[1]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[2]} .original_name {{u_csr_regbank/seed_reg[2]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[3]} .original_name {{u_csr_regbank/seed_reg[3]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[4]} .original_name {{u_csr_regbank/seed_reg[4]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[5]} .original_name {{u_csr_regbank/seed_reg[5]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/seed_reg_reg[6]} .original_name {{u_csr_regbank/seed_reg[6]}}}
catch {set_db {inst:prbs_ber_chip_top/u_csr_regbank/window_reg_reg[19]} .original_name {{u_csr_regbank/window_reg[19]}}}
catch {set_db inst:prbs_ber_chip_top/u_measure_ctrl/clear_count_pulse_reg .original_name u_measure_ctrl/clear_count_pulse}
catch {set_db inst:prbs_ber_chip_top/u_measure_ctrl/busy_q_reg .original_name u_measure_ctrl/busy_q}
catch {set_db inst:prbs_ber_chip_top/u_measure_ctrl/done_q_reg .original_name u_measure_ctrl/done_q}
catch {set_db inst:prbs_ber_chip_top/u_measure_ctrl/overflow_q_reg .original_name u_measure_ctrl/overflow_q}
catch {set_db inst:prbs_ber_chip_top/u_measure_ctrl/skip_window_check_q_reg .original_name u_measure_ctrl/skip_window_check_q}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[4]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[4]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[3]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[3]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[2]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[2]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[1]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[1]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[0]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[0]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[5]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[5]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q_reg[6]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs7_top/u_prbs_core/lfsr_q[6]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[12]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[12]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[11]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[11]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[10]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[10]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[9]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[9]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[8]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[8]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[7]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[7]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[6]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[6]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[5]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[5]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[4]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[4]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[3]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[3]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[2]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[2]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[1]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[1]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[0]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[0]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[13]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[13]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q_reg[14]} .original_name {{u_prbs_ber_top/u_prbs_gen_top/u_prbs15_top/u_prbs15_core/lfsr_q[14]}}}
catch {set_db inst:prbs_ber_chip_top/u_prbs_ber_top/ref_bit_q_reg .original_name u_prbs_ber_top/ref_bit_q}
catch {set_db inst:prbs_ber_chip_top/u_prbs_ber_top/ext_serial_in_q_reg .original_name u_prbs_ber_top/ext_serial_in_q}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[0]} .original_name {{u_prbs_ber_top/error_count[0]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[1]} .original_name {{u_prbs_ber_top/error_count[1]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[2]} .original_name {{u_prbs_ber_top/error_count[2]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[3]} .original_name {{u_prbs_ber_top/error_count[3]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[4]} .original_name {{u_prbs_ber_top/error_count[4]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[5]} .original_name {{u_prbs_ber_top/error_count[5]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[6]} .original_name {{u_prbs_ber_top/error_count[6]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[7]} .original_name {{u_prbs_ber_top/error_count[7]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[8]} .original_name {{u_prbs_ber_top/error_count[8]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[9]} .original_name {{u_prbs_ber_top/error_count[9]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[10]} .original_name {{u_prbs_ber_top/error_count[10]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[11]} .original_name {{u_prbs_ber_top/error_count[11]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[12]} .original_name {{u_prbs_ber_top/error_count[12]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[13]} .original_name {{u_prbs_ber_top/error_count[13]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[14]} .original_name {{u_prbs_ber_top/error_count[14]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[15]} .original_name {{u_prbs_ber_top/error_count[15]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[16]} .original_name {{u_prbs_ber_top/error_count[16]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[17]} .original_name {{u_prbs_ber_top/error_count[17]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[18]} .original_name {{u_prbs_ber_top/error_count[18]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[19]} .original_name {{u_prbs_ber_top/error_count[19]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[20]} .original_name {{u_prbs_ber_top/error_count[20]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[21]} .original_name {{u_prbs_ber_top/error_count[21]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[22]} .original_name {{u_prbs_ber_top/error_count[22]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[23]} .original_name {{u_prbs_ber_top/error_count[23]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[24]} .original_name {{u_prbs_ber_top/error_count[24]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[25]} .original_name {{u_prbs_ber_top/error_count[25]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[26]} .original_name {{u_prbs_ber_top/error_count[26]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[27]} .original_name {{u_prbs_ber_top/error_count[27]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[28]} .original_name {{u_prbs_ber_top/error_count[28]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[29]} .original_name {{u_prbs_ber_top/error_count[29]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[30]} .original_name {{u_prbs_ber_top/error_count[30]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/error_count_reg[31]} .original_name {{u_prbs_ber_top/error_count[31]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[0]} .original_name {{u_prbs_ber_top/total_count[0]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[1]} .original_name {{u_prbs_ber_top/total_count[1]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[2]} .original_name {{u_prbs_ber_top/total_count[2]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[3]} .original_name {{u_prbs_ber_top/total_count[3]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[4]} .original_name {{u_prbs_ber_top/total_count[4]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[5]} .original_name {{u_prbs_ber_top/total_count[5]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[6]} .original_name {{u_prbs_ber_top/total_count[6]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[7]} .original_name {{u_prbs_ber_top/total_count[7]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[8]} .original_name {{u_prbs_ber_top/total_count[8]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[9]} .original_name {{u_prbs_ber_top/total_count[9]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[10]} .original_name {{u_prbs_ber_top/total_count[10]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[11]} .original_name {{u_prbs_ber_top/total_count[11]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[12]} .original_name {{u_prbs_ber_top/total_count[12]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[13]} .original_name {{u_prbs_ber_top/total_count[13]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[14]} .original_name {{u_prbs_ber_top/total_count[14]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[15]} .original_name {{u_prbs_ber_top/total_count[15]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[16]} .original_name {{u_prbs_ber_top/total_count[16]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[17]} .original_name {{u_prbs_ber_top/total_count[17]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[18]} .original_name {{u_prbs_ber_top/total_count[18]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[19]} .original_name {{u_prbs_ber_top/total_count[19]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[20]} .original_name {{u_prbs_ber_top/total_count[20]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[21]} .original_name {{u_prbs_ber_top/total_count[21]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[22]} .original_name {{u_prbs_ber_top/total_count[22]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[23]} .original_name {{u_prbs_ber_top/total_count[23]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[24]} .original_name {{u_prbs_ber_top/total_count[24]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[25]} .original_name {{u_prbs_ber_top/total_count[25]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[26]} .original_name {{u_prbs_ber_top/total_count[26]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[27]} .original_name {{u_prbs_ber_top/total_count[27]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[28]} .original_name {{u_prbs_ber_top/total_count[28]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[29]} .original_name {{u_prbs_ber_top/total_count[29]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[30]} .original_name {{u_prbs_ber_top/total_count[30]}}}
catch {set_db {inst:prbs_ber_chip_top/u_prbs_ber_top/total_count_reg[31]} .original_name {{u_prbs_ber_top/total_count[31]}}}
